/* Stick War: original deterministic strategy simulation. */
(()=>{'use strict';
const WORLD=2800,BASE=[160,2640],MINE=[410,2390],CAP=36;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),fin=(n,d=0)=>Number.isFinite(Number(n))?Number(n):d;
function rng(seed){let x=seed>>>0||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
const UNITS=[
 {id:'miner',name:'Miner',cost:100,pop:1,hp:90,damage:7,range:38,speed:73,rate:1.2,train:3,unlock:0,description:'Carries gold home. Your economy starts here.'},
 {id:'sword',name:'Swordsman',cost:125,pop:1,hp:135,damage:22,range:48,speed:105,rate:.85,train:4,unlock:0,description:'Fast infantry. Rush archers and protect miners.'},
 {id:'archer',name:'Archer',cost:220,pop:2,hp:95,damage:19,range:340,speed:82,rate:1.5,train:6,unlock:1,description:'Long range. Keep a frontline between them and danger.'},
 {id:'spear',name:'Spearman',cost:360,pop:3,hp:360,damage:33,range:78,speed:73,rate:1.3,train:8,unlock:3,description:'Armoured shield wall. Blocks frontal arrows.'},
 {id:'mage',name:'Mage',cost:600,pop:4,hp:170,damage:42,range:245,speed:63,rate:3.3,train:11,unlock:6,description:'Area stun and summoned minions break dense armies.'},
 {id:'giant',name:'Giant',cost:900,pop:6,hp:1050,damage:85,range:110,speed:55,rate:2.4,train:15,unlock:8,description:'Heavy stomps and enormous statue damage.'}
];
const EXTRA={minion:{id:'minion',name:'Minion',hp:55,damage:12,range:40,speed:110,rate:.8,pop:0},dead:{id:'dead',name:'Dead',hp:80,damage:13,range:42,speed:77,rate:1.1,pop:1},brute:{id:'brute',name:'Dead Giant',hp:520,damage:47,range:85,speed:51,rate:2,pop:4}};
const def=id=>UNITS.find(u=>u.id===id)||EXTRA[id]||UNITS[1];
const MAPS=[{id:'meadow',name:'Golden Meadows',sky:['#d5ccaa','#f3dfad'],mountain:'#727b69',hill:'#667353',grass:'#77764d',ground:'#554d35'}, {id:'desert',name:'Ashen Dunes',sky:['#c9896a','#f4c087'],mountain:'#876057',hill:'#a87952',grass:'#a18752',ground:'#67513b'}, {id:'frost',name:'Frost Peaks',sky:['#6a899d','#c8d4cb'],mountain:'#657e8c',hill:'#8a9f99',grass:'#a7b4a6',ground:'#53626a'}, {id:'night',name:'Moonlit Hollow',sky:['#1e2b3c','#68717d'],mountain:'#303d4b',hill:'#3b4c4e',grass:'#596154',ground:'#333e38'}];
const MISSIONS=[
 {name:'First Banner',map:'meadow',enemy:['sword','sword','sword'],start:['miner','miner','sword'],gold:300,enemyGold:180,initial:['miner','miner','sword'],pace:12,power:.78,brief:'The valley is undefended. Build your economy and lead a first strike.',tip:'Train miners first. Gold arrives only when a miner returns to your statue.'},
 {name:'Archer Ridge',map:'meadow',enemy:['archer','archer','sword'],start:['miner','miner','sword','sword'],gold:360,enemyGold:350,initial:['miner','miner','archer','archer'],pace:9,power:.88,brief:'A line of bows controls the ridge. Close the distance before the arrows stack up.',tip:'Swordsmen are quick enough to pressure archers. Your own archers are now available.'},
 {name:'Night Ambush',map:'night',enemy:['sword'],start:['miner','miner','sword','sword','archer'],gold:450,initial:[],mode:'hold',duration:100,pace:18,power:.9,brief:'Raiders have found your camp. Hold your statue until dawn.',tip:'Defend keeps your soldiers near the mine. Garrison retreats and heals them.'},
 {name:'The Shield Line',map:'desert',enemy:['spear','sword','archer'],start:['miner','miner','sword','archer'],gold:520,enemyGold:420,initial:['miner','miner','spear','sword'],pace:10,power:.93,brief:'Spears stand between you and the dunes. Build a balanced army and break their line.',tip:'Spearmen resist frontal arrows. Attack from behind while directly controlling a unit.'},
 {name:'Dust and Iron',map:'desert',enemy:['sword','spear','sword','archer'],start:['miner','miner','spear','sword'],gold:520,enemyGold:500,initial:['miner','miner','sword','archer','spear'],pace:8,power:1,brief:'An iron legion is gathering. Spend carefully and choose the moment to attack.',tip:'Training takes time. Queue reinforcements before your frontline falls.'},
 {name:'Broken Pass',map:'meadow',enemy:['spear','archer','archer'],start:['miner','miner','spear','archer'],gold:600,enemyGold:550,initial:['miner','miner','spear','archer','archer'],pace:8,power:1,brief:'The defenders occupy a narrow pass. Their final reserves will join when the statue cracks.',tip:'A damaged enemy statue can trigger a counterattack. Keep reinforcements ready.'},
 {name:'The Spellkeepers',map:'night',enemy:['mage','sword','sword','archer'],start:['miner','miner','spear','archer'],gold:700,enemyGold:720,initial:['miner','miner','mage','sword','archer'],pace:9,power:1,brief:'The hollow hums with magic. Enemy casters stun packed armies and summon fighters.',tip:'Archers can outrange mages. Your own mage can stun a crowd with an area spell.'},
 {name:'Siege of Ember',map:'desert',enemy:['spear','mage','archer','sword'],start:['miner','miner','spear','archer','sword'],gold:700,enemyGold:750,initial:['miner','miner','spear','mage','archer'],pace:8,power:1.03,brief:'Ember is guarded by a complete army. Use every unit in the role it does best.',tip:'Control a miner for faster work, or a fighter for precise attacks and blocks.'},
 {name:'Footsteps of Giants',map:'meadow',enemy:['giant','sword','archer'],start:['miner','miner','spear','archer','mage'],gold:950,enemyGold:1000,initial:['miner','miner','giant','sword'],pace:11,power:1,brief:'The earth shakes. Bring down a giant without losing your frontline.',tip:'Giant stomps hit nearby units. Spread out and keep ranged units behind shields.'},
 {name:'The Long Night',map:'night',enemy:['dead','dead','brute'],start:['miner','miner','spear','archer','mage'],gold:850,initial:[],mode:'hold',duration:140,pace:20,power:1.05,brief:'The dead march in from the dark. Survive the night with your statue standing.',tip:'Mages punish dense waves. Garrison when your army needs time to recover.'},
 {name:'Icebound',map:'frost',enemy:['spear','archer','mage','giant'],start:['miner','miner','spear','archer','mage'],gold:900,enemyGold:1050,initial:['miner','miner','giant','spear','archer'],pace:9,power:1.04,brief:'The northern fortress holds the last passage. Snow slows every march equally.',tip:'Movement is slower here. An early economy and a prepared army matter more.'},
 {name:'The Last Standard',map:'desert',enemy:['spear','mage','giant','archer'],start:['miner','miner','spear','archer','mage'],gold:1100,enemyGold:1200,initial:['miner','miner','spear','mage','giant'],pace:9,power:1.08,boss:true,brief:'One statue remains. Its king will fight when his standard begins to fall.',tip:'The final guardian is powerful. Keep your miners alive and train a mixed army.'}
].map((m,i)=>({...m,id:i+1}));
const UPGRADE_IDS=['miner','sword','archer','spear','mage','giant','statue','income'];
const UPGRADE_INFO={miner:['Heavy satchels','Carry more gold and mine faster.'],sword:['Forged blades','More health and stronger sword strikes.'],archer:['Longbows','Stronger arrows and longer range.'],spear:['Bronze armour','More health and tougher shields.'],mage:['Arcane mastery','Stronger spells and faster casting.'],giant:['Ancient strength','More health and devastating stomps.'],statue:['Stone foundations','More statue health and faster garrison healing.'],income:['Royal treasury','Earn a little gold from the statue every second.']};
function clean(raw={}){const d=raw&&typeof raw==='object'?raw:{},p=d.prefs||{},stars=Array.from({length:12},(_,i)=>Math.floor(clamp(fin(d.stars?.[i]),0,3))),upgrades={};for(const id of UPGRADE_IDS)upgrades[id]=Math.floor(clamp(fin(d.upgrades?.[id]),0,3));const earned=stars.filter(Boolean).length*2,spent=Object.values(upgrades).reduce((a,b)=>a+b,0);if(spent>earned){for(const id of UPGRADE_IDS)upgrades[id]=0;}return{version:1,stars,upgrades,points:earned-Object.values(upgrades).reduce((a,b)=>a+b,0),bestWave:Math.floor(clamp(fin(d.bestWave),0,9999)),wins:Math.floor(clamp(fin(d.wins),0,999999)),prefs:{sound:p.sound!==false,motion:p.motion!==false,difficulty:['easy','normal','hard','random'].includes(p.difficulty)?p.difficulty:'normal',map:MAPS.some(m=>m.id===p.map)||p.map==='random'?p.map:'random'}};}
class Profile{constructor(raw){this.save=clean(raw);}unlocked(){return Math.min(12,this.save.stars.findIndex(s=>!s)<0?12:this.save.stars.findIndex(s=>!s)+1);}upgrade(id){if(!UPGRADE_IDS.includes(id)||this.save.points<1||this.save.upgrades[id]>=3)return false;this.save.upgrades[id]++;this.save.points--;return true;}complete(b){if(b.settled)return 0;b.settled=true;if(b.mode==='survival'){this.save.bestWave=Math.max(this.save.bestWave,b.wave);return 0;}if(b.winner!==0)return 0;this.save.wins++;if(b.mode!=='campaign')return 0;const i=b.mission.id-1,first=!this.save.stars[i],rating=(b.base[0].hp/b.base[0].max>.65?1:0)+(b.time<240?1:0)+1;this.save.stars[i]=Math.max(this.save.stars[i],rating);if(first)this.save.points+=2;return first?2:0;}export(){return clean(this.save);}}
class Battle{
 constructor({mode='campaign',mission=1,difficulty='normal',map='random',upgrades={},seed=1}={}){this.mode=['campaign','skirmish','survival'].includes(mode)?mode:'campaign';this.mission=MISSIONS[clamp(Math.floor(mission)-1,0,11)];this.random=rng(seed);this.difficulty=difficulty==='random'?['easy','normal','hard'][Math.floor(this.random()*3)]:difficulty;this.power={easy:.8,normal:1,hard:1.18}[this.difficulty]||1;this.map=this.mode==='campaign'?this.mission.map:map==='random'?MAPS[Math.floor(this.random()*MAPS.length)].id:MAPS.some(m=>m.id===map)?map:'meadow';this.upgrades={};for(const id of UPGRADE_IDS)this.upgrades[id]=clamp(fin(upgrades[id]),0,3);this.time=0;this.gold=[this.mode==='campaign'?this.mission.gold:600,this.mode==='campaign'?this.mission.enemyGold||0:650];this.commands=['defend','defend'];this.queue=[[],[]];this.units=[];this.projectiles=[];this.effects=[];this.corpses=[];this.events=[];this.id=1;this.selected=null;this.manual={x:0,y:0,attack:false,block:false};this.base=BASE.map((x,team)=>({base:true,uid:-1-team,team,x,y:0,hp:team?this.mode==='campaign'?this.mission.id===1?900:1600+(this.mission.id*50):1800:1800+this.upgrades.statue*300,max:team?this.mode==='campaign'?this.mission.id===1?900:1600+this.mission.id*50:1800:1800+this.upgrades.statue*300,flash:0}));this.aiClock=4;this.reserve=false;this.done=false;this.winner=null;this.reason='';this.wave=0;this.nextWave=this.mode==='survival'?20:12;this.tower=[0,0];this.kills=[0,0];this.lastIncome=0;
 const starts=this.mode==='campaign'?this.mission.start:['miner','miner','sword','archer'];for(const id of starts)this.spawn(0,id);const enemy=this.mode==='campaign'?this.mission.initial||[]:['miner','miner','sword','archer'];if(this.mode==='survival')this.gold[1]=0;else for(const id of enemy)this.spawn(1,id);this.events.push({type:'brief',text:this.objective()});}
 objective(){if(this.mode==='survival')return'Hold the line. Survive as many waves as you can.';if(this.mode==='campaign'&&this.mission.mode==='hold')return'Survive until dawn · '+this.mission.duration+' seconds';return'Destroy the enemy statue. Protect your own.';}
 allowed(id,team=0){return!!UNITS.find(u=>u.id===id)&&(team===1||this.mode!=='campaign'||def(id).unlock<this.mission.id);}
 population(team){return this.units.filter(u=>u.team===team&&u.hp>0).reduce((a,u)=>a+u.pop,0);}
 reserved(team){return this.queue[team].reduce((a,q)=>a+def(q.id).pop,0);}
 train(id,team=0){const d=def(id);if(!this.allowed(id,team)||this.done)return'Locked';if(this.queue[team].length>=6)return'Training queue is full';if(this.population(team)+this.reserved(team)+d.pop>CAP)return'Army capacity reached';if(this.gold[team]<d.cost)return'Not enough gold';this.gold[team]-=d.cost;this.queue[team].push({id,left:d.train,total:d.train,cost:d.cost});this.events.push({type:'train',team,id});return null;}
 cancel(team=0){const q=this.queue[team].pop();if(!q)return false;this.gold[team]+=q.cost;return true;}
 spawn(team,id,{x,y,boss=false,power}={}){const d=def(id),level=team===0?this.upgrades[id]||0:0,p=power??(team?this.power*(this.mode==='campaign'?this.mission.power:1):1),hp=d.hp*p*(1+level*(id==='spear'?.2:.1))*(boss?2.1:1),u={uid:this.id++,id,team,x:x??BASE[team]+(team?-1:1)*(40+this.random()*80),y:y??(this.random()-.5)*86,hp,max:hp,damage:d.damage*p*(1+level*.15)*(boss?1.45:1),range:d.range+(id==='archer'?level*20:0),speed:d.speed*(this.map==='frost'?.87:1),rate:d.rate*(id==='mage'?1-level*.08:1),pop:d.pop||0,face:team?-1:1,cooldown:this.random()*.5,stun:0,flash:0,walk:this.random()*10,state:'walk',carry:0,mining:0,swing:0,spell:8,boss,age:0,guard:false};this.units.push(u);return u;}
 command(cmd,team=0){if(!['defend','attack','garrison'].includes(cmd))return;this.commands[team]=cmd;this.events.push({type:'command',team,cmd});}
 control(uid){const u=this.units.find(u=>u.uid===uid&&u.team===0&&u.hp>0);this.selected=u?.uid??null;this.manual={x:0,y:0,attack:false,block:false};return u||null;}
 special(){const u=this.units.find(u=>u.uid===this.selected&&u.hp>0);if(!u||this.done)return'Control a spearman or mage first';if(u.id==='spear'){if(u.spearThrown)return'This spear has already been thrown';const t=this.target(u);if(!t.unit||t.distance>550)return'Move closer to an enemy';u.spearThrown=true;u.range=48;u.swing=.38;const duration=Math.max(.15,t.distance/700);this.projectiles.push({team:u.team,source:u.uid,id:'spear',x:u.x,y:u.y-40,tx:t.unit.x,ty:t.unit.y-30,target:t.unit.uid,t:duration,max:duration,damage:u.damage*2.5});return null;}if(u.id==='mage'){if(u.spell>0)return'Summon ready in '+Math.ceil(u.spell)+'s';if(this.units.filter(v=>v.team===u.team&&v.id==='minion'&&v.hp>0).length>=6)return'Six minions are already fighting';u.spell=16;for(let i=0;i<2;i++)this.spawn(u.team,'minion',{x:u.x+u.face*35,y:u.y+i*20,power:1});this.effects.push({type:'summon',x:u.x,y:u.y,t:.65,max:.65,team:u.team});return null;}return'This unit has no special ability';}
 target(u){const enemies=this.units.filter(v=>v.team!==u.team&&v.hp>0&&v.state!=='garrison');let near=null,best=Infinity;for(const v of enemies){const d=Math.hypot(v.x-u.x,(v.y-u.y)*1.2);if(d<best){best=d;near=v;}}const statue=this.base[1-u.team],bd=Math.hypot(statue.x-u.x,u.y);if(statue.hp>0&&bd<best&&(u.team===1||this.mode!=='survival'&&!(this.mode==='campaign'&&this.mission.mode==='hold'))){near=statue;best=bd;}return{unit:near,distance:best};}
 move(u,x,y,dt){const dx=x-u.x,dy=y-u.y,d=Math.hypot(dx,dy);if(d<3){u.state='idle';return;}const step=Math.min(d,u.speed*dt);u.x+=dx/d*step;u.y+=dy/d*step*.7;u.face=dx<0?-1:1;u.walk+=dt*9;u.state='walk';}
 hurt(v,amount,source,{stun=0,ignoreShield=false}={}){if(!v||v.hp<=0)return;if(!v.base&&(v.guard||v.id==='spear')&&!ignoreShield&&Math.sign(source.x-v.x)===v.face){amount*=v.guard?.25:.65;}if(v.base&&source.id==='archer')amount*=.45;if(source.uid===this.selected)amount*=1.3;v.hp=Math.max(0,v.hp-amount);v.flash=.13;if(!v.base)v.stun=Math.max(v.stun,stun);this.effects.push({type:'hit',x:v.x,y:v.y-35,t:.28,max:.28,team:source.team});if(v.hp===0){if(v.base){this.finish(source.team,'The enemy statue has fallen.');}else{this.kills[source.team]++;this.corpses.push({...v,t:2.8});this.events.push({type:'kill',team:source.team,id:v.id});if(this.selected===v.uid)this.control(null);}}}
 strike(u,t){if(u.cooldown>0||!t||t.hp<=0)return false;u.cooldown=u.rate;u.swing=.38;u.state='attack';u.face=t.x<u.x?-1:1;const range=u.range+(!t.base&&t.id==='giant'?20:0);if(Math.hypot(t.x-u.x,(t.y-u.y)*1.2)>range+20)return false;if(u.id==='archer'){const dist=Math.hypot(t.x-u.x,t.y-u.y);this.projectiles.push({team:u.team,source:u.uid,id:u.id,x:u.x,y:u.y-43,tx:t.x,ty:t.y-30,target:t.uid,t:Math.max(.15,dist/560),max:Math.max(.15,dist/560),damage:u.damage});}else if(u.id==='mage'||u.id==='giant'||u.id==='brute'){const radius=u.id==='mage'?105:95;this.effects.push({type:u.id==='mage'?'spell':'stomp',x:t.x,y:t.y,t:.6,max:.6,team:u.team});for(const v of [...this.units,this.base[1-u.team]])if(v.team!==u.team&&v.hp>0&&Math.hypot(v.x-t.x,v.y-t.y)<radius)this.hurt(v,u.damage,u,{stun:u.id==='mage'?.85:.4,ignoreShield:true});}else this.hurt(t,u.damage,u);this.events.push({type:'attack',id:u.id,team:u.team});return true;}
 mine(u,dt,manual=false){const dir=u.team?-1:1,mine=MINE[u.team],base=BASE[u.team],capacity=55+(u.team===0?this.upgrades.miner*15:0);if(u.carry>=capacity){if(Math.abs(u.x-base)<35){this.gold[u.team]+=u.carry;this.events.push({type:'gold',team:u.team,amount:Math.round(u.carry),x:u.x});u.carry=0;u.mining=0;}else if(!manual)this.move(u,base+dir*18,u.y,dt);return;}if(Math.abs(u.x-mine)<65){u.state='mine';u.face=dir;u.walk+=dt*5;u.carry=Math.min(capacity,u.carry+dt*(11+(u.team===0?this.upgrades.miner*2:0))*(manual?1.65:1));}else if(!manual)this.move(u,mine+(u.uid%4-1.5)*22,u.y,dt);}
 updateUnit(u,dt){if(u.hp<=0)return;u.age+=dt;if(u.id==='mage')u.spell-=dt;u.cooldown=Math.max(0,u.cooldown-dt);u.stun=Math.max(0,u.stun-dt);u.flash=Math.max(0,u.flash-dt);u.swing=Math.max(0,u.swing-dt);if(u.id==='minion'&&u.age>35){u.hp=0;return;}u.guard=false;if(u.stun>0){u.state='stun';return;}const direct=u.uid===this.selected,cmd=this.commands[u.team],dir=u.team?-1:1,home=BASE[u.team];if(direct){u.guard=this.manual.block&&u.id!=='miner';const dx=this.manual.x,dy=this.manual.y;if((dx||dy)&&!u.guard){this.move(u,u.x+dx*100,u.y+dy*100,dt);}else u.state=u.guard?'block':'idle';if(u.id==='miner'){this.mine(u,dt,true);if(this.manual.attack){const t=this.target(u);if(t.distance<u.range+15)this.strike(u,t.unit);}}else if(this.manual.attack){const t=this.target(u);this.strike(u,t.unit);}return;}
 if(cmd==='garrison'){if(Math.abs(u.x-home)<65){u.state='garrison';u.hp=Math.min(u.max,u.hp+dt*(u.team===0?8+this.upgrades.statue*3:8));u.carry&&u.id==='miner'&&(this.gold[u.team]+=u.carry,u.carry=0);}else this.move(u,home,u.y,dt);return;}
 if(u.id==='miner'){const t=this.target(u);if(t.unit&&!t.unit.base&&t.distance<120){this.move(u,home+dir*15,u.y,dt);}else this.mine(u,dt);return;}
 const t=this.target(u),engage=cmd==='attack'||t.distance<u.range+220&&t.unit&&Math.abs(t.unit.x-home)<680;
 if(engage&&t.unit){u.face=t.unit.x<u.x?-1:1;if(t.distance<=u.range+8){u.state='idle';this.strike(u,t.unit);}else this.move(u,t.unit.x-dir*(u.range*.8),t.unit.y+(u.uid%3-1)*10,dt);}else{const fighters=this.units.filter(v=>v.team===u.team&&v.id!=='miner'&&v.hp>0).sort((a,b)=>def(b.id).range-def(a.id).range),slot=fighters.indexOf(u),x=home+dir*(cmd==='attack'?1200:300+Math.max(0,330-u.range)*.28);this.move(u,x+dir*(slot%3)*25,(Math.floor(slot/3)%5-2)*22,dt);}
 if(u.id==='mage'){if(u.spell<=0&&engage&&this.units.filter(v=>v.team===u.team&&v.id==='minion'&&v.hp>0).length<6){u.spell=16;for(let i=0;i<2;i++)this.spawn(u.team,'minion',{x:u.x+dir*35,y:u.y+i*20,power:1});this.effects.push({type:'summon',x:u.x,y:u.y,t:.65,max:.65,team:u.team});}}
 }
 ai(dt){if(this.mode==='survival'||this.mode==='campaign'&&this.mission.mode==='hold')return;this.aiClock-=dt;const f=this.units.filter(u=>u.team===1&&u.id!=='miner'&&u.hp>0),threat=this.units.filter(u=>u.team===0&&u.hp>0&&u.x>2050).length;if(this.base[1].hp<this.base[1].max*.25&&f.length<3&&threat>0)this.commands[1]='garrison';else this.commands[1]=f.length>=(this.mission.id<3?3:5)||threat>0||this.time>100?'attack':'defend';if(this.aiClock<=0){this.aiClock=this.mode==='campaign'?this.mission.pace/this.power:6/this.power;const miners=this.units.filter(u=>u.team===1&&u.id==='miner'&&u.hp>0).length;if(miners<3&&this.gold[1]>=100)this.train('miner',1);else{const pool=this.mode==='campaign'?this.mission.enemy:['sword','sword','archer','spear','mage','giant'],available=pool.filter(id=>UNITS.some(u=>u.id===id)&&def(id).cost<=this.gold[1]);if(available.length)this.train(available[Math.floor(this.random()*available.length)],1);}}if(!this.reserve&&this.base[1].hp<this.base[1].max*.42){this.reserve=true;this.commands[1]='attack';const boss=this.mode==='campaign'&&this.mission.boss;this.spawn(1,boss?'giant':'spear',{boss});this.spawn(1,'sword');this.events.push({type:'reserve',text:boss?'The last guardian has awakened.':'Enemy reinforcements!'});}}
 advanceWaves(){this.wave++;const special=this.wave%5===0,mode=this.mode;this.events.push({type:'wave',text:(mode==='survival'?'Wave '+this.wave: 'Raid '+this.wave)+(special?' · Heavy assault':'' )});const n=mode==='survival'?Math.min(18,3+Math.floor(this.wave*1.2)):Math.min(12,2+this.wave);for(let i=0;i<n;i++){const id=this.mission.id===3&&mode==='campaign'?'sword':special&&i===0?'brute':i%6===5&&this.wave>3?'brute':'dead';this.spawn(1,id,{x:WORLD-110-i*15,y:(this.random()-.5)*110,power:this.power*(1+Math.min(2,this.wave*.06))});}this.commands[1]='attack';this.nextWave=this.time+(mode==='survival'?28:this.mission.pace);this.gold[0]+=special?150:50;}
 finish(winner,reason){if(this.done)return;this.done=true;this.winner=winner;this.reason=winner===0?reason:'Your statue has fallen.';this.events.push({type:'finish',winner});}
 tick(dt){if(this.done)return;dt=clamp(dt,0,.05);this.time+=dt;for(let team=0;team<2;team++){this.gold[team]+=dt*(team===0?1.5+this.upgrades.income*1.2:this.mode==='campaign'?this.mission.id===1?1.5:2.5*this.power:2.5*this.power);const q=this.queue[team][0];if(q){q.left-=dt;if(q.left<=0){this.spawn(team,q.id);this.queue[team].shift();this.events.push({type:'spawn',team,id:q.id});}}this.base[team].flash=Math.max(0,this.base[team].flash-dt);this.tower[team]-=dt;if(this.commands[team]==='garrison'&&this.tower[team]<=0){const t=this.units.filter(u=>u.team!==team&&u.hp>0&&Math.abs(u.x-BASE[team])<460).sort((a,b)=>Math.abs(a.x-BASE[team])-Math.abs(b.x-BASE[team]))[0];if(t){this.tower[team]=1.3;this.projectiles.push({team,source:-1-team,id:'archer',x:BASE[team],y:-130,tx:t.x,ty:t.y-30,target:t.uid,t:.5,max:.5,damage:24});}}}
 this.ai(dt);if(this.mode==='survival'||this.mode==='campaign'&&this.mission.mode==='hold'){if(this.time>=this.nextWave)this.advanceWaves();if(this.mode==='campaign'&&this.time>=this.mission.duration){this.finish(0,'Dawn breaks. Your statue still stands.');return;}}
 const snapshot=[...this.units];for(const u of snapshot)this.updateUnit(u,dt);const alive=this.units.filter(u=>u.hp>0);for(let i=0;i<alive.length;i++){const a=alive[i];if(a.state==='garrison')continue;for(let j=i+1;j<alive.length;j++){const b=alive[j];if(b.state==='garrison')continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),r=(a.id==='giant'||a.id==='brute'?23:10)+(b.id==='giant'||b.id==='brute'?23:10);if(d<r&&d>.01){const p=(r-d)*.35;a.x-=dx/d*p;b.x+=dx/d*p;a.y-=dy/d*p*.65;b.y+=dy/d*p*.65;}}a.x=clamp(a.x,70,WORLD-70);a.y=clamp(a.y,-72,72);}
 for(const p of this.projectiles){p.t-=dt;if(p.t<=0){const t=this.units.find(u=>u.uid===p.target)||this.base.find(u=>u.uid===p.target),source=this.units.find(u=>u.uid===p.source)||{x:BASE[p.team],team:p.team,id:p.id,uid:p.source};if(t&&Math.hypot(t.x-p.tx,t.y-p.ty-30)<75)this.hurt(t,p.damage,source);}}
 this.projectiles=this.projectiles.filter(p=>p.t>0);for(const e of this.effects)e.t-=dt;this.effects=this.effects.filter(e=>e.t>0);for(const c of this.corpses)c.t-=dt;this.corpses=this.corpses.filter(c=>c.t>0);this.units=this.units.filter(u=>u.hp>0);
 
 }
 step(dt){let left=clamp(dt,0,.25);while(left>1e-8&&!this.done){const t=Math.min(left,1/30);this.tick(t);left-=t;}}
}
const API={WORLD,BASE,MINE,CAP,UNITS,MAPS,MISSIONS,UPGRADE_IDS,UPGRADE_INFO,clamp,fin,rng,def,clean,Profile,Battle};if(typeof module!=='undefined'&&module.exports)module.exports=API;globalThis.StickCore=API;
})();
