/* Original canvas artwork, responsive controls and campaign interface. */
(()=>{'use strict';const $=id=>document.getElementById(id),C=globalThis.StickCore;if(!C){$('error').hidden=false;$('error-text').textContent='A game file is missing. Reload or reinstall Stick War.';return;}
const {WORLD,BASE,MINE,CAP,UNITS,MAPS,MISSIONS,UPGRADE_IDS,UPGRADE_INFO,clamp,def,Profile,Battle}=C,canvas=$('field'),ctx=canvas.getContext('2d');if(!ctx){$('error').hidden=false;$('error-text').textContent='This browser cannot create a battlefield canvas.';return;}
let raw={};try{raw=window.__POCKETVM_SAVE||JSON.parse(localStorage.getItem('pocketvm.game.stickwar')||'{}');}catch{}const profile=new Profile(raw);
let page='menu',battle=null,pending=null,paused=false,last=0,acc=0,now=0,uiClock=0,camera=0,cameraTarget=0,autoCamera=true,scale=1,ground=0,width=innerWidth,height=innerHeight,speed=1,shake=0,toastLeft=0,pan=null,joy=null,soundCtx=null,audioReady=false,audioTime=0,ambientTime=0;const keys=new Set(),sparks=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),time=s=>Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');
function unitIcon(id){const extra=id==='statue'?'<path d="M29 87H71M34 77H66M45 73V52M55 73V52M50 52V31M50 38L31 51M50 38L69 51M70 58V15"/>':id==='income'?'<ellipse cx="50" cy="58" rx="24" ry="11"/><path d="M26 58V72Q50 91 74 72V58M26 65Q50 82 74 65"/><text x="50" y="62" text-anchor="middle" fill="currentColor" stroke="none" font-size="16">◆</text>':'<circle cx="50" cy="24" r="8"/><path d="M50 34V58M50 58L36 82M50 58L65 82M50 41L31 56M50 41L67 53"/>'+(id==='miner'?'<path d="M67 67L75 24M63 28Q77 15 90 27M30 78L24 63L34 56L42 63Z"/>':id==='sword'?'<path d="M68 60L81 19M75 43L87 47"/>':id==='archer'?'<path d="M73 25Q96 52 72 78M72 25L72 78M55 53H96"/>':id==='spear'?'<path d="M78 83V9M74 18L78 9L82 18M26 39Q12 56 26 71Q41 55 26 39Z"/>':id==='mage'?'<path d="M35 20L50 1L65 20ZM77 83V25M72 25L77 17L82 25"/>':id==='giant'?'<path d="M30 38L20 73M70 38L86 65M84 60L94 72" stroke-width="8"/>':'');return'<svg viewBox="0 0 100 100" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">'+extra+'</svg>';}
function save(){const data=profile.export();try{localStorage.setItem('pocketvm.game.stickwar',JSON.stringify(data));}catch{}parent.postMessage({type:'pocketvm-stick-save',data},'*');}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;toastLeft=3.5;}
function audio(kind){if(!audioReady||!profile.save.prefs.sound||paused&&!['win','loss'].includes(kind)||document.hidden)return;try{soundCtx=soundCtx||new(window.AudioContext||window.webkitAudioContext)();soundCtx.resume();const t=soundCtx.currentTime;if(kind==='hit'&&t-audioTime<.09)return;audioTime=t;const tones=kind==='win'?[261.63,329.63,392,523.25]:kind==='loss'?[196,174.6,146.8]:kind==='gold'?[880,1174.66]:kind==='ambient'?[65.4,98,130.8]:kind==='train'?[293.6,392]:[90,60];for(let i=0;i<tones.length;i++){const o=soundCtx.createOscillator(),g=soundCtx.createGain(),start=t+i*(kind==='ambient'?.01:.1),duration=kind==='ambient'?2.8:kind==='hit'?.08:.25;o.type=kind==='ambient'?'sine':kind==='hit'?'triangle':'sine';o.frequency.setValueAtTime(tones[i],start);if(kind==='hit')o.frequency.exponentialRampToValueAtTime(35,start+.08);g.gain.setValueAtTime(.001,start);g.gain.linearRampToValueAtTime(kind==='ambient'?.018:.035,start+.015);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(soundCtx.destination);o.start(start);o.stop(start+duration+.05);}}catch{}}
function activate(){audioReady=true;audio('train');}
function show(next){page=next;for(const id of ['menu','campaign-screen','forge-screen','settings-screen'])$(id).hidden=id!==(next==='menu'?'menu':next+'-screen');$('hud').hidden=next!=='battle';if(next!=='battle'){battle=null;$('direct-controls').hidden=true;$('control-strip').hidden=true;resetInput();}if(next==='menu'){const s=profile.save;$('progress').textContent=s.stars.filter(Boolean).length+' / 12';$('best-wave').textContent=s.bestWave;$('point-badge').textContent=s.points?'· '+s.points+' points':'';}if(next==='campaign')renderCampaign();if(next==='forge')renderForge();if(next==='settings')for(const id of ['difficulty','map','sound','motion']){const e=$(id);if(e.type==='checkbox')e.checked=profile.save.prefs[id];else e.value=profile.save.prefs[id];}resize();}
function renderCampaign(){const unlocked=profile.unlocked();$('missions').innerHTML=MISSIONS.map(m=>{const n=profile.save.stars[m.id-1],locked=m.id>unlocked;return'<button class="mission '+(locked?'locked':m.id===unlocked?'next':'')+'" data-mission="'+m.id+'" '+(locked?'disabled':'')+'><span class="number">'+String(m.id).padStart(2,'0')+(locked?' · LOCKED':'')+'</span><b>'+m.name+'</b><span class="stars">'+(n?'★'.repeat(n)+'☆'.repeat(3-n):'— — —')+'</span><span class="tag">'+(m.mode==='hold'?'Hold until dawn':m.boss?'Final assault':MAPS.find(x=>x.id===m.map).name)+'</span></button>';}).join('');}
function renderForge(){$('forge-points').textContent=profile.save.points+' points available';$('upgrades').innerHTML=UPGRADE_IDS.map(id=>{const n=profile.save.upgrades[id];return'<article class="upgrade"><div class="upgrade-art">'+unitIcon(id)+'</div><h3>'+UPGRADE_INFO[id][0]+'</h3><p>'+UPGRADE_INFO[id][1]+'</p><div class="levels">'+'●'.repeat(n)+'○'.repeat(3-n)+'</div><button data-upgrade="'+id+'" '+(n>=3||profile.save.points<1?'disabled':'')+'>'+(n>=3?'Fully upgraded':'Upgrade · 1 point')+'</button></article>';}).join('');}
function brief(mode,mission=1){activate();pending={mode,mission};const m=MISSIONS[mission-1];$('brief-label').textContent=mode==='campaign'?'MISSION '+String(mission).padStart(2,'0'):mode==='survival'?'ENDLESS DEADS':'CUSTOM BATTLE';$('brief-title').textContent=mode==='campaign'?m.name:mode==='survival'?'Hold the line.':'Make your own war.';$('brief-text').textContent=mode==='campaign'?m.brief:mode==='survival'?'The dead return in stronger waves. Protect your statue, grow your army, and set a new survival record.': 'A full roster, a fresh battlefield, and an enemy army with the same economy and population limit.';$('brief-tip').textContent=mode==='campaign'?m.tip:mode==='survival'?'A wave arrives every 28 seconds. Every fifth wave brings a heavy assault. All six units are available.':'Difficulty: '+profile.save.prefs.difficulty+' · Terrain: '+(profile.save.prefs.map==='random'?'Random':MAPS.find(m=>m.id===profile.save.prefs.map).name)+'. Change both in Settings. All six units are available.';$('brief').hidden=false;}
function begin(){if(!pending)return;$('brief').hidden=true;$('result').hidden=true;page='battle';for(const id of ['menu','campaign-screen','forge-screen','settings-screen'])$(id).hidden=true;$('hud').hidden=false;battle=new Battle({...pending,difficulty:profile.save.prefs.difficulty,map:profile.save.prefs.map,upgrades:profile.save.upgrades,seed:(Date.now()>>>0)||1});paused=false;speed=1;$('speed').textContent='1×';camera=cameraTarget=0;autoCamera=true;resetInput();resize();renderTraining();updateHUD();toast(battle.objective());last=0;acc=0;activate();}
function renderTraining(){if(!battle)return;$('training').innerHTML=UNITS.map((d,i)=>'<button class="unit-button" data-train="'+d.id+'" aria-label="Train '+d.name+' for '+d.cost+' gold" title="'+esc(d.description)+' · Key '+(i+1)+'" '+(!battle.allowed(d.id)?'disabled':'')+'>'+unitIcon(d.id)+'<span><b>'+d.name+'</b><small>'+(battle.allowed(d.id)?'◆ '+d.cost:'Mission '+(d.unlock+1))+'</small></span><span class="count" data-count="'+d.id+'" hidden></span></button>').join('');}
function train(id){if(!battle||paused)return;activate();const error=battle.train(id);if(error)toast(error);updateHUD();}
function special(){if(!battle||paused)return;const error=battle.special();if(error)toast(error);else audio('train');}
function command(cmd){if(!battle||paused)return;battle.command(cmd);autoCamera=true;audio('train');updateHUD();}
function control(u){if(!battle)return;battle.control(u?.uid);resetInput();$('direct-controls').hidden=!u;$('control-strip').hidden=!u;$('battle-note').hidden=!!u;if(u){$('controlled-name').textContent=def(u.id).name+(u.id==='miner'?' · faster mining':' · direct control');$('attack-unit').textContent=u.id==='miner'?'Strike':'Attack';$('block-unit').disabled=u.id==='miner';$('ability-unit').hidden=!['spear','mage'].includes(u.id);$('ability-unit').textContent=u.id==='mage'?'Summon':'Throw';autoCamera=true;toast(u.id==='miner'?'Move to the gold. Your miner works faster while you control it.':'Move · Attack · Block. Release returns this unit to your army.');}updateHUD();}
function resetInput(){keys.clear();joy=null;pan=null;if(battle)battle.manual={x:0,y:0,attack:false,block:false};$('knob').style.transform='';}
function pause(){if(!battle||battle.done||paused)return;paused=true;resetInput();$('pause-objective').textContent=battle.objective();$('pause-panel').hidden=false;}
function resume(){$('pause-panel').hidden=true;paused=false;last=0;acc=0;activate();}
function finish(){if(!battle)return;paused=true;resetInput();const won=battle.winner===0,reward=profile.complete(battle);save();$('result-emblem').textContent=won?'⚑':'✕';$('result-label').textContent=battle.mode==='survival'?'ENDLESS DEADS':won?'TERRITORY CAPTURED':'THE STANDARD HAS FALLEN';$('result-title').textContent=battle.mode==='survival'?'Wave '+battle.wave+'.':won?'Victory.':'Defeat.';$('result-text').textContent=battle.mode==='survival'?'The dead won this night. Your best record is wave '+profile.save.bestWave+'.':won?battle.reason+(reward?' Two armoury points earned.':''): 'Regroup, train more miners, and try a different formation.';$('result-time').textContent=time(battle.time);$('result-kills').textContent=battle.kills[0];$('result-reward').textContent=battle.mode==='survival'?profile.save.bestWave:reward?'+'+reward:won?'★'.repeat(battle.mode==='campaign'?profile.save.stars[battle.mission.id-1]:1):'—';$('reward-label').textContent=battle.mode==='survival'?'BEST WAVE':reward?'ARMOURY POINTS':'BATTLE RATING';$('result-next').textContent=won&&battle.mode==='campaign'&&battle.mission.id<12?'Next territory →':won&&battle.mode==='campaign'?'Campaign complete →':'Try again →';$('result').hidden=false;$('direct-controls').hidden=true;audioReady&&audio(won?'win':'loss');}
function updateHUD(){if(!battle)return;const b=battle;$('mission-name').textContent=b.mode==='campaign'?b.mission.name.toUpperCase():b.mode==='survival'?'ENDLESS DEADS · WAVE '+b.wave:'SKIRMISH · '+MAPS.find(m=>m.id===b.map).name.toUpperCase();$('gold').textContent=Math.floor(b.gold[0]);$('population').textContent=(b.population(0)+b.reserved(0))+' / '+CAP;$('clock').textContent=b.mode==='campaign'&&b.mission.mode==='hold'?time(Math.max(0,b.mission.duration-b.time)):time(b.time);$('your-hp').style.width=b.base[0].hp/b.base[0].max*100+'%';$('enemy-hp').style.width=b.base[1].hp/b.base[1].max*100+'%';$('enemy-label').textContent=b.mode==='survival'||b.mission.mode==='hold'&&b.mode==='campaign'?'HOLD UNTIL DAWN':'ENEMY STATUE';for(const e of document.querySelectorAll('[data-command]')){const on=e.dataset.command===b.commands[0];e.classList.toggle('active',on);e.setAttribute('aria-pressed',String(on));}for(const e of document.querySelectorAll('[data-train]')){const d=def(e.dataset.train);e.disabled=!b.allowed(d.id)||b.gold[0]<d.cost||b.population(0)+b.reserved(0)+d.pop>CAP||b.queue[0].length>=6;const count=b.queue[0].filter(q=>q.id===d.id).length,s=e.querySelector('.count');s.hidden=!count;s.textContent=count;}
const q=b.queue[0][0];$('queue-name').textContent=q?def(q.id).name+' · '+Math.ceil(q.left)+'s'+(b.queue[0].length>1?' · '+(b.queue[0].length-1)+' waiting':''):'Training queue empty';$('queue-progress').hidden=!q;$('cancel').hidden=!q;if(q)$('queue-progress').querySelector('i').style.width=(1-q.left/q.total)*100+'%';const u=b.units.find(u=>u.uid===b.selected);if(!u){$('direct-controls').hidden=true;$('control-strip').hidden=true;$('battle-note').hidden=false;}const span=width/scale,left=clamp(camera/WORLD*100,0,100),vw=clamp(span/WORLD*100,0,100);$('minimap-track').innerHTML='<span class="mini-camera" style="left:'+left+'%;width:'+Math.min(100-left,vw)+'%"></span>'+b.base.map(v=>'<i class="mini-dot base '+(v.team?'enemy':'')+'" style="left:'+v.x/WORLD*100+'%"></i>').join('')+b.units.filter(u=>u.state!=='garrison').map(u=>'<i class="mini-dot '+(u.team?'enemy':'')+'" style="left:'+u.x/WORLD*100+'%"></i>').join('');}
function resize(){width=innerWidth;height=innerHeight;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);const top=width<=600?182:155,bottom=width<=600?185:height<500?87:112,available=Math.max(90,height-top-bottom);scale=page==='battle'?clamp(available/360,.5,1.3):clamp(height/710,.55,1.1);ground=page==='battle'?top+available*.76:height*.79;camera=clamp(camera,0,Math.max(0,WORLD-width/scale));cameraTarget=clamp(cameraTarget,0,Math.max(0,WORLD-width/scale));canvas.dataset.viewport=JSON.stringify({width,height,scale,ground});}
function line(points,color='#171d20',lw=4){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function polygon(points,color){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=color;ctx.fill();}
function hills(map,offset,factor,base,amp){ctx.beginPath();ctx.moveTo(0,height);for(let x=-30;x<=width+30;x+=25){const wx=x+offset*factor,y=base+Math.sin(wx*.0031+factor*8)*amp+Math.sin(wx*.0074)*amp*.28;ctx.lineTo(x,y);}ctx.lineTo(width,height);ctx.closePath();ctx.fillStyle=map;ctx.fill();}
function backdrop(){const map=MAPS.find(m=>m.id===(battle?.map||'meadow')),sky=ctx.createLinearGradient(0,0,0,height);sky.addColorStop(0,map.sky[0]);sky.addColorStop(1,map.sky[1]);ctx.fillStyle=sky;ctx.fillRect(0,0,width,height);const sunx=width*.77-camera*.05,suny=Math.max(100,ground-height*.47);circle(sunx,suny,height*.061,battle?.map==='night'?'#eee9cba8':'#fff1c58c');if(battle?.map==='night'){circle(sunx+height*.022,suny-height*.015,height*.06,map.sky[0]);for(let i=0;i<35;i++)circle((i*101.6+19)%width,18+(i*67.3)%(Math.max(20,ground*.5)),i%3===0?1.1:.6,'#e4dacb68');}
 for(let l=0;l<2;l++){const y=ground-height*(.35-l*.1),amp=height*(.13-l*.035);ctx.beginPath();ctx.moveTo(-50,height);for(let x=-120;x<=width+200;x+=120){const wx=x+camera*(.12+l*.07),h=Math.sin(wx*.005+l*3)*amp+Math.sin(wx*.013)*amp*.35;ctx.lineTo(x,y+h);}ctx.lineTo(width+120,height);ctx.fillStyle=l===0?map.mountain:map.hill;ctx.globalAlpha=l===0?.55:.65;ctx.fill();ctx.globalAlpha=1;}hills(map.hill,camera,.25,ground-height*.08,height*.065);hills(map.grass,camera,.5,ground+20,height*.015);ctx.fillStyle=map.ground;ctx.fillRect(0,ground+55*scale,width,height);ctx.fillStyle='#101c1922';ctx.fillRect(0,ground+60*scale,width,7*scale);
 if(profile.save.prefs.motion)for(let i=0;i<5;i++){const x=((i*width/4+now*(i%2?3:5)-camera*.07)%(width+250))-125,y=ground-height*(.52+i%2*.08);ctx.fillStyle='#fff9e313';ctx.beginPath();ctx.ellipse(x,y,80+15*i,9+i*2,0,0,Math.PI*2);ctx.fill();}
 for(let i=0;i<Math.ceil(width/18)+1;i++){const x=i*21-(camera*scale%21),y=ground+15+(Math.sin((i+Math.floor(camera/21))*.9)*.5+.5)*35;line([[x,y],[x+2,y-5]],'#1b382228',1);if(i%11===0){circle(x,y-5,1.5,'#f5d79535');}}
 if(map.id==='frost'&&profile.save.prefs.motion){ctx.fillStyle='#f7fffba0';for(let i=0;i<45;i++){const x=(i*43.3+now*12)%(width+60),y=(i*67.9+now*18)%(height);ctx.fillRect(x,y,1.5,1.5);}}
}
function goldMine(x){ctx.save();ctx.translate(x,0);ctx.fillStyle='#14272125';ctx.beginPath();ctx.ellipse(0,18,62,15,0,0,Math.PI*2);ctx.fill();for(let i=0;i<6;i++){const ox=(i%3-1)*26,oy=-Math.floor(i/3)*17;polygon([[ox-21,oy+9],[ox-14,oy-12],[ox+2,oy-20],[ox+21,oy-6],[ox+15,oy+10]],['#c29c46','#d9b759','#a38944'][i%3]);line([[ox-8,oy-5],[ox+4,oy-12]],'#f5dd854f',3);}ctx.restore();}
function banner(x,team){ctx.save();ctx.translate(x,-10);line([[0,0],[0,-165]],'#3c4031',5);const flutter=Math.sin(now*2+x)*5,color=team?'#813d36':'#b39147';polygon([[0,-153],[52,-146+flutter],[50,-93+flutter],[24,-105+flutter],[0,-106]],color);line([[24,-139],[24,-111]],'#ecd9a86c',3);circle(0,-171,5,'#c3ad75');ctx.restore();}
function statue(b){ctx.save();ctx.translate(b.x,b.y);const enemy=b.team,stone=enemy?'#8a8275':'#c0b08b',dark=enemy?'#615c57':'#928563';ctx.fillStyle='#15241f22';ctx.beginPath();ctx.ellipse(3,25,95,19,0,0,Math.PI*2);ctx.fill();polygon([[-66,17],[69,17],[69,0],[-66,0]],dark);polygon([[-55,0],[56,0],[48,-39],[-47,-39]],stone);polygon([[-47,-39],[48,-39],[42,-54],[-42,-54]],dark);ctx.save();ctx.translate(0,-55);ctx.scale(1.45,1.45);line([[-16,0],[-6,-27],[0,-50],[7,-26],[18,0]],stone,12);line([[0,-52],[0,-85]],stone,14);line([[0,-78],[-21,-60],[-36,-89]],stone,10);line([[0,-78],[19,-63],[35,-79]],stone,10);circle(0,-101,12,stone);polygon([[-11,-111],[-9,-124],[-3,-118],[3,-125],[7,-118],[12,-122],[11,-110]],dark);line([[39,-23],[39,-125]],dark,5);polygon([[33,-107],[39,-138],[44,-109]],stone);line([[29,-99],[48,-99]],stone,6);ctx.restore();if(b.flash>0){ctx.globalAlpha=.35;ctx.fillStyle='#fff8cc';ctx.fillRect(-48,-218,96,219);ctx.globalAlpha=1;}const damaged=1-b.hp/b.max;if(damaged>.25)line([[-12,-33],[-5,-22],[-15,-15],[-6,-1]],'#393b3555',2);if(damaged>.6)line([[18,-206],[11,-170],[20,-155],[11,-146]],'#37382d88',3);banner(enemy?-85:85,enemy);ctx.restore();}
function soldier(u,{corpse=false}={}){if(u.state==='garrison')return;const sx=(u.x-camera)*scale;if(sx<-150||sx>width+150)return;ctx.save();ctx.translate(u.x,u.y);const giant=u.id==='giant'||u.id==='brute',size=giant?2.05:1,ink=u.flash>0?'#efe1ac':u.id==='dead'||u.id==='brute'?'#293732':'#171d20',accent=u.team?'#ad6554':'#d1b36d',walk=u.state==='walk'?Math.sin(u.walk)*12:0,attack=u.swing>0?Math.sin(u.swing/.38*Math.PI):0;ctx.fillStyle='#15221d30';ctx.beginPath();ctx.ellipse(0,5,giant?29:16,giant?9:5,0,0,Math.PI*2);ctx.fill();if(u.uid===battle?.selected){ctx.strokeStyle='#ffe2a4';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,4,27*size,9*size,0,0,Math.PI*2);ctx.stroke();}ctx.scale(size*u.face,size);if(corpse){ctx.rotate(-Math.PI*.45);ctx.translate(5,10);}const bob=u.state==='walk'?Math.abs(Math.sin(u.walk))*2:0;ctx.translate(0,-bob);const torso=u.state==='mine'?12:0;line([[-10-walk*.5,0],[-5+walk*.1,-14],[torso,-28],[5-walk*.3,-13],[10+walk*.5,0]],ink,4);line([[torso,-28],[torso-2,-47]],ink,4.5);circle(torso-2,-59,8.5,ink);
 if(u.id==='miner'){polygon([[torso-13,-61],[torso+9,-61],[torso+5,-72],[torso-8,-72]],accent);circle(torso+7,-63,2,'#eada99');const mining=u.state==='mine',angle=mining?Math.sin(now*8+u.uid)*.6:-.25;ctx.save();ctx.translate(torso+15,-37);ctx.rotate(angle);line([[-15,-6],[-6,4],[8,-8]],ink,3.5);line([[0,12],[17,-34]],'#725b3d',3);line([[8,-33],[22,-36],[30,-24]],'#aaaa8d',4);ctx.restore();line([[torso,-43],[torso-13,-32],[torso-9,-19]],ink,4);if(u.carry>0){polygon([[-12,-31],[-23,-26],[-22,-11],[-8,-12]],'#876c3d');circle(-16,-26,4,'#d8b861');}}
 else if(u.id==='archer'){line([[-2,-44],[10,-40],[24,-42]],ink,3.5);line([[-2,-43],[8,-31],[24,-42]],ink,3.5);ctx.strokeStyle='#ad8653';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(27,-65);ctx.quadraticCurveTo(44+attack*6,-42,27,-20);ctx.stroke();line([[27,-65],[20-attack*8,-42],[27,-20]],'#e0cba6',1);line([[15,-42],[47,-42]],'#c2b48d',1.5);polygon([[46,-45],[53,-42],[46,-39]],'#929d94');line([[-10,-45],[-15,-16]],'#705e40',5);polygon([[-12,-62],[8,-62],[4,-72],[-7,-71]],accent);}
 else if(u.id==='spear'){line([[-2,-45],[12,-31],[22,-37]],ink,4);line([[-1,-43],[-12,-31],[-19,-42]],ink,4);const guard=u.guard,angle=attack?-.6:guard?-.2:.12;ctx.save();ctx.translate(21,-35);ctx.rotate(angle);if(u.spearThrown){line([[0,3],[0,-27]],'#d3cfaa',3.5);line([[-5,-2],[5,-2]],accent,3);}else{line([[0,28],[0,-65]],'#9a8054',3);polygon([[-4,-58],[0,-74],[4,-58]],'#bac1aa');}ctx.restore();ctx.fillStyle=accent;ctx.beginPath();ctx.ellipse(guard?16:-16,-32,10,18,guard?.1:-.25,0,Math.PI*2);ctx.fill();line([[-17,-46],[-15,-19]],'#ffe0a34d',2);polygon([[-13,-57],[-11,-73],[2,-76],[9,-67],[7,-58]],accent);line([[-2,-77],[-3,-86],[8,-83]],u.team?'#7e3437':'#9a633e',5);}
 else if(u.id==='mage'){polygon([[-17,-50],[0,-82],[14,-50]],accent);polygon([[-10,-38],[-17,-8],[16,-8],[9,-38]],'#404446');line([[-2,-43],[10,-35],[23,-45]],ink,4);line([[-2,-43],[-14,-30],[-22,-39]],ink,4);line([[24,2],[24,-61]],'#806949',3);circle(24,-64,5,u.team?'#dda17d':'#dbcca0');if(attack){circle(27,-64,13,'#e3cf9a44');}}
 else if(giant){const a=attack*24;line([[-2,-45],[-15,-31],[-26,-11]],ink,6);line([[-2,-45],[14,-33],[23+a,-47+a]],ink,6);line([[21+a,-41+a],[29+a,-11+a]],'#68503a',7);line([[25+a,-22+a],[34+a,-17+a]],'#9a8965',10);polygon([[-8,-30],[10,-30],[13,-23],[-10,-23]],accent);if(u.boss){polygon([[-12,-65],[-11,-77],[-5,-73],[0,-81],[6,-72],[12,-76],[10,-65]],'#b38149');}}
 else{const block=u.guard,a=attack*36;line([[-2,-43],[-14,-29],[-17,-14]],ink,4);line([[-2,-43],[12,-32],[22+a*.35,-46+a*.4]],ink,4);ctx.save();ctx.translate(22+a*.35,-46+a*.4);ctx.rotate(attack?attack*1.5:block?-1.6:-.2);line([[0,4],[0,-33]],'#d3cfaa',3.5);line([[-6,-2],[6,-2]],accent,3);ctx.restore();line([[-10,-63],[5,-62]],accent,3);if(u.id==='dead'){circle(3,-61,1.8,'#bdba86');line([[9,-41],[17,-28],[21,-15]],ink,3);}}
 ctx.restore();if(!corpse&&(u.hp<u.max||u.uid===battle?.selected||u.boss)){ctx.fillStyle='#16271c55';ctx.fillRect(u.x-17*size,u.y-83*size,34*size,3);ctx.fillStyle=u.team?'#d7816e':'#e2c182';ctx.fillRect(u.x-17*size,u.y-83*size,34*size*u.hp/u.max,3);}if(u.stun>0){ctx.strokeStyle='#efd88f';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(u.x,u.y-80*size,11,3,now*3,0,Math.PI*2);ctx.stroke();}}
const demo=[{id:'giant',x:1750,y:0,team:0,walk:0},{id:'spear',x:1470,y:9,team:0,walk:1},{id:'spear',x:1590,y:-20,team:0,walk:3},{id:'archer',x:1330,y:15,team:0,walk:2},{id:'sword',x:1620,y:38,team:0,walk:6},{id:'miner',x:1260,y:-18,team:0,walk:1}].map((u,i)=>({...u,uid:-10-i,hp:100,max:100,face:1,state:'idle',swing:0,flash:0,stun:0,carry:35}));
function render(){ctx.save();ctx.setTransform(Math.min(devicePixelRatio||1,2),0,0,Math.min(devicePixelRatio||1,2),0,0);backdrop();const b=battle;if(!b){camera=clamp(1500-width/scale*.5,0,WORLD-width/scale);}ctx.save();ctx.translate(-camera*scale+(profile.save.prefs.motion&&shake>0?Math.sin(now*85)*shake:0),ground);ctx.scale(scale,scale);if(b){for(const base of b.base)if(!(base.team&&(b.mode==='survival'||b.mode==='campaign'&&b.mission.mode==='hold')))statue(base);for(const x of MINE)goldMine(x);for(const c of b.corpses){ctx.globalAlpha=clamp(c.t/2.8,0,.7);soldier(c,{corpse:true});}ctx.globalAlpha=1;for(const u of [...b.units].sort((a,z)=>a.y-z.y))soldier(u);for(const p of b.projectiles){const progress=1-p.t/p.max,x=p.x+(p.tx-p.x)*progress,y=p.y+(p.ty-p.y)*progress-Math.sin(progress*Math.PI)*60,angle=Math.atan2(p.ty-p.y,p.tx-p.x);ctx.save();ctx.translate(x,y);ctx.rotate(angle);line([[-14,0],[7,0]],'#403e31',1.7);polygon([[7,-3],[13,0],[7,3]],'#d5caa2');ctx.restore();}for(const e of b.effects){const progress=1-e.t/e.max;ctx.globalAlpha=e.t/e.max;if(e.type==='hit'){line([[e.x-9,e.y-7],[e.x+9,e.y+7]],'#e9d2a0',2);line([[e.x+9,e.y-7],[e.x-9,e.y+7]],'#e9d2a0',2);}else{ctx.strokeStyle=e.team?'#e7987555':'#f1d28c88';ctx.lineWidth=e.type==='stomp'?5:3;ctx.beginPath();ctx.ellipse(e.x,e.y,(15+progress*105),10+progress*23,0,0,Math.PI*2);ctx.stroke();if(e.type==='spell'){for(let i=0;i<7;i++)line([[e.x+(i-3)*18,e.y],[e.x+(i-3)*22,e.y-35-progress*60]],'#f0d2a4',2);}}ctx.globalAlpha=1;}}
else{goldMine(1210);banner(1870,0);for(const u of demo){u.walk=now*4+u.uid;u.state=u.id==='miner'?'mine':'idle';soldier(u);}}ctx.restore();if(b&&b.commands[0]==='garrison'){ctx.fillStyle='#142725cc';ctx.font='11px system-ui';ctx.textAlign='left';const x=(BASE[0]-camera)*scale;ctx.fillText('Garrison · '+b.units.filter(u=>u.team===0&&u.state==='garrison').length,x-35,ground+38*scale);}ctx.restore();}
function inputs(){if(!battle)return;const m=battle.manual;if(!joy){m.x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0);m.y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);}m.attack=m.attackTouch||keys.has('Space');m.block=m.blockTouch||keys.has('KeyQ');}
function animate(t){requestAnimationFrame(animate);if(!last)last=t;const dt=Math.min(.12,Math.max(0,(t-last)/1000));last=t;now+=dt;toastLeft=Math.max(0,toastLeft-dt);if(!toastLeft)$('toast').hidden=true;if(battle&&!paused&&!document.hidden){inputs();acc+=dt*speed;for(let i=0;i<8&&acc>=1/30&&!battle.done;i++){battle.tick(1/30);acc-=1/30;}if(battle.done){finish();acc=0;}const ev=battle.events.splice(0);let heard=false;for(const e of ev){if(['wave','reserve'].includes(e.type))toast(e.text);if(e.type==='attack'&&e.team===0&&!heard){audio('hit');heard=true;if(profile.save.prefs.motion&&['giant','mage'].includes(e.id))shake=4;}if(e.type==='gold'&&e.team===0)audio('gold');}ambientTime-=dt;if(ambientTime<=0){ambientTime=8;audio('ambient');}const u=battle.units.find(u=>u.uid===battle.selected),front=battle.units.filter(u=>u.team===0&&u.id!=='miner'&&u.state!=='garrison').reduce((a,u)=>Math.max(a,u.x),BASE[0]);if(autoCamera){cameraTarget=clamp((u?u.x:battle.commands[0]==='attack'?front:width/scale*.5)-width/scale*.5,0,Math.max(0,WORLD-width/scale));}camera+=(cameraTarget-camera)*Math.min(1,dt*7);uiClock-=dt;if(uiClock<=0){uiClock=.12;updateHUD();}}shake=Math.max(0,shake-dt*14);render();}
function setup(){for(const id of ['campaign','forge','settings'])$(id).addEventListener('click',()=>{activate();show(id);});document.querySelectorAll('[data-home]').forEach(e=>e.addEventListener('click',()=>show('menu')));$('skirmish').addEventListener('click',()=>brief('skirmish'));$('survival').addEventListener('click',()=>brief('survival'));$('missions').addEventListener('click',e=>{const el=e.target.closest('[data-mission]');if(el&&!el.disabled)brief('campaign',Number(el.dataset.mission));});$('upgrades').addEventListener('click',e=>{const el=e.target.closest('[data-upgrade]');if(el&&profile.upgrade(el.dataset.upgrade)){save();audio('train');renderForge();}});for(const id of ['difficulty','map','sound','motion'])$(id).addEventListener('change',e=>{profile.save.prefs[id]=e.target.type==='checkbox'?e.target.checked:e.target.value;save();});$('brief-back').addEventListener('click',()=>{$('brief').hidden=true;pending=null;});$('begin').addEventListener('click',begin);$('training').addEventListener('click',e=>{const b=e.target.closest('[data-train]');if(b&&!b.disabled)train(b.dataset.train);});$('commands').addEventListener('click',e=>{const b=e.target.closest('[data-command]');if(b)command(b.dataset.command);});$('cancel').addEventListener('click',()=>{if(!paused&&battle){battle.cancel();updateHUD();}});$('pause').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('leave').addEventListener('click',()=>{$('pause-panel').hidden=true;paused=false;save();show('menu');});$('speed').addEventListener('click',()=>{if(!paused){speed=speed===1?2:1;$('speed').textContent=speed+'×';}});$('release').addEventListener('click',()=>control(null));$('ability-unit').addEventListener('click',special);$('camera-home').addEventListener('click',()=>{autoCamera=false;cameraTarget=0;});$('camera-front').addEventListener('click',()=>{autoCamera=false;const front=battle.units.filter(u=>u.team===0&&u.id!=='miner').reduce((a,u)=>Math.max(a,u.x),BASE[0]);cameraTarget=clamp(front-width/scale*.5,0,Math.max(0,WORLD-width/scale));});$('minimap').addEventListener('pointerdown',e=>{if(!battle||paused)return;const r=$('minimap').getBoundingClientRect();autoCamera=false;cameraTarget=clamp((e.clientX-r.left)/r.width*WORLD-width/scale*.5,0,Math.max(0,WORLD-width/scale));});
 canvas.addEventListener('pointerdown',e=>{if(page!=='battle'||paused)return;pan={id:e.pointerId,x:e.clientX,y:e.clientY,camera,dx:0};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(pan?.id!==e.pointerId)return;pan.dx=Math.max(pan.dx,Math.hypot(e.clientX-pan.x,e.clientY-pan.y));if(pan.dx>8){autoCamera=false;camera=cameraTarget=clamp(pan.camera-(e.clientX-pan.x)/scale,0,Math.max(0,WORLD-width/scale));}});canvas.addEventListener('pointerup',e=>{if(pan?.id!==e.pointerId)return;if(pan.dx<8){const x=e.clientX/scale+camera,y=(e.clientY-ground)/scale;const found=battle.units.filter(u=>u.team===0&&u.state!=='garrison').map(u=>({u,d:Math.hypot((u.x-x)*.8,u.y-35-y)})).sort((a,b)=>a.d-b.d)[0];if(found&&found.d<(found.u.id==='giant'?75:48))control(found.u);else if(battle.selected)control(null);}pan=null;});for(const event of ['pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>pan=null);
 function stick(e){if(!battle||paused)return;const r=$('joystick').getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),radius=r.width*.33,d=Math.max(radius,Math.hypot(dx,dy));battle.manual.x=dx/d;battle.manual.y=dy/d;$('knob').style.transform='translate('+(dx/d*radius)+'px,'+(dy/d*radius)+'px)';}
 $('joystick').addEventListener('pointerdown',e=>{e.preventDefault();joy=e.pointerId;$('joystick').setPointerCapture(e.pointerId);stick(e);});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===joy)stick(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(event,()=>{joy=null;if(battle){battle.manual.x=0;battle.manual.y=0;}$('knob').style.transform='';});for(const[id,key]of[['attack-unit','attackTouch'],['block-unit','blockTouch']]){$(id).addEventListener('pointerdown',e=>{if(!battle||paused)return;e.preventDefault();$(id).setPointerCapture(e.pointerId);battle.manual[key]=true;activate();});for(const event of ['pointerup','pointercancel','lostpointercapture'])$(id).addEventListener(event,()=>{if(battle)battle.manual[key]=false;});}
 $('result-home').addEventListener('click',()=>{$('result').hidden=true;paused=false;show('menu');});$('result-next').addEventListener('click',()=>{const b=battle;$('result').hidden=true;paused=false;if(b.mode==='campaign'&&b.winner===0){const n=b.mission.id+1;if(n>12){show('campaign');toast('The kingdom is yours. All twelve territories captured.');}else{show('campaign');brief('campaign',n);}}else{pending={mode:b.mode,mission:b.mission.id};begin();}});
 addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target?.tagName)||$('brief').hidden===false)return;if(e.code==='Escape'){e.preventDefault();if(page==='battle'){if(paused&&!battle.done)resume();else pause();}else show('menu');return;}if(page!=='battle'||paused)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD','Space','KeyQ'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.repeat)return;if(/^Digit[1-6]$/.test(e.code))train(UNITS[Number(e.code.slice(-1))-1].id);const cmd={KeyZ:'defend',KeyX:'attack',KeyC:'garrison'}[e.code];if(cmd)command(cmd);if(e.code==='KeyR')control(null);if(e.code==='KeyE')special();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);addEventListener('blur',()=>{resetInput();if(page==='battle')pause();save();});document.addEventListener('visibilitychange',()=>{resetInput();if(document.hidden){if(page==='battle')pause();last=0;save();}});addEventListener('pagehide',save);
 show('menu');parent.postMessage({type:'pocketvm-stick-ready'},'*');requestAnimationFrame(animate);
}
try{setup();}catch(e){$('error').hidden=false;$('error-text').textContent=e.message;console.error(e);}
})();
