// Test the shipped Store installer and sandbox launcher using a disposable virtual drive.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..'),store=fs.readFileSync(path.join(root,'store.js'),'utf8'),html=fs.readFileSync(path.join(root,'store/apexrush/game.html'),'utf8'),mp3=fs.readFileSync(path.join(root,'store/apexrush/music.mp3'));
function context(badMusic=false){const files=new Map(),storage=new Map(),events={},frame={contentWindow:{}},loading={classList:{add(){}}};
 class FileReader{async readAsDataURL(blob){this.result='data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64');this.onload?.()}}
 const disk={ensureDir:async p=>files.set(p,{type:'dir'}),writeText:async(p,text)=>files.set(p,{type:'file',text,size:Buffer.byteLength(text)}),writeBlob:async(p,blob)=>files.set(p,{type:'file',blob,size:blob.size}),readText:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).text},readBlob:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).blob},getNode:async p=>files.get(p),snapshot:async()=>Object.fromEntries(files),remove:async p=>{for(const k of files.keys())if(k===p||k.startsWith(p+'/'))files.delete(k)}};
 const box={console,URL,Blob,FileReader,CSS:{escape:s=>String(s)},location:{href:'https://example.com/PocketVM/'},PocketDisk:disk,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:()=>null,getElementById:()=>null},addEventListener:(k,f)=>events[k]=f,removeEventListener(){},setTimeout,clearTimeout,fetch:async url=>({ok:true,text:async()=>html,blob:async()=>new Blob([badMusic?Buffer.alloc(1):mp3],{type:'audio/mpeg'})})};box.window=box;
 // SVG-to-PNG is visually verified in the browser; retain the actual installer and every disk operation.
 const source=store.replace(/async function createApexIconBlob\(\)\{[^\n]+/,"async function createApexIconBlob(){return new Blob(['test PNG'],{type:'image/png'})}");vm.runInNewContext(source,box,{filename:'store.js'});
 const ctx={queryOne:selector=>selector==='iframe'?frame:selector==='.store-game-loading'?loading:null,setWindowTitle(){},escapeHTML:s=>s,refreshFS:async()=>{},notify(){},state:{windows:new Map()},setWindowIcon(){},initDesktopGrid(){}};
 return{app:box.PocketStoreApp,files,storage,events,frame,loading,ctx};
}
(async()=>{
 const c=context(),progress=[];await c.app.installApex((bytes,total,file)=>progress.push({bytes,total,file}));assert.equal(await c.app.apexInstalled(),true);assert.equal(c.files.get('/home/user/Downloads/Apex Rush/music.mp3').size,mp3.length);assert.equal(c.files.get('/home/user/Downloads/Apex Rush/game.html').text,html);assert.equal(c.files.get('/home/user/Downloads/Apex Rush/name.txt').text,'Apex Rush');assert.equal(progress.at(-1).bytes,progress.at(-1).total);console.log('PASS Installer writes the verified HTML, uploaded music, icon and identity');
 c.storage.set('pocketvm.game.apexrush',JSON.stringify({prefs:{paint:'#123abc',volume:.7},bestLaps:{'metro-rain':31.4}}));const win={id:'test-race',content:{},el:{querySelector:()=>null}};await c.app.buildApex(win,{},c.ctx);assert.ok(c.frame.srcdoc.includes('data:audio/mpeg;base64,'));assert.ok(c.frame.srcdoc.includes('"paint":"#123abc"'));assert.ok(c.frame.srcdoc.includes('"metro-rain":31.4'));c.events.message({source:{},data:{type:'pocketvm-apex-save',data:{wins:99}}});assert.ok(!JSON.parse(c.storage.get('pocketvm.game.apexrush')).wins);c.events.message({source:c.frame.contentWindow,data:{type:'pocketvm-apex-save',data:{wins:3,prefs:{paint:'#abcdef',volume:.2}}}});assert.equal(JSON.parse(c.storage.get('pocketvm.game.apexrush')).wins,3);assert.equal(JSON.parse(c.storage.get('pocketvm.game.apexrush')).prefs.paint,'#abcdef');console.log('PASS Sandbox launcher injects music and saved settings; only its own frame can save');
 const bad=context(true);await assert.rejects(()=>bad.app.installApex(),/soundtrack/);assert.equal(await bad.app.apexInstalled(),false);assert.equal(bad.files.size,0);console.log('PASS A truncated music download rolls back the incomplete installation');
 fs.writeFileSync(path.join(__dirname,'apex-package-results.json'),JSON.stringify({checks:3,tests:['Installer writes verified package and exact music bytes','Sandbox boot and source-checked saves','Truncated music rollback']},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1});
