// Real Store package, virtual disk, source-checked saves, updates and artwork migration.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),store=fs.readFileSync(path.join(root,'store.js'),'utf8'),home='/home/user/Downloads/Ball vs Ball',tests=[];
function context(badFile=null){const files=new Map(),storage=new Map(),events={},frame={contentWindow:{}},loading={classList:{add(){}}};let offline=false,failWrite=false;
 class FileReader{async readAsDataURL(blob){this.result='data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64');this.onload?.()}}
 const disk={ensureDir:async p=>files.set(p,{type:'dir'}),writeText:async(p,text)=>{if(failWrite&&p.endsWith('/game.js'))throw Error('Drive write interrupted');files.set(p,{type:'file',text,size:Buffer.byteLength(text)})},writeBlob:async(p,blob)=>files.set(p,{type:'file',blob,size:blob.size}),readText:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).text},readBlob:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).blob},getNode:async p=>files.get(p),snapshot:async()=>Object.fromEntries(files),remove:async p=>{for(const k of files.keys())if(k===p||k.startsWith(p+'/'))files.delete(k)}};
 const box={console,URL,Blob,Uint8Array,DataView,FileReader,CSS:{escape:s=>String(s)},location:{href:'https://example.com/PocketVM/'},PocketDisk:disk,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:()=>null,getElementById:()=>null},addEventListener:(k,f)=>events[k]=f,removeEventListener(){},setTimeout,clearTimeout,fetch:async url=>{if(offline)throw Error('Offline');const pathname=new URL(url,box.location.href).pathname.replace('/PocketVM/',''),data=pathname.endsWith(badFile)&&badFile?Buffer.alloc(1):fs.readFileSync(path.join(root,pathname));return{ok:true,text:async()=>data.toString('utf8'),blob:async()=>new Blob([data],{type:pathname.endsWith('.png')?'image/png':pathname.endsWith('.mp3')?'audio/mpeg':'text/plain'})}}};box.window=box;vm.runInNewContext(store,box,{filename:'store.js'});
 const ctx={queryOne:selector=>selector==='iframe'?frame:selector==='.store-game-loading'?loading:null,setWindowTitle(){},escapeHTML:s=>s,refreshFS:async()=>{},notify(){},state:{windows:new Map()},setWindowIcon(){},initDesktopGrid(){}};
 return{app:box.PocketStoreApp,files,storage,events,frame,loading,ctx,disk,setOffline:v=>offline=v,setFailWrite:v=>failWrite=v};
}
function pass(name){tests.push(name);console.log('PASS '+name)}
(async()=>{
 const c=context(),progress=[];await c.app.installBall((bytes,total,file)=>progress.push({bytes,total,file}));assert.equal(await c.app.ballInstalled(),true);for(const name of ['game.html','core.js','game.js'])assert.equal(c.files.get(home+'/'+name).text,fs.readFileSync(path.join(root,'store/ballvsball',name),'utf8'));for(const name of ['menu.mp3','battle.mp3'])assert.deepEqual(Buffer.from(await c.files.get(home+'/'+name).blob.arrayBuffer()),fs.readFileSync(path.join(root,'store/ballvsball',name)));assert.equal(progress.at(-1).bytes,progress.at(-1).total);pass('Installer verifies the full game, both exact music files and matching artwork');
 c.storage.set('pocketvm.game.ballvsball',JSON.stringify({coins:500,owned:['king'],prefs:{mode:'team',music:false}}));const win={id:'ball-test',content:{},el:{querySelector:()=>null}};await c.app.buildBall(win,{},c.ctx);const scripts=[...c.frame.srcdoc.matchAll(/src="(data:text\/javascript;base64,[^"]+)"/g)];assert.equal(scripts.length,2);for(let i=0;i<2;i++)assert.equal(Buffer.from(scripts[i][1].split(',')[1],'base64').toString('utf8'),fs.readFileSync(path.join(root,'store/ballvsball',i===0?'core.js':'game.js'),'utf8'));const audio=[...c.frame.srcdoc.matchAll(/src="(data:audio\/mpeg;base64,[^"]+)"/g)];assert.equal(audio.length,2);for(let i=0;i<2;i++)assert.deepEqual(Buffer.from(audio[i][1].split(',')[1],'base64'),fs.readFileSync(path.join(root,'store/ballvsball',i===0?'menu.mp3':'battle.mp3')));assert.ok(c.frame.srcdoc.includes('"coins":500'));assert.ok(c.frame.srcdoc.includes('https://example.com/PocketVM/store/ballvsball/favicon-32.png'));pass('Sandbox embeds both scripts and songs without relative dependencies');
 const old=c.storage.get('pocketvm.game.ballvsball');c.events.message({source:{},data:{type:'pocketvm-ball-save',data:{coins:999999}}});assert.equal(c.storage.get('pocketvm.game.ballvsball'),old);const raw={coins:900,owned:['king','fake'],prefs:{volume:9,mode:'local'}};c.events.message({source:c.frame.contentWindow,data:{type:'pocketvm-ball-save',data:raw}});assert.deepEqual(JSON.parse(c.storage.get('pocketvm.game.ballvsball')),require('../store/ballvsball/core.js').clean(raw));pass('Source-checked game saves exactly match the core sanitizer');
 for(const file of ['game.html','core.js','game.js','menu.mp3','battle.mp3','icon-512.png']){const b=context(file);await assert.rejects(()=>b.app.installBall(),/incomplete|verification/);assert.equal(b.files.size,0);}pass('Six truncated download types cannot create a partial installation');
 const broken=context();broken.setFailWrite(true);await assert.rejects(()=>broken.app.installBall(),/interrupted/);assert.equal(broken.files.size,0);pass('A failed drive write rolls back the incomplete package');
 await c.disk.writeText(home+'/core.js','old code');await c.disk.writeText(home+'/name.txt','My Duel');await c.app.buildBall(win,{},c.ctx);assert.equal(c.files.get(home+'/core.js').text,fs.readFileSync(path.join(root,'store/ballvsball/core.js'),'utf8'));assert.equal(c.files.get(home+'/name.txt').text,'My Duel');assert.ok(c.frame.srcdoc.includes('"coins":900'));pass('Repair preserves the custom name, collection and coins');
 c.setOffline(true);await c.app.buildBall(win,{},c.ctx);assert.equal([...c.frame.srcdoc.matchAll(/data:audio\/mpeg;base64/g)].length,2);pass('Complete installed games start with code and music offline');const before=c.storage.get('pocketvm.game.ballvsball');await c.app.uninstallBall();assert.equal(await c.app.ballInstalled(),false);assert.equal(c.storage.get('pocketvm.game.ballvsball'),before);pass('Uninstall preserves collection and earned coins');
 fs.writeFileSync(path.join(__dirname,'ball-package-results.json'),JSON.stringify({checks:tests.length,tests},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1});
