// Real Store package, virtual disk, source-checked saves, updates and artwork migration.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),store=fs.readFileSync(path.join(root,'store.js'),'utf8'),home='/home/user/Downloads/Fisch Horizon',tests=[];
function context(badFile=null){const files=new Map(),storage=new Map(),events={},frame={contentWindow:{}},loading={classList:{add(){}}};let offline=false,failWrite=false;
 class FileReader{async readAsDataURL(blob){this.result='data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64');this.onload?.()}}
 const disk={ensureDir:async p=>files.set(p,{type:'dir'}),writeText:async(p,text)=>{if(failWrite&&p.endsWith('/game.js'))throw Error('Drive write interrupted');files.set(p,{type:'file',text,size:Buffer.byteLength(text)})},writeBlob:async(p,blob)=>files.set(p,{type:'file',blob,size:blob.size}),readText:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).text},readBlob:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).blob},getNode:async p=>files.get(p),snapshot:async()=>Object.fromEntries(files),remove:async p=>{for(const k of files.keys())if(k===p||k.startsWith(p+'/'))files.delete(k)}};
 const box={console,URL,Blob,Uint8Array,DataView,FileReader,CSS:{escape:s=>String(s)},location:{href:'https://example.com/PocketVM/'},PocketDisk:disk,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:()=>null,getElementById:()=>null},addEventListener:(k,f)=>events[k]=f,removeEventListener(){},setTimeout,clearTimeout,fetch:async url=>{if(offline)throw Error('Offline');const pathname=new URL(url,box.location.href).pathname.replace('/PocketVM/',''),data=pathname.endsWith(badFile)&&badFile?Buffer.alloc(1):fs.readFileSync(path.join(root,pathname));return{ok:true,text:async()=>data.toString('utf8'),blob:async()=>new Blob([data],{type:pathname.endsWith('.png')?'image/png':'text/plain'})}}};box.window=box;vm.runInNewContext(store,box,{filename:'store.js'});
 const ctx={queryOne:selector=>selector==='iframe'?frame:selector==='.store-game-loading'?loading:null,setWindowTitle(){},escapeHTML:s=>s,refreshFS:async()=>{},notify(){},state:{windows:new Map()},setWindowIcon(){},initDesktopGrid(){}};
 return{app:box.PocketStoreApp,files,storage,events,frame,loading,ctx,disk,setOffline:v=>offline=v,setFailWrite:v=>failWrite=v};
}
function pass(name){tests.push(name);console.log('PASS '+name)}
(async()=>{
 const c=context(),progress=[];await c.app.installFisch((bytes,total,file)=>progress.push({bytes,total,file}));assert.equal(await c.app.fischInstalled(),true);for(const name of ['game.html','engine.js','game.js','three.min.js','software-renderer.js','THREE-LICENSE.txt'])assert.equal(c.files.get(home+'/'+name).text,fs.readFileSync(path.join(root,'store/fisch',name),'utf8'));assert.equal(progress.at(-1).bytes,progress.at(-1).total);assert.equal(c.files.get(home+'/name.txt').text,'Fisch: Horizon');pass('Installer verifies every world, engine, vendor, licence and icon byte');
 c.storage.set('pocketvm.game.fisch',JSON.stringify({coins:326,prefs:{touch:'on',assist:false},rods:['steady'],rod:'steady',visited:['reef'],seen:{'harbor-0':{count:2,weight:1.5}}}));const win={id:'test-fisch',content:{},el:{querySelector:()=>null}};await c.app.buildFisch(win,{},c.ctx);const sources=[...c.frame.srcdoc.matchAll(/src="(data:text\/javascript;base64,[^"]+)"/g)];assert.equal(sources.length,4);for(let i=0;i<4;i++){const expected=['three.min.js','software-renderer.js','engine.js','game.js'][i],decoded=Buffer.from(sources[i][1].split(',')[1],'base64').toString('utf8');assert.equal(decoded,fs.readFileSync(path.join(root,'store/fisch',expected),'utf8'));}assert.ok(c.frame.srcdoc.includes('"coins":326'));assert.ok(c.frame.srcdoc.includes('"touch":"on"'));assert.ok(c.frame.srcdoc.includes('https://example.com/PocketVM/store/fisch/favicon-32.png'));assert.ok(c.frame.srcdoc.includes('src="https://example.com/PocketVM/store/fisch/icon.svg"'));pass('Sandbox embeds all scripts and resolves every artwork path');
 const old=c.storage.get('pocketvm.game.fisch');c.events.message({source:{},data:{type:'pocketvm-fisch-save',data:{coins:99999}}});assert.equal(c.storage.get('pocketvm.game.fisch'),old);const raw={coins:219,rods:['steady','fake'],visited:['reef','reef','fake'],prefs:{touch:'on',sensitivity:99},bag:[{uid:'f1',fish:'harbor-0',weight:1,value:30},{fish:'fake',value:999999}],position:{x:Infinity,z:-30}};c.events.message({source:c.frame.contentWindow,data:{type:'pocketvm-fisch-save',data:raw}});const s=JSON.parse(c.storage.get('pocketvm.game.fisch'));assert.deepEqual(s,require('../store/fisch/engine.js').clean(raw));pass('Only this frame saves; shell and game sanitizers match exactly');
 for(const file of ['game.html','engine.js','game.js','three.min.js','software-renderer.js','icon-512.png']){const b=context(file);await assert.rejects(()=>b.app.installFisch(),/incomplete|verification/);assert.equal(b.files.size,0);}pass('Six truncated downloads cannot create a partial installation');
 const broken=context();broken.setFailWrite(true);await assert.rejects(()=>broken.app.installFisch(),/interrupted/);assert.equal(broken.files.size,0);pass('Interrupted virtual-drive writes roll back the package');
 await c.disk.writeText(home+'/engine.js','old engine');c.files.delete(home+'/software-renderer.js');await c.disk.writeText(home+'/name.txt','My Sea');await c.app.buildFisch(win,{},c.ctx);assert.equal(c.files.get(home+'/engine.js').text,fs.readFileSync(path.join(root,'store/fisch/engine.js'),'utf8'));assert.equal(c.files.get(home+'/name.txt').text,'My Sea');assert.ok(c.frame.srcdoc.includes('"coins":219'));pass('Outdated files repair on launch while retaining identity and progress');
 c.setOffline(true);await c.app.buildFisch(win,{},c.ctx);assert.equal([...c.frame.srcdoc.matchAll(/data:text\/javascript;base64/g)].length,4);pass('Installed game embeds its full 3D engine offline');const before=c.storage.get('pocketvm.game.fisch');await c.app.uninstallFisch();assert.equal(await c.app.fischInstalled(),false);assert.equal(c.storage.get('pocketvm.game.fisch'),before);pass('Uninstall preserves earned catches and gear');
 fs.writeFileSync(path.join(__dirname,'fisch-package-results.json'),JSON.stringify({checks:tests.length,tests},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1});
