const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),native=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/':'')+'@napi-rs/canvas');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'store/gradeschool/game.html'),'utf8'),nodes=new Map(),frames=[],messages=[],storage=new Map(),tests=[];
let currentDocument,clock=0;
const rect=(x,y,width,height)=>({x,y,left:x,top:y,right:x+width,bottom:y+height,width,height});
function element(id){if(nodes.has(id))return nodes.get(id);const e=id==='room'?native.createCanvas(1024,768):{},classes=new Set(),handlers={};Object.assign(e,{id,hidden:false,disabled:false,checked:false,dataset:{},children:[],style:{setProperty(){}},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),toggle(x,v){v=v??!classes.has(x);if(v)classes.add(x);else classes.delete(x)}},textContent:'',getBoundingClientRect(){return id==='playArea'?rect(0,78,1024,690):id==='class-side'?rect(23,105,310,620):id==='student-info'?rect(23,636,310,88):rect(380,200,500,350)},closest:()=>element('student-info'),scrollTop:0,addEventListener:(k,f)=>{handlers[k]=f},fire(k){handlers[k]?.({target:e})},focus(){currentDocument.activeElement=e},appendChild(){},remove(){},querySelectorAll(selector){return e.children.filter(x=>selector==='button,input'?x.tagName==='BUTTON'||x.tagName==='INPUT':selector.includes('[data-')?x.dataset[selector.match(/data-([\w-]+)/)[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]!==undefined:selector.includes('button')?x.tagName==='BUTTON':false)},querySelector(s){return e.querySelectorAll(s)[0]||null}});
Object.defineProperty(e,'innerHTML',{get(){return e._html||''},set(value){e._html=value;e.children=[];for(const match of value.matchAll(/<(button|input)\b([^>]*)>/g)){const id=match[2].match(/\bid="([^"]+)"/)?.[1]||'anon-'+nodes.size,child=element(id);child.tagName=match[1].toUpperCase();child.disabled=/\bdisabled\b/.test(match[2]);for(const [,key,val]of match[2].matchAll(/data-([\w-]+)="([^"]*)"/g))child.dataset[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=val;e.children.push(child)}}});nodes.set(id,e);return e}
for(const [,tag,id]of html.matchAll(/(<[^>]*\bid="([^"]+)"[^>]*>)/g))element(id).hidden=/\bhidden\b/.test(tag);
element('class-side');element('student-info');const doc={hidden:false,activeElement:null,getElementById:id=>nodes.get(id)||null,querySelector:s=>s==='.class-side'?element('class-side'):null,body:element('body'),documentElement:element('root'),createElement:()=>element('new-'+nodes.size),addEventListener(){}};currentDocument=doc;
const box={console,Math,Date,Map,Set,JSON,document:doc,performance:{now:()=>clock},innerWidth:1024,innerHeight:768,devicePixelRatio:1,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},parent:{postMessage:m=>messages.push(m)},setTimeout:()=>0,clearTimeout(){},requestAnimationFrame:f=>frames.push(f),addEventListener(){}};box.window=box;vm.createContext(box);for(const file of ['core.js','game.js'])vm.runInContext(fs.readFileSync(path.join(root,'store/gradeschool',file),'utf8'),box,{filename:file});
function pass(name){tests.push(name);console.log('PASS '+name)}
assert.equal(element('fatal').hidden,true);assert.ok(messages.some(m=>m.type==='pocketvm-grade-ready'));assert.ok(element('modal').innerHTML.includes('Grade<br>'));pass('Actual game UI boots to the welcome menu and signals PocketVM readiness');
clock=100;frames.shift()(clock);const canvas=element('room'),pixels=canvas.getContext('2d').getImageData(0,0,1024,768).data,colours=new Set();for(let i=0;i<pixels.length;i+=128)colours.add(pixels[i]+','+pixels[i+1]+','+pixels[i+2]);assert.ok(colours.size>150);fs.writeFileSync(path.join(__dirname,'grade-classroom.png'),canvas.toBuffer('image/png'));pass('Production Canvas renders original students, windows, desks and classroom in hundreds of colours');
element('careerStart').fire('click');assert.ok(element('modal').innerHTML.includes('School day 1'));element('ringIn').fire('click');assert.equal(element('modalBackdrop').hidden,true);assert.ok(element('questions').innerHTML.includes('STUDENT’S ANSWER'));assert.equal(element('actions').children.length,2);assert.ok(storage.get('pocketvm.game.gradeschool'));pass('Production career buttons start a paper with both touch stamps and persist a resumable session');
element('hintButton').fire('click');assert.equal(element('hintBox').hidden,false);assert.equal(element('hintButton').disabled,true);element('actions').children[1].fire('click');assert.equal(element('feedback').hidden,false);assert.ok(element('feedback').innerHTML.includes('Answer:'));clock=800;frames.shift()(clock);element('nextPaper').fire('click');assert.equal(element('feedback').hidden,true);assert.equal(JSON.parse(storage.get('pocketvm.game.gradeschool')).total,1);pass('Real answer-key, stamp, feedback and next-student event handlers complete one grading cycle');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),assets=vm.runInNewContext(sw.split("self.addEventListener('install'")[0]+'ASSETS'),base='https://example.com/PocketVM/',cache=new Set(assets.map(a=>new URL(a,base).href));for(const [,url]of html.matchAll(/<script[^>]*src="([^"]+)"/g))assert.ok(cache.has(new URL(url,new URL('store/gradeschool/game.html',base)).href));for(const url of ['icon.svg?v=illustrated-v1','favicon-32.png','icon-180.png','icon-512.png'])assert.ok(cache.has(new URL('./store/gradeschool/'+url,base).href));pass('Offline cache contains exact versioned scripts, illustrated icon and all touch exports');
const store=fs.readFileSync(path.join(root,'store.js'),'utf8'),files=JSON.parse(store.match(/const GRADE_FILES=(\[[^\n]+\]);/)[1]);for(const file of files)assert.equal(file.size,fs.statSync(path.join(root,'store/gradeschool',file.name)).size);pass('Store package verification sizes match every production file');
fs.writeFileSync(path.join(__dirname,'grade-render-results.json'),JSON.stringify({checks:tests.length,tests,sampledColours:colours.size},null,2)+'\n');
