const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),native=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/':'')+'@napi-rs/canvas');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'store/gradeschool/game.html'),'utf8'),nodes=new Map(),frames=[],messages=[],storage=new Map(),tests=[];
let currentDocument,clock=0;const documentHandlers={},windowHandlers={};
const rect=(x,y,width,height)=>({x,y,left:x,top:y,right:x+width,bottom:y+height,width,height});
function element(id){if(nodes.has(id))return nodes.get(id);const e=['room','inkCanvas'].includes(id)?native.createCanvas(1024,768):{},classes=new Set(),handlers={};Object.assign(e,{id,hidden:false,disabled:false,checked:false,dataset:{},children:[],style:{setProperty(){}},classList:{contains:x=>classes.has(x),add:x=>classes.add(x),remove:x=>classes.delete(x),toggle(x,v){v=v??!classes.has(x);if(v)classes.add(x);else classes.delete(x)}},textContent:'',getBoundingClientRect(){return id==='playArea'?rect(0,78,1024,690):id==='class-side'?rect(23,105,310,620):id==='student-info'?rect(23,636,310,88):rect(380,200,500,350)},closest:()=>element('student-info'),scrollTop:0,addEventListener:(k,f)=>{handlers[k]=f},fire(k,args={}){handlers[k]?.({target:e,preventDefault(){},pointerId:1,pressure:.5,...args})},insertAdjacentHTML(pos,value){e._html=value+(e._html||'')},setAttribute(k,v){e[k]=v},setPointerCapture(){},releasePointerCapture(){},focus(){currentDocument.activeElement=e},appendChild(child){child.parentNode=e;e.children.push(child)},insertBefore(child,before){if(child.parentNode){const i=child.parentNode.children.indexOf(child);if(i>=0)child.parentNode.children.splice(i,1)}child.parentNode=e;const i=e.children.indexOf(before);e.children.splice(i<0?e.children.length:i,0,child)},remove(){},querySelectorAll(selector){return e.children.filter(x=>selector==='button,input'?x.tagName==='BUTTON'||x.tagName==='INPUT':selector.includes('[data-')?x.dataset[selector.match(/data-([\w-]+)/)[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]!==undefined:selector.includes('button')?x.tagName==='BUTTON':false)},querySelector(s){return e.querySelectorAll(s)[0]||null}});
Object.defineProperty(e,'innerHTML',{get(){return e._html||''},set(value){e._html=value;e.children=[];for(const match of value.matchAll(/<(button|input)\b([^>]*)>/g)){const id=match[2].match(/\bid="([^"]+)"/)?.[1]||'anon-'+nodes.size,child=element(id);child.tagName=match[1].toUpperCase();child.disabled=/\bdisabled\b/.test(match[2]);for(const [,key,val]of match[2].matchAll(/data-([\w-]+)="([^"]*)"/g))child.dataset[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=val;e.children.push(child)}}});nodes.set(id,e);return e}
for(const [,tag,id]of html.matchAll(/(<[^>]*\bid="([^"]+)"[^>]*>)/g))element(id).hidden=/\bhidden\b/.test(tag);
element('class-side');element('student-info');element('paper-area').appendChild(element('markingControls'));element('paper-area').appendChild(element('feedback'));element('game').appendChild(element('modalBackdrop'));const doc={hidden:false,activeElement:null,getElementById:id=>nodes.get(id)||null,querySelector:s=>s==='.class-side'?element('class-side'):s==='.tools'?element('tools'):null,body:element('body'),documentElement:element('root'),createElement:()=>element('new-'+nodes.size),addEventListener:(k,f)=>documentHandlers[k]=f};currentDocument=doc;
const box={console,Math,Date,Map,Set,JSON,document:doc,performance:{now:()=>clock},innerWidth:1024,innerHeight:768,devicePixelRatio:1,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},parent:{postMessage:m=>messages.push(m)},setTimeout:()=>0,clearTimeout(){},requestAnimationFrame:f=>frames.push(f),addEventListener:(k,f)=>windowHandlers[k]=f};box.window=box;vm.createContext(box);for(const file of ['core.js','game.js'])vm.runInContext(fs.readFileSync(path.join(root,'store/gradeschool',file),'utf8'),box,{filename:file});
function pass(name){tests.push(name);console.log('PASS '+name)}
assert.equal(element('fatal').hidden,true);assert.ok(messages.some(m=>m.type==='pocketvm-grade-ready'));assert.ok(element('modal').innerHTML.includes('Grade<br>'));pass('Actual game UI boots to the welcome menu and signals PocketVM readiness');
clock=100;frames.shift()(clock);const canvas=element('room'),pixels=canvas.getContext('2d').getImageData(0,0,1024,768).data,colours=new Set();for(let i=0;i<pixels.length;i+=128)colours.add(pixels[i]+','+pixels[i+1]+','+pixels[i+2]);assert.ok(colours.size>150);fs.writeFileSync(path.join(__dirname,'grade-classroom.png'),canvas.toBuffer('image/png'));pass('Production Canvas renders original students, windows, desks and classroom in hundreds of colours');
element('careerStart').fire('click');assert.ok(element('modal').innerHTML.includes('School day 1'));element('ringIn').fire('click');assert.equal(element('modalBackdrop').hidden,true);assert.ok(element('questions').innerHTML.includes('STUDENT’S ANSWER'));assert.equal(element('actions').children.length,3);assert.equal(element('handIn').disabled,true);assert.ok(storage.get('pocketvm.game.gradeschool'));pass('Production career buttons start a paper with both ink selectors and persist a resumable session');
element('redInk').fire('click');assert.equal(element('redInk')['aria-pressed'],'true');element('inkCanvas').fire('pointerdown',{clientX:500,clientY:350});element('inkCanvas').fire('pointermove',{clientX:500,clientY:430});element('inkCanvas').fire('pointerup',{clientX:500,clientY:450});assert.equal(element('handIn').disabled,false);const inkPixels=element('inkCanvas').getContext('2d').getImageData(0,0,element('inkCanvas').width,element('inkCanvas').height).data;assert.ok(inkPixels.some((v,i)=>i%4===3&&v>0));assert.equal(JSON.parse(storage.get('pocketvm.game.gradeschool')).session.drawing.strokes.length,1);element('undoInk').fire('click');assert.equal(element('handIn').disabled,true);element('greenInk').fire('click');element('inkCanvas').fire('pointerdown',{clientX:500,clientY:350});element('inkCanvas').fire('pointermove',{clientX:550,clientY:420});element('inkCanvas').fire('pointerup',{clientX:610,clientY:350});assert.equal(element('handIn').disabled,false);element('handIn').fire('click');assert.equal(element('feedback').hidden,false);assert.ok(element('feedback').innerHTML.includes('Answer:'));clock=1800;frames.shift()(clock);element('nextPaper').fire('click');assert.equal(element('feedback').hidden,true);assert.equal(JSON.parse(storage.get('pocketvm.game.gradeschool')).total,1);assert.equal(element('handIn').disabled,true);pass('Real pointer strokes paint ink, save the drawing, undo, switch colour and hand back a graded paper');

const savedDrawing=()=>JSON.parse(storage.get('pocketvm.game.gradeschool')).session.drawing;
function key(value,opts={}){let prevented=false;documentHandlers.keydown({key:value,preventDefault(){prevented=true},...opts});return prevented}
element('redInk').fire('click');const ink=element('inkCanvas');ink.fire('pointerdown',{button:2,clientX:500,clientY:350});ink.fire('pointermove',{clientX:560,clientY:400});ink.fire('pointerup',{clientX:560,clientY:400});assert.equal(savedDrawing().strokes.length,0);
ink.fire('pointerdown',{isPrimary:false,clientX:500,clientY:350});ink.fire('pointerup',{clientX:560,clientY:400});assert.equal(savedDrawing().strokes.length,0);
ink.fire('pointerdown',{clientX:500,clientY:350});ink.fire('pointercancel',{pointerId:99});ink.fire('pointermove',{clientX:560,clientY:400,getCoalescedEvents:()=>[]});ink.fire('pointerup',{clientX:560,clientY:400});assert.equal(savedDrawing().strokes.length,1);assert.equal(element('handIn').disabled,false);pass('Right clicks and secondary touches cannot draw; empty coalesced events and secondary cancellation preserve the primary stroke');
element('undoInk').fire('click');assert.equal(savedDrawing().strokes.length,0);assert.equal(element('redoInk').disabled,false);element('redoInk').fire('click');assert.equal(savedDrawing().strokes.length,1);assert.equal(key('z',{ctrlKey:true}),true);assert.equal(savedDrawing().strokes.length,0);assert.equal(key('z',{metaKey:true,shiftKey:true}),true);assert.equal(savedDrawing().strokes.length,1);assert.equal(key('r',{ctrlKey:true}),false);assert.equal(key('a',{metaKey:true}),false);assert.equal(savedDrawing().ink,'F');pass('Undo and redo work with buttons and laptop shortcuts while browser refresh and select-all remain untouched');
element('movePage').fire('click');assert.equal(element('body').classList.contains('move-page'),true);ink.fire('pointerdown',{clientX:500,clientY:350});ink.fire('pointerup',{clientX:560,clientY:400});assert.equal(savedDrawing().strokes.length,1);element('greenInk').fire('click');assert.equal(element('body').classList.contains('move-page'),false);ink.fire('pointerdown',{clientX:500,clientY:350});ink.fire('pointermove',{clientX:570,clientY:390});windowHandlers.blur();assert.equal(savedDrawing().strokes.length,1);windowHandlers.focus();ink.fire('pointerdown',{pointerId:2,clientX:500,clientY:350});ink.fire('pointerup',{pointerId:2,clientX:600,clientY:440});assert.equal(savedDrawing().strokes.length,2);pass('Move page blocks accidental ink, choosing a colour restores drawing, and focus loss safely saves and releases a stroke');
const beforeRotation=JSON.stringify(savedDrawing());box.innerWidth=390;box.innerHeight=844;windowHandlers.resize();assert.equal(element('markingControls').parentNode,element('game'));assert.equal(element('body').classList.contains('compact-controls'),true);box.innerWidth=1366;box.innerHeight=768;windowHandlers.resize();assert.equal(element('markingControls').parentNode,element('paper-area'));assert.equal(element('body').classList.contains('compact-controls'),false);assert.equal(JSON.stringify(savedDrawing()),beforeRotation);
const beforeHidden=canvas.toBuffer('image/png');doc.hidden=true;documentHandlers.visibilitychange();clock=5000;for(let i=0;i<6;i++)frames.shift()?.(clock+i*100);assert.deepEqual(canvas.toBuffer('image/png'),beforeHidden);doc.hidden=false;documentHandlers.visibilitychange();pass('Phone and laptop controls relocate without losing ink, and hidden tabs do not redraw the classroom');
element('handIn').fire('click');assert.equal(element('handIn').textContent,'Next student →');clock=6000;element('handIn').fire('click');assert.equal(element('feedback').hidden,true);assert.equal(element('handIn').disabled,true);pass('The dock advances to the next student after feedback without depending on animation frames');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),assets=vm.runInNewContext(sw.split("self.addEventListener('install'")[0]+'ASSETS'),base='https://example.com/PocketVM/',cache=new Set(assets.map(a=>new URL(a,base).href));for(const [,url]of html.matchAll(/<script[^>]*src="([^"]+)"/g))assert.ok(cache.has(new URL(url,new URL('store/gradeschool/game.html',base)).href));for(const url of ['icon.svg?v=illustrated-v1','favicon-32.png','icon-180.png','icon-512.png'])assert.ok(cache.has(new URL('./store/gradeschool/'+url,base).href));pass('Offline cache contains exact versioned scripts, illustrated icon and all touch exports');
const store=fs.readFileSync(path.join(root,'store.js'),'utf8'),files=JSON.parse(store.match(/const GRADE_FILES=(\[[^\n]+\]);/)[1]);for(const file of files)assert.equal(file.size,fs.statSync(path.join(root,'store/gradeschool',file.name)).size);pass('Store package verification sizes match every production file');
fs.writeFileSync(path.join(__dirname,'grade-render-results.json'),JSON.stringify({checks:tests.length,tests,sampledColours:colours.size},null,2)+'\n');
