// Real Store package, virtual disk, source-checked saves, updates and artwork migration.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),store=fs.readFileSync(path.join(root,'store.js'),'utf8'),home='/home/user/Downloads/Grade School',tests=[];
function context(badFile=null){const files=new Map(),storage=new Map(),events={},frame={contentWindow:{}},loading={classList:{add(){}}};let offline=false,failWrite=false;
 class FileReader{async readAsDataURL(blob){this.result='data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64');this.onload?.()}}
 const disk={ensureDir:async p=>files.set(p,{type:'dir'}),writeText:async(p,text)=>{if(failWrite&&p.endsWith('/game.js'))throw Error('Drive write interrupted');files.set(p,{type:'file',text,size:Buffer.byteLength(text)})},writeBlob:async(p,blob)=>files.set(p,{type:'file',blob,size:blob.size}),readText:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).text},readBlob:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).blob},getNode:async p=>files.get(p),snapshot:async()=>Object.fromEntries(files),remove:async p=>{for(const k of files.keys())if(k===p||k.startsWith(p+'/'))files.delete(k)}};
 const box={console,URL,Blob,Uint8Array,DataView,FileReader,CSS:{escape:s=>String(s)},location:{href:'https://example.com/PocketVM/'},PocketDisk:disk,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:()=>null,getElementById:()=>null},addEventListener:(k,f)=>events[k]=f,removeEventListener(){},setTimeout,clearTimeout,fetch:async url=>{if(offline)throw Error('Offline');const pathname=new URL(url,box.location.href).pathname.replace('/PocketVM/',''),data=pathname.endsWith(badFile)&&badFile?Buffer.alloc(1):fs.readFileSync(path.join(root,pathname));return{ok:true,text:async()=>data.toString('utf8'),blob:async()=>new Blob([data],{type:pathname.endsWith('.png')?'image/png':'text/plain'})}}};box.window=box;vm.runInNewContext(store,box,{filename:'store.js'});
 const ctx={queryOne:selector=>selector==='iframe'?frame:selector==='.store-game-loading'?loading:null,setWindowTitle(){},escapeHTML:s=>s,refreshFS:async()=>{},notify(){},state:{windows:new Map()},setWindowIcon(){},initDesktopGrid(){}};
 return{app:box.PocketStoreApp,files,storage,events,frame,loading,ctx,disk,setOffline:v=>offline=v,setFailWrite:v=>failWrite=v};
}
function pass(name){tests.push(name);console.log('PASS '+name)}
(async()=>{
 const c=context(),progress=[];await c.app.installGrade((bytes,total,file)=>progress.push({bytes,total,file}));assert.equal(await c.app.gradeInstalled(),true);for(const name of ['game.html','core.js','game.js'])assert.equal(c.files.get(home+'/'+name).text,fs.readFileSync(path.join(root,'store/gradeschool',name),'utf8'));assert.equal(progress.at(-1).bytes,progress.at(-1).total);assert.equal(c.files.get(home+'/name.txt').text,'Grade School');pass('Installer stores all verified code, icon and identity files with completed progress');
 c.storage.set('pocketvm.game.gradeschool',JSON.stringify({coins:123,day:5,owned:['hamster'],prefs:{sound:false},session:{mode:'career',day:5,seed:22,marks:['A+'],hinted:[],timeLeft:60,paperTime:8}}));const win={id:'grade-test',content:{},el:{querySelector:()=>null}};await c.app.buildGrade(win,{},c.ctx);const scripts=[...c.frame.srcdoc.matchAll(/src="(data:text\/javascript;base64,[^"]+)"/g)];assert.equal(scripts.length,2);for(let i=0;i<2;i++)assert.equal(Buffer.from(scripts[i][1].split(',')[1],'base64').toString('utf8'),fs.readFileSync(path.join(root,'store/gradeschool',['core.js','game.js'][i]),'utf8'));assert.ok(c.frame.srcdoc.includes('"coins":123'));assert.ok(c.frame.srcdoc.includes('"paperTime":8'));assert.ok(c.frame.srcdoc.includes('https://example.com/PocketVM/store/gradeschool/favicon-32.png'));pass('Sandbox embeds both scripts, absolute favicons and a saved unfinished class');
 const before=c.storage.get('pocketvm.game.gradeschool');c.events.message({source:{},data:{type:'pocketvm-grade-save',data:{coins:900}}});assert.equal(c.storage.get('pocketvm.game.gradeschool'),before);c.events.message({source:c.frame.contentWindow,data:{type:'pocketvm-grade-save',data:{coins:49,day:2,reputation:0,total:2,correct:5,owned:['plant','plant','fake'],equipped:{room:'room-blue'},prefs:{large:true},session:{mode:'career',day:1,seed:42,marks:Array(50).fill('A+'),hinted:[0,0,-1,200],timeLeft:999}}}});const saved=JSON.parse(c.storage.get('pocketvm.game.gradeschool'));assert.equal(saved.coins,49);assert.equal(saved.reputation,0);assert.equal(saved.correct,2);assert.deepEqual(saved.owned,['room-mint','desk-oak','stamp-red','plant']);assert.equal(saved.equipped.room,'room-mint');assert.equal(saved.session.marks.length,6);assert.deepEqual(saved.session.hinted,[0]);assert.equal(saved.session.timeLeft,60);pass('Only the owning iframe can save, and both progress and session data are bounded');
 for(const badFile of ['game.html','core.js','game.js','icon-512.png']){const b=context(badFile);await assert.rejects(()=>b.app.installGrade(),/incomplete|verification/);assert.equal(b.files.size,0)}pass('Four truncated download cases cannot leave a partial installation');
 const broken=context();broken.setFailWrite(true);await assert.rejects(()=>broken.app.installGrade(),/interrupted/);assert.equal(broken.files.size,0);pass('A write failure rolls back an incomplete installation');
 await c.disk.writeText(home+'/core.js','old code');await c.disk.writeText(home+'/name.txt','My Class');await c.app.buildGrade(win,{},c.ctx);assert.equal(c.files.get(home+'/core.js').text,fs.readFileSync(path.join(root,'store/gradeschool/core.js'),'utf8'));assert.equal(c.files.get(home+'/name.txt').text,'My Class');assert.ok(c.frame.srcdoc.includes('"coins":49'));pass('Package repair updates code while preserving the custom name and career');
 c.setOffline(true);await c.app.buildGrade(win,{},c.ctx);assert.equal([...c.frame.srcdoc.matchAll(/data:text\/javascript;base64/g)].length,2);pass('A complete installation launches offline without remote scripts');
 const savedBeforeUninstall=c.storage.get('pocketvm.game.gradeschool');await c.app.uninstallGrade();assert.equal(await c.app.gradeInstalled(),false);assert.equal(c.storage.get('pocketvm.game.gradeschool'),savedBeforeUninstall);pass('Uninstall keeps career and classroom purchases for the next installation');
 fs.writeFileSync(path.join(__dirname,'grade-package-results.json'),JSON.stringify({checks:tests.length,tests},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1});
