// Production-engine balance checks and players that spend only real match resources.
module.exports=({api,stage,plant,run,test,assert,setRandomSeed})=>{
const nativeWaves=[[4,6,8,10,8,10,20,10,20,20],[10,20,10,20,10,10,20,10,20,20],[10,20,20,30,20,20,30,20,30,30],[10,20,10,20,20,10,20,10,20,20],[10,20,20,30,20,20,30,20,30,30]];
test('Adventure uses the original 50 wave counts and zombie introduction masks',()=>{for(let w=1;w<=5;w++)for(let l=1;l<=10;l++){const c=api.levelConfig({w,l});assert.equal(c.waves,nativeWaves[w-1][l-1]);for(const id of c.enemyPool)assert.equal(api.BALANCE_REFERENCE.allowed[id][(w-1)*10+l-1],'1');const plan=api.buildWavePlan(c,{w,l});for(const wave of plan)if(!wave.final)for(const id of wave.roster)if(id!=='flag'&&!(api.BALANCE_REFERENCE.zombies[id].introduced===(w-1)*10+l&&wave.number===(['digger','balloon'].includes(id)?7:Math.floor(c.waves/2)+1)))assert.ok(wave.number>=api.BALANCE_REFERENCE.zombies[id].firstWave,id+' too early')}});
test('four world finales have their complete huge flag waves and conveyor decks',()=>{for(let w=1;w<=4;w++){const g=stage(w,10);assert.equal(g.wavePlan.length,nativeWaves[w-1][9]);assert.equal(g.wavePlan.filter(x=>x.huge).length,w===3?3:2);assert.ok(g.wavePlan.filter(x=>x.huge).every(x=>x.roster.includes('flag')));assert.equal(g.wavePlan.at(-1).final,true);assert.equal(g.boss,null);assert.ok(api.conveyorRecipe().length>=7);assert.ok(g.musicKey==='bossA'||g.musicKey==='bossB')}});
test('all 49 seed costs and recharge times match the original profiles',()=>{for(const p of api.PLANTS){const reference=api.BALANCE_REFERENCE.plants[p.id];assert.equal(p.cost,reference.cost,p.id);assert.equal(p.cool,reference.cool,p.id)}assert.equal(api.PLANT.cherrybomb.cool,50);assert.equal(api.PLANT.plantern.cool,30);assert.equal(api.PLANT.gatlingpea.cool,50)});
test('waves allow at least four seconds and speed up only after damage',()=>{const g=stage(1,6);g.grace=0;api.startNextWave();api.updateTasks(.1);const first=g.waveIndex;api.updateWaveBattle(3.9);assert.equal(g.waveIndex,first);g.zombies[0].hp=50;api.updateWaveBattle(.2);assert.ok(g.spawnTimer<=2);api.updateWaveBattle(2.1);assert.equal(g.waveIndex,first+1)});
test('huge waves receive a 7.5-second warning, and pause freezes it',()=>{const g=stage(1,10);g.grace=0;g.waveIndex=9;g.waveAge=5;g.spawnTimer=0;api.updateWaveBattle(.01);assert.equal(g.waveWarning,7.5);api.setPaused(true);run(4);assert.equal(g.waveWarning,7.5);api.setPaused(false);api.updateWaveBattle(7.4);assert.equal(g.waveIndex,9);api.updateWaveBattle(.11);assert.equal(g.waveIndex,10);assert.ok(g.pendingWaveSpawns>1)});
test('wave spawning consumes the opening basics and varies legal lanes',()=>{for(let w=1;w<=5;w++){const g=stage(w,9);g.grace=0;const count=w===3?3:w>=4?2:4;for(let i=0;i<count;i++){api.startNextWave();api.updateTasks(10)}assert.equal(g.openingBasicLeft,0);assert.ok(g.zombies.slice(0,count).every(z=>z.id==='basic'));for(let i=2;i<g.spawnHistory.length;i++)assert.ok(!g.spawnHistory.slice(i-2,i).includes(g.spawnHistory[i]))}});
test('Fog has no gravestones; Night graves emerge with the final flag only',()=>{let g=stage(4,10);assert.ok(g.cells.flat().every(c=>!c.grave));g=stage(2,10);assert.equal(g.cells.flat().filter(c=>c.grave).length,13);g.grace=0;g.waveIndex=g.wavePlan.length-1;api.startNextWave();const planned=g.wavePlan.at(-1).roster.length;api.updateTasks(4);assert.equal(g.zombies.length,planned+13);assert.equal(g.running,true)});
test('Grave Buster takes 4.5 seconds and cannot stack on its occupied grave',()=>{const g=stage(2,6);let r,c;for(let rr=0;rr<g.rows;rr++)for(let cc=0;cc<9;cc++)if(g.cells[rr][cc].grave){r=rr;c=cc}plant('gravebuster',r,c);assert.equal(api.canPlant('gravebuster',r,c),false);api.updatePlants(4.4);assert.equal(g.cells[r][c].grave,true);api.updatePlants(.11);assert.equal(g.cells[r][c].grave,false);assert.equal(g.cells[r][c].main,null)});
test('pool final ambush is queued and blocks premature victory',()=>{const g=stage(3,10);g.grace=0;g.waveIndex=g.wavePlan.length-1;api.startNextWave();api.updateSpawns(.01);assert.equal(g.running,true);const planned=g.wavePlan.at(-1).roster.length;api.updateTasks(10);assert.equal(g.zombies.length,planned+3);assert.ok(g.zombies.filter(z=>z.x<api.cx(8)).length>=3)});
test('conveyors stop overfilling and discard unusable Grave Buster weight',()=>{let g=stage(2,10);g.cells.flat().forEach(c=>c.grave=false);g.conveyorIssued=20;for(let i=0;i<100;i++)assert.notEqual(api.nextConveyorSeed(),'gravebuster');g=stage(1,10);run(29);assert.ok(g.conveyor.length>=6&&g.conveyor.length<=10);const before=g.conveyor.length;api.setPaused(true);run(5);assert.equal(g.conveyor.length,before)});
test('Bungee Blitz drops retain the planned zombie and wave health',()=>{const g=stage(5,5);g.grace=0;g.openingBasicLeft=0;api.startNextWave();api.updateTasks(.2);assert.ok(g.pendingSpawns>0);api.updateTasks(1);assert.equal(g.zombies[0].fromWave,1);assert.equal(api.currentWaveHealth(),g.waveHealthStart)});
test('Zomboni leaves temporary unplantable ice and Jalapeno clears its lane',()=>{const g=stage(3,9);api.spawnZombie('zomboni',0,api.cx(5));api.updateCombatTerrain(.05);assert.equal(api.canPlant('peashooter',0,7),false);assert.equal(api.canPlant('peashooter',0,2),true);api.doInstant(api.PLANT.jalapeno,0,2);assert.equal(api.canPlant('peashooter',0,7),true)});
test('Gloom Shroom sends four 20-damage pulses and respects allies',()=>{const g=stage(2,9);plant('fumeshroom',2,2);const p=plant('gloomshroom',2,2),z=api.spawnZombie('basic',2,api.cx(3)),friend=api.spawnZombie('basic',1,api.cx(3));friend.friendly=true;p.timer=0;api.updatePlants(.01);api.updateTasks(.7);assert.equal(z.hp,120);assert.equal(friend.hp,200)});
test('Chomper has a 42-second chew and takes only small bites from Gargantuar',()=>{stage();let p=plant('chomper',2,3),z=api.spawnZombie('basic',2,api.cx(3)+35);api.updatePlants(.01);assert.equal(z.dead,true);assert.equal(p.chew,42);stage(5,9);p=plant('chomper',2,3);z=api.spawnZombie('gargantuar',2,api.cx(3)+35);api.updatePlants(.01);assert.equal(z.hp,2960);assert.equal(p.chew,1.5)});
test('Spikerock withstands nine vehicles, and Gargantuar winds up before smashing',()=>{let g=stage(3,9);plant('spikeweed',0,3);let p=plant('spikerock',0,3);for(let i=0;i<8;i++){api.spawnZombie('zomboni',0,api.cx(3));api.updatePlants(.01)}assert.equal(p.hp,50);api.spawnZombie('zomboni',0,api.cx(3));api.updatePlants(.01);assert.equal(p.hp,0);g=stage(5,9);p=plant('wallnut',2,2);api.spawnZombie('gargantuar',2,api.cx(2));api.updateZombies(1.4);assert.equal(p.hp,4000);api.updateZombies(.11);assert.equal(p.hp,0)});
test('slowing zombies halves both their movement and their bite damage',()=>{stage();const p=plant('wallnut',2,3),z=api.spawnZombie('basic',2,api.cx(3));api.hurtZombie(z,1,{slow:.5});api.updateZombies(1);assert.equal(p.hp,3950)});
test('boss mushrooms are awake, head phases gate damage, and both ball counters work',()=>{let g=stage(5,10);assert.equal(g.boss.visible,false);assert.equal(g.boss.hp,40000);const health=g.boss.hp;api.doInstant(api.PLANT.jalapeno,1,1);assert.equal(g.boss.hp,health);api.bossSetPhase('exposed');api.doInstant(api.PLANT.jalapeno,1,1);assert.equal(g.boss.hp,health-1800);g.bossThreat={kind:'fire',row:2,x:1000,time:2};g.conveyor=['iceshroom'];g.selected={id:'iceshroom',conveyor:0,free:true};assert.equal(api.placePlant('iceshroom',0,0,true),true);assert.equal(g.cells[0][0].main,null);assert.equal(g.bossThreat,null);g.bossThreat={kind:'ice',row:2,x:1000,time:2};api.doInstant(api.PLANT.jalapeno,1,0);assert.ok(g.bossThreat);api.doInstant(api.PLANT.jalapeno,2,0);assert.equal(g.bossThreat,null)});
test('boss rolling balls destroy tile layers and pause stops attack clocks',()=>{const g=stage(5,10);const p=plant('cabbagepult',2,1);g.bossThreat={kind:'fire',row:2,x:api.cx(1)+5,time:0,rolling:true};api.setPaused(true);const x=g.bossThreat.x;run(2);assert.equal(g.bossThreat.x,x);api.setPaused(false);api.updateBoss(.01);assert.equal(g.cells[2][1].main,null);assert.equal(g.cells[2][1].base,null);assert.equal(p.hp,300)});
test('Catapult waits until it reaches the lawn, deals 75 damage and has finite ammunition',()=>{const g=stage(5,9);const p=plant('sunflower',2,0),z=api.spawnZombie('catapult',2);api.updateZombies(.1);assert.equal(p.hp,300);z.x=api.cx(6);api.updateZombies(.1);assert.equal(p.hp,225);assert.equal(z.catapultShots,19);plant('umbrellaleaf',1,1);api.updateZombies(3.6);assert.equal(p.hp,225);z.catapultShots=0;const x=z.x;api.updateZombies(.1);assert.ok(z.x<x)});
test('Pogo jumps take simulation time and can be frozen mid jump',()=>{const g=stage(4,9);plant('wallnut',0,3);const z=api.spawnZombie('pogo',0,api.cx(3));api.updateZombies(.01);assert.equal(z.x,api.cx(3));assert.ok(z.jumpTime>0);api.updateZombies(.45);assert.ok(z.x<api.cx(3)&&z.x>api.cx(2));const x=z.x;z.freeze=1;api.updateZombies(.4);assert.equal(z.x,x)});
test('tiny zombies retain normal movement and bite speed with quarter health',()=>{const g=stage(3,5),z=api.spawnZombie('basic',0,api.cx(3));assert.equal(z.hp,50);assert.equal(z.speed,api.ZOMBIE.basic.speed);assert.equal(z.bite,1);assert.equal(z.scale,.5)});
test('Bungee thefts are assigned to flag waves and leave roof supports intact',()=>{const g=stage(5,5);assert.equal(g.wavePlan[9].roster.filter(id=>id==='bungee').length,5);assert.equal(g.wavePlan.at(-1).roster.filter(id=>id==='bungee').length>=5,true);g.grace=0;plant('chomper',0,1);api.updateSpecial(20);assert.equal(g.tasks.length,0);const old=api.spawnZombie('basic',0);old.dead=true;g.waveIndex=9;api.startNextWave();api.updateTasks(3);assert.equal(g.bungeeTargets.size,1);api.updateTasks(2);assert.equal(g.cells[0][1].main,null);assert.equal(g.cells[0][1].base.id,'flowerpot')});

function play(w,l,seed,limit=1200){
 setRandomSeed(seed);api.save={...api.defaultSave(),levelUnlocked:(w-1)*10+l,completed:Array.from({length:(w-1)*10+l-1},(_,i)=>Math.floor(i/10)+1+'-'+(i%10+1))};
 const decks={1:['sunflower','peashooter','snowpea','wallnut','potatomine','cherrybomb'],2:['sunshroom','puffshroom','fumeshroom','scaredyshroom','gravebuster','doomshroom','iceshroom'],3:['sunflower','lilypad','peashooter','snowpea','tanglekelp','squash','jalapeno','tallnut'],4:['sunshroom','puffshroom','lilypad','seashroom','scaredyshroom','blover','squash','starfruit'],5:['sunflower','flowerpot','kernelpult','melonpult','squash','jalapeno','umbrellaleaf','potatomine','cherrybomb']};
 api.startStage({w,l,key:w+'-'+l,idx:(w-1)*10+l},decks[w]);const g=api.game;const startSun=g.sun;let spent=0,placements=0,counters=0;const water=r=>g.rows===6&&(r===2||r===3);
 const enemies=()=>g.zombies.filter(z=>!z.dead&&!z.friendly);
 const rowRisk=r=>enemies().filter(z=>z.row===r).reduce((n,z)=>n+(z.hp+z.armor)*(1+Math.max(0,8-(z.x-api.cx(0))/94)),0);
 const rows=()=>g.cfg.activeRows.slice().sort((a,b)=>rowRisk(b)-rowRisk(a)||a-b);
 function use(id,r,c,index=null){if(!api.canPlant(id,r,c))return false;const free=index!==null;if(!free&&(!g.seeds.includes(id)||(g.seedCd[id]||0)>0||g.sun<api.PLANT[id].cost))return false;g.selected=free?{id,conveyor:index,free:true}:{id,seed:id};const before=g.sun;const ok=api.placePlant(id,r,c,free);if(ok){spent+=before-g.sun;placements++}return ok}
 function tiles(cols){return cols.flatMap(c=>rows().map(r=>({r,c}))).filter(({r,c})=>api.canPlant('flowerpot',r,c)||!g.cells[r][c].main)}
 function targetCell(z,back=0){const c=Math.max(0,Math.min(8,Math.floor((z.x-api.cx(0))/94)-back));for(const cc of [c,c-1,c+1,2,1,0,3,4,5,6,7,8])if(cc>=0&&cc<9&&!g.cells[z.row][cc].main&&!g.cells[z.row][cc].grave&&(!water(z.row)||g.cells[z.row][cc].base)&& (w!==5||g.cells[z.row][cc].base))return{r:z.row,c:cc};return null}
 function emergency(id,index=null){const zs=enemies().sort((a,b)=>a.x-b.x);const z=zs.find(z=>z.x<api.cx(4)||(z.eating&&g.cells[z.row].some(c=>c.main?.id==='chomper'&&c.main.chew>0))||z.hp+z.armor>900||zs.filter(q=>Math.abs(q.row-z.row)<=1&&Math.abs(q.x-z.x)<120).length>=3);if(!z)return false;let t=targetCell(z,id==='squash'||id==='chomper'||id==='tanglekelp'?1:0);if(['cherrybomb','doomshroom','iceshroom'].includes(id)){const nearby=[];for(const r of [z.row,z.row-1,z.row+1])for(let c=0;c<9;c++)if(r>=0&&r<g.rows&&api.canPlant(id,r,c)&&Math.hypot(api.cx(c)-z.x,api.cy(r)-api.cy(z.row))<140)nearby.push({r,c,d:Math.hypot(api.cx(c)-z.x,api.cy(r)-api.cy(z.row))});nearby.sort((a,b)=>a.d-b.d);t=nearby[0]||t}return t&&use(id,t.r,t.c,index)}
 function conveyorAction(id,i){
  if(id==='iceshroom'&&g.bossThreat?.kind==='fire'){for(const t of tiles([0,1,2,3]))if(use(id,t.r,t.c,i)){counters++;return true}}
  if(id==='jalapeno'&&g.bossThreat?.kind==='ice'){for(let c=0;c<9;c++)if(use(id,g.bossThreat.row,c,i)){counters++;return true}}
  if(id==='iceshroom')return enemies().length>=6&&emergency(id,i);
  if(g.cfg.mode==='bungee'&&id==='chomper'){for(const c of [4,5,6,3,7,2,1,0])for(const r of rows())if(use(id,r,c,i))return true;return false}
  if(['jalapeno','cherrybomb','doomshroom','squash','tanglekelp','chomper'].includes(id))return emergency(id,i);
  if(id==='blover')return enemies().some(z=>z.air)&&use(id,0,0,i)||enemies().some(z=>z.air)&&tiles([1,2,3,4]).some(t=>use(id,t.r,t.c,i));
  if(id==='gravebuster'){for(let r=0;r<g.rows;r++)for(let c=0;c<9;c++)if(g.cells[r][c].grave&&use(id,r,c,i))return true;return false}
  if(id==='lilypad'){for(const c of w===4?[3,4,2,1,5,0,6,7,8]:[1,3,5,2,4,0,6,7,8])for(const r of [2,3])if(use(id,r,c,i))return true;return false}
  if(id==='flowerpot'){for(const t of tiles([3,4,5,6,1,2,0,7,8]))if(use(id,t.r,t.c,i))return true;return false}
  if(id==='magnetshroom'){const lawn=g.cells.flat().filter(c=>c.main?.id===id).length;if(lawn>=4)return false;for(const r of [1,4,0,5,2,3])for(const c of [3,4,2,5])if(r<g.rows&&use(id,r,c,i))return true;return false}
  if(id==='torchwood'){for(const c of [4,5,6])for(const r of rows())if(g.cells.slice(Math.max(0,r-1),r+2).some(row=>row.some(cell=>cell.main?.id==='threepeater'))&&use(id,r,c,i))return true;return false}
  if(id==='pumpkin'){for(const c of [4,3,5,2,1,6,0,7])for(const r of rows())if(g.cells[r][c].main&&use(id,r,c,i))return true;return false}
  if(['wallnut','tallnut','pumpkin','hypnoshroom','spikeweed'].includes(id)){for(const c of [6,5,7,4,3,2])for(const r of rows())if(use(id,r,c,i))return true;return false}
  const rr=rows().sort((a,b)=>g.cells[a].filter(c=>c.main&&['shooter','lobber','three','star','fume'].includes(api.PLANT[c.main.id].role)).length-g.cells[b].filter(c=>c.main&&['shooter','lobber','three','star','fume'].includes(api.PLANT[c.main.id].role)).length||rowRisk(b)-rowRisk(a));
  if(id==='cactus')rr.sort((a,b)=>Number(g.cells[a].some(c=>c.main?.id==='cactus'))-Number(g.cells[b].some(c=>c.main?.id==='cactus'))||rowRisk(b)-rowRisk(a));
  if(id==='splitpea')rr.sort((a,b)=>Number(g.cells[a].some(c=>c.main?.id==='splitpea'))-Number(g.cells[b].some(c=>c.main?.id==='splitpea'))||rowRisk(b)-rowRisk(a));
  if(g.cfg.mode==='tiny'&&id==='peashooter')rr.sort((a,b)=>Number(g.cells[a].some(c=>c.main?.id==='peashooter'))-Number(g.cells[b].some(c=>c.main?.id==='peashooter'))||Number(water(b))-Number(water(a))||rowRisk(b)-rowRisk(a));
  if(id==='threepeater')rr.sort((a,b)=>[1,4,2,3,0,5].indexOf(a)-[1,4,2,3,0,5].indexOf(b));
  for(const c of id==='starfruit'?[3,4,2,5,1,6,0,7]:id==='puffshroom'||id==='seashroom'?[5,4,6,3,7,2,1,0]:[1,2,0,3,4,5,6,7])for(const r of rr)if(use(id,r,c,i))return true;return false;
 }
 function normalAction(){
  const zs=enemies();
  if(zs.some(z=>z.air)){for(const t of tiles([0,1,2,3]))if(use('blover',t.r,t.c))return}
  for(const id of ['squash','tanglekelp','cherrybomb','jalapeno','doomshroom'])if(emergency(id))return;
  const rs=rows(),attack=id=>g.cells.flat().filter(c=>c.main?.id===id).length;
  if(w===4)for(const c of [5,4,6])for(const r of [2,3])if(use('seashroom',r,c))return;
  if(w===2||w===4){for(const c of [5,4,6,3])for(const r of rs)if(use('puffshroom',r,c))return}
  const shooter=w===1?'peashooter':w===2?'fumeshroom':w===3?'peashooter':w===4?'scaredyshroom':'kernelpult';
  for(const r of rs){const z=zs.find(z=>z.row===r);if(z&&!g.cells[r].some(c=>c.main&&['shooter','three','lobber','star','fume'].includes(api.PLANT[c.main.id].role))){for(const c of [2,1,3,0])if(use(shooter,r,c))return}}
  if((w===1||w===5)&&g.elapsed<100)for(const r of rs){const z=zs.find(z=>z.row===r&&z.x>api.cx(5)&&!g.cells[r].some(c=>c.main?.id==='potatomine'));if(z&&use('potatomine',r,w===5?2:4))return}
  const income=w===2||w===4?'sunshroom':'sunflower',desired=Math.min(w===5?8:10,Math.floor(g.elapsed/12)+3);
  if(attack(income)<desired)for(const c of [0,1])for(const r of rs.filter(r=>!water(r)&&!(w===5&&c===1&&[1,3].includes(r))))if(use(income,r,c))return;
  if(g.rows===6)for(const c of [2,3])for(const r of [2,3])if(use('lilypad',r,c))return;
  if(w===5){for(const c of [3,4])for(const r of rs)if(use('flowerpot',r,c))return}
  if(w===5&&g.elapsed>25)for(const r of [1,3])for(const c of [1])if(use('umbrellaleaf',r,c))return;
  for(const c of [2,3,4,5])for(const r of rs)if(use(w===5&&attack('kernelpult')>=8?'melonpult':(w===1||w===3)&&attack('peashooter')>=5?'snowpea':w===4&&attack('scaredyshroom')>=6?'starfruit':shooter,r,c))return;
  if(w===2)for(const c of [4,5,6])for(const r of rs)if(use('gravebuster',r,c))return;
  if(g.cells.flat().filter(c=>c.main&&['shooter','three','lobber','star','fume'].includes(api.PLANT[c.main.id].role)).length>=g.rows*2&&g.cells.filter(row=>row.some(c=>c.main&&['shooter','three','lobber','star','fume'].includes(api.PLANT[c.main.id].role))).length===g.rows)for(const c of [6,5,7])for(const r of rs)if(use(w===3?'tallnut':'wallnut',r,c))return;
  if(w===3)for(const r of rs.filter(r=>!water(r)))for(const c of [6,7,5])if(use('spikeweed',r,c))return;
 }
 for(let t=0;t<limit*20&&g.running;t++){
  for(const sun of [...g.suns])api.collectSun(sun);
  if(t%5===0){if(g.cfg.mode==='bowling'){const z=enemies().sort((a,b)=>a.x-b.x)[0];if(z)api.handleCanvas(api.cx(0),api.cy(z.row))}else if(g.cfg.mode==='whack'){for(const z of enemies())for(let i=0;i<3&&!z.dead;i++)api.handleCanvas(z.x,api.cy(z.row))}else if(['conveyor','storm','boss','bungee','tiny'].includes(g.cfg.mode)){for(let i=0;i<g.conveyor.length;i++)if(conveyorAction(g.conveyor[i],i))break}else normalAction()}
  api.update(.05);
  if(process.env.PVZ_BALANCE_TRACE===w+'-'+l&&t%400===0)console.log('TRACE',JSON.stringify({t:Math.round(g.elapsed),sun:Math.floor(g.sun),wave:g.waveIndex,lawn:g.cells.map(row=>row.map(c=>c.main?.id||'.').join(',')),z:enemies().map(z=>[z.id,z.row,Math.round(z.x),Math.round(z.hp+z.armor)])}));
 }
 if(process.env.PVZ_BALANCE_TRACE===w+'-'+l)console.log('ENDTRACE',JSON.stringify({lawn:g.cells.map(row=>row.map(c=>c.main?.id||'.').join(',')),z:enemies().map(z=>[z.id,z.row,Math.round(z.x),Math.round(z.hp+z.armor)]),bank:g.conveyor}));
 const result={level:w+'-'+l,seed,won:api.save.completed.includes(w+'-'+l),seconds:Math.round(g.elapsed),placements,spent,startSun,remainingSun:Math.floor(g.sun),mowersUsed:g.cleaners.filter(x=>!x).length,counters,waves:g.waveIndex,zombies:g.spawned};return result;
}
const results=[];
for(const [w,l] of [[1,3],[1,9],[2,9],[3,9],[4,9],[5,9],[1,5],[2,5],[1,10],[2,10],[3,10],[4,10],[5,10]]){
 test('normal-resource full match '+w+'-'+l,()=>{const result=play(w,l,(w===3&&l===9||w===5&&l===9?732:730)+w*100+l);results.push(result);console.log('MATCH',JSON.stringify(result));assert.equal(result.won,true,JSON.stringify(result))});
}
if(process.env.PVZ_BALANCE_STRESS){for(const [w,l] of [[3,5],[5,5]])console.log('STRESS',JSON.stringify(play(w,l,730+w*100+l)))}
if(process.env.PVZ_QA_DIR){require('node:fs').mkdirSync(process.env.PVZ_QA_DIR,{recursive:true});require('node:fs').writeFileSync(require('node:path').join(process.env.PVZ_QA_DIR,'pvz-balance-matches.json'),JSON.stringify(results,null,2)+'\n')}
};
