const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),native=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas'),root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'store/stickwar/game.html'),'utf8'),els=new Map(),frames=[],messages=[],events={},tests=[];let active;
function el(id){if(els.has(id))return els.get(id);const e=id==='field'?native.createCanvas(1280,800):{};Object.assign(e,{hidden:false,style:{},dataset:{},textContent:'',innerHTML:'',listeners:{},type:'',classList:{toggle(){}},addEventListener(t,f){this.listeners[t]=f},querySelector(s){return el(id+':'+s)},querySelectorAll(){return[]},focus(){},setPointerCapture(){},getBoundingClientRect(){return{left:0,top:0,width:104,height:104}}});els.set(id,e);return e;}
for(const[,tag,id]of html.matchAll(/(<[^>]*\bid="([^"]+)"[^>]*>)/g))el(id).hidden=/\bhidden\b/.test(tag);
const box={console,Math,Date,JSON,Map,Set,Array,innerWidth:1280,innerHeight:800,devicePixelRatio:1,localStorage:{getItem:()=>null,setItem(){}},parent:{postMessage:m=>messages.push(m)},requestAnimationFrame:f=>frames.push(f),addEventListener:(t,f)=>events[t]=f,document:{hidden:false,getElementById:el,querySelectorAll:()=>[],addEventListener:(t,f)=>events[t]=f}};box.window=box;vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(root,'store/stickwar/core.js'),'utf8'),box);const Orig=box.StickCore.Battle;box.StickCore.Battle=class extends Orig{constructor(opts){super(opts);active=this;}};vm.runInContext(fs.readFileSync(path.join(root,'store/stickwar/game.js'),'utf8'),box);assert.equal(el('error').hidden,true);assert.ok(messages.some(m=>m.type==='pocketvm-stick-ready'));let tick=1;const run=(n,ms=16.667)=>{for(let i=0;i<n;i++)frames.shift()(tick+=ms)};function check(n,f){f();tests.push(n);console.log('PASS '+n)}
check('Production game boots, renders original scenery and opens the campaign',()=>{run(2);fs.writeFileSync(path.join(__dirname,'stick-menu-canvas.png'),el('field').toBuffer('image/png'));el('campaign').listeners.click();assert.equal(el('campaign-screen').hidden,false);assert.ok(el('missions').innerHTML.includes('First Banner'));assert.equal((el('missions').innerHTML.match(/ disabled/g)||[]).length,11);});
check('Campaign briefing launches paid unit training and actual strategy simulation',()=>{el('missions').listeners.click({target:{closest:()=>({dataset:{mission:'1'}})}});assert.equal(el('brief').hidden,false);el('begin').listeners.click();assert.equal(el('hud').hidden,false);assert.equal(el('brief').hidden,true);const before=active.gold[0];el('training').listeners.click({target:{closest:()=>({dataset:{train:'miner'},disabled:false})}});assert.equal(active.gold[0],before-100);run(210);assert.ok(active.units.filter(u=>u.team===0&&u.id==='miner').length>=3);});
check('Pause, tab visibility and held inputs freeze gameplay without hidden progress',()=>{el('pause').listeners.click();const t=active.time;run(90);assert.equal(active.time,t);el('resume').listeners.click();run(20);assert.ok(active.time>t);box.document.hidden=true;events.visibilitychange();const hiddenTime=active.time;run(60);assert.equal(active.time,hiddenTime);box.document.hidden=false;el('resume').listeners.click();});
check('Touch selection, direct movement and release use production handlers',()=>{const u=active.units.find(u=>u.team===0&&u.id==='sword'),v=JSON.parse(el('field').dataset.viewport),p={pointerId:3,clientX:u.x*v.scale,clientY:v.ground+(u.y-35)*v.scale};el('field').listeners.pointerdown(p);el('field').listeners.pointerup(p);assert.equal(active.selected,u.uid);assert.equal(el('direct-controls').hidden,false);const x=u.x;events.keydown({code:'KeyD',target:{tagName:'BODY'},preventDefault(){}});run(50);assert.ok(u.x>x+30);events.keyup({code:'KeyD'});el('release').listeners.click();assert.equal(active.selected,null);assert.equal(el('direct-controls').hidden,true);});
check('Army attack orders, renderer and victory settle a real campaign round',()=>{el('commands').listeners.click({target:{closest:()=>({dataset:{command:'attack'}})}});assert.equal(active.commands[0],'attack');for(let i=0;i<9000&&!active.done;i++){if(i%100===0)el('training').listeners.click({target:{closest:()=>({dataset:{train:'sword'},disabled:false})}});run(1,33.334);if(i===1100)fs.writeFileSync(path.join(__dirname,'stick-battle-canvas.png'),el('field').toBuffer('image/png'));}assert.ok(active.done);assert.equal(el('result').hidden,false);assert.ok(messages.some(m=>m.type==='pocketvm-stick-save'));});
check('Returning to the menu restores the campaign, armoury and modes',()=>{el('result-home').listeners.click();assert.equal(el('menu').hidden,false);el('forge').listeners.click();assert.equal(el('forge-screen').hidden,false);assert.equal((el('upgrades').innerHTML.match(/class="upgrade"/g)||[]).length,8);});
fs.writeFileSync(path.join(__dirname,'stick-render-results.json'),JSON.stringify({checks:tests.length,tests},null,2)+'\n');
