// Real Store package, virtual disk, source-checked saves, updates and artwork migration.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),store=fs.readFileSync(path.join(root,'store.js'),'utf8'),home='/home/user/Downloads/Stick War',tests=[];
function context(badFile=null){const files=new Map(),storage=new Map(),events={},frame={contentWindow:{}},loading={classList:{add(){}}};let offline=false,failWrite=false;
 class FileReader{async readAsDataURL(blob){this.result='data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64');this.onload?.()}}
 const disk={ensureDir:async p=>files.set(p,{type:'dir'}),writeText:async(p,text)=>{if(failWrite&&p.endsWith('/game.js'))throw Error('Drive write interrupted');files.set(p,{type:'file',text,size:Buffer.byteLength(text)})},writeBlob:async(p,blob)=>files.set(p,{type:'file',blob,size:blob.size}),readText:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).text},readBlob:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).blob},getNode:async p=>files.get(p),snapshot:async()=>Object.fromEntries(files),remove:async p=>{for(const k of files.keys())if(k===p||k.startsWith(p+'/'))files.delete(k)}};
 const box={console,URL,Blob,Uint8Array,DataView,FileReader,CSS:{escape:s=>String(s)},location:{href:'https://example.com/PocketVM/'},PocketDisk:disk,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:()=>null,getElementById:()=>null},addEventListener:(k,f)=>events[k]=f,removeEventListener(){},setTimeout,clearTimeout,fetch:async url=>{if(offline)throw Error('Offline');const pathname=new URL(url,box.location.href).pathname.replace('/PocketVM/',''),data=pathname.endsWith(badFile)&&badFile?Buffer.alloc(1):fs.readFileSync(path.join(root,pathname));return{ok:true,text:async()=>data.toString('utf8'),blob:async()=>new Blob([data],{type:pathname.endsWith('.png')?'image/png':pathname.endsWith('.mp3')?'audio/mpeg':'text/plain'})}}};box.window=box;vm.runInNewContext(store,box,{filename:'store.js'});
 const ctx={queryOne:selector=>selector==='iframe'?frame:selector==='.store-game-loading'?loading:null,setWindowTitle(){},escapeHTML:s=>s,refreshFS:async()=>{},notify(){},state:{windows:new Map()},setWindowIcon(){},initDesktopGrid(){}};
 return{app:box.PocketStoreApp,files,storage,events,frame,loading,ctx,disk,setOffline:v=>offline=v,setFailWrite:v=>failWrite=v};
}
function pass(name){tests.push(name);console.log('PASS '+name)}
(async()=>{
 const c=context(),progress=[];await c.app.installStick((bytes,total,file)=>progress.push({bytes,total,file}));assert.equal(await c.app.stickInstalled(),true);for(const name of ['game.html','core.js','game.js'])assert.equal(c.files.get(home+'/'+name).text,fs.readFileSync(path.join(root,'store/stickwar',name),'utf8'));assert.equal(progress.at(-1).bytes,progress.at(-1).total);pass('Real Store installs every verified game file and original artwork');
 c.storage.set('pocketvm.game.stickwar',JSON.stringify({stars:[3,2],upgrades:{miner:2},prefs:{sound:false}}));const win={id:'stick-test',content:{},el:{querySelector:()=>null}};await c.app.buildStick(win,{},c.ctx);const scripts=[...c.frame.srcdoc.matchAll(/src="(data:text\/javascript;base64,[^"]+)"/g)];assert.equal(scripts.length,2);for(let i=0;i<2;i++)assert.equal(Buffer.from(scripts[i][1].split(',')[1],'base64').toString('utf8'),fs.readFileSync(path.join(root,'store/stickwar',i===0?'core.js':'game.js'),'utf8'));assert.ok(c.frame.srcdoc.includes('"points":2'));assert.ok(c.frame.srcdoc.includes('https://example.com/PocketVM/store/stickwar/favicon-32.png'));pass('Sandbox embeds production scripts, saved upgrades and matching favicons');
 const old=c.storage.get('pocketvm.game.stickwar');c.events.message({source:{},data:{type:'pocketvm-stick-save',data:{stars:Array(12).fill(3)}}});assert.equal(c.storage.get('pocketvm.game.stickwar'),old);for(const raw of [{stars:[3],upgrades:{miner:1},points:999,prefs:{map:'fake',difficulty:'fake'}},{stars:Array(12).fill(99),upgrades:{giant:99},bestWave:Infinity},null,{upgrades:{mage:3},wins:-1}]){c.events.message({source:c.frame.contentWindow,data:{type:'pocketvm-stick-save',data:raw}});assert.deepEqual(JSON.parse(c.storage.get('pocketvm.game.stickwar')),require('../store/stickwar/core.js').clean(raw||{}));}pass('Source-checked saves repair invalid progress and match the game sanitizer');
 for(const file of ['game.html','core.js','game.js','icon-512.png']){const b=context(file);await assert.rejects(()=>b.app.installStick(),/incomplete|verification/);assert.equal(b.files.size,0);}pass('Truncated downloads cannot create a partial installation');
 const broken=context();broken.setFailWrite(true);await assert.rejects(()=>broken.app.installStick(),/interrupted/);assert.equal(broken.files.size,0);pass('Interrupted writes roll back the game package');
 await c.disk.writeText(home+'/core.js','old code');await c.disk.writeText(home+'/name.txt','My Army');const saved=c.storage.get('pocketvm.game.stickwar');await c.app.buildStick(win,{},c.ctx);assert.equal(c.files.get(home+'/core.js').text,fs.readFileSync(path.join(root,'store/stickwar/core.js'),'utf8'));assert.equal(c.files.get(home+'/name.txt').text,'My Army');assert.equal(c.storage.get('pocketvm.game.stickwar'),saved);pass('Package repair preserves custom names and campaign progress');
 c.setOffline(true);await c.app.buildStick(win,{},c.ctx);assert.equal([...c.frame.srcdoc.matchAll(/data:text\/javascript;base64/g)].length,2);pass('An installed battle starts without network dependencies');const before=c.storage.get('pocketvm.game.stickwar');await c.app.uninstallStick();assert.equal(await c.app.stickInstalled(),false);assert.equal(c.storage.get('pocketvm.game.stickwar'),before);pass('Uninstall preserves campaign, armoury and survival saves');
 fs.writeFileSync(path.join(__dirname,'stick-package-results.json'),JSON.stringify({checks:tests.length,tests},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1});
