// Real Store package, virtual disk, source-checked saves, updates and artwork migration.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),store=fs.readFileSync(path.join(root,'store.js'),'utf8'),home='/home/user/Downloads/Wobble Bay',tests=[];
function context(badFile=null){const files=new Map(),storage=new Map(),events={},frame={contentWindow:{}},loading={classList:{add(){}}};let offline=false,failWrite=false;
 class FileReader{async readAsDataURL(blob){this.result='data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64');this.onload?.()}}
 const disk={ensureDir:async p=>files.set(p,{type:'dir'}),writeText:async(p,text)=>{if(failWrite&&p.endsWith('/game.js'))throw Error('Drive write interrupted');files.set(p,{type:'file',text,size:Buffer.byteLength(text)})},writeBlob:async(p,blob)=>files.set(p,{type:'file',blob,size:blob.size}),readText:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).text},readBlob:async p=>{if(!files.has(p))throw Error('Missing');return files.get(p).blob},getNode:async p=>files.get(p),snapshot:async()=>Object.fromEntries(files),remove:async p=>{for(const k of files.keys())if(k===p||k.startsWith(p+'/'))files.delete(k)}};
 const box={console,URL,Blob,Uint8Array,DataView,FileReader,CSS:{escape:s=>String(s)},location:{href:'https://example.com/PocketVM/'},PocketDisk:disk,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:()=>null,getElementById:()=>null},addEventListener:(k,f)=>events[k]=f,removeEventListener(){},setTimeout,clearTimeout,fetch:async url=>{if(offline)throw Error('Offline');const pathname=new URL(url,box.location.href).pathname.replace('/PocketVM/',''),data=pathname.endsWith(badFile)&&badFile?Buffer.alloc(1):fs.readFileSync(path.join(root,pathname));return{ok:true,text:async()=>data.toString('utf8'),blob:async()=>new Blob([data],{type:pathname.endsWith('.png')?'image/png':'text/plain'})}}};box.window=box;vm.runInNewContext(store,box,{filename:'store.js'});
 const ctx={queryOne:selector=>selector==='iframe'?frame:selector==='.store-game-loading'?loading:null,setWindowTitle(){},escapeHTML:s=>s,refreshFS:async()=>{},notify(){},state:{windows:new Map()},setWindowIcon(){},initDesktopGrid(){}};
 return{app:box.PocketStoreApp,files,storage,events,frame,loading,ctx,disk,setOffline:v=>offline=v,setFailWrite:v=>failWrite=v};
}
function pass(name){tests.push(name);console.log('PASS '+name)}
(async()=>{
 const c=context(),progress=[];await c.app.installWobble((bytes,total,file)=>progress.push({bytes,total,file}));assert.equal(await c.app.wobbleInstalled(),true);for(const name of ['game.html','engine.js','game.js','three.min.js','THREE-LICENSE.txt'])assert.equal(c.files.get(home+'/'+name).text,fs.readFileSync(path.join(root,'store/wobblebay',name),'utf8'));assert.equal(progress.at(-1).bytes,progress.at(-1).total);assert.equal(c.files.get(home+'/name.txt').text,'Wobble Bay');pass('Installer stores every verified engine, vendor, licence, icon and identity file');
 c.storage.set('pocketvm.game.wobblebay',JSON.stringify({cash:326,prefs:{touchSize:'xl',touchControls:true},homes:['cottage'],stars:['star2']}));const win={id:'test-bay',content:{},el:{querySelector:()=>null}};await c.app.buildWobble(win,{},c.ctx);const sources=[...c.frame.srcdoc.matchAll(/src="(data:text\/javascript;base64,[^"]+)"/g)];assert.equal(sources.length,3);for(let i=0;i<3;i++){const expected=['three.min.js','engine.js','game.js'][i],decoded=Buffer.from(sources[i][1].split(',')[1],'base64').toString('utf8');assert.equal(decoded,fs.readFileSync(path.join(root,'store/wobblebay',expected),'utf8'));}assert.ok(c.frame.srcdoc.includes('"cash":326'));assert.ok(c.frame.srcdoc.includes('"touchSize":"xl"'));assert.ok(c.frame.srcdoc.includes('https://example.com/PocketVM/store/wobblebay/favicon-32.png'));pass('Sandbox embeds all three scripts and saved purchases without relative asset requests');
 const old=c.storage.get('pocketvm.game.wobblebay');c.events.message({source:{},data:{type:'pocketvm-wobble-save',data:{cash:999999}}});assert.equal(c.storage.get('pocketvm.game.wobblebay'),old);c.events.message({source:c.frame.contentWindow,data:{type:'pocketvm-wobble-save',data:{cash:219,stars:['star2','star2','fake'],prefs:{touchSize:'xl',touchControls:true,volume:2},rides:['heli','fake']}}});const saved=JSON.parse(c.storage.get('pocketvm.game.wobblebay'));assert.equal(saved.cash,219);assert.deepEqual(saved.stars,['star2']);assert.equal(saved.prefs.volume,1);assert.deepEqual(saved.rides,['runabout','heli']);pass('Only this game frame can save and its data is bounded and whitelisted');
 for(const badFile of ['game.html','engine.js','game.js','three.min.js','icon-512.png']){const b=context(badFile);await assert.rejects(()=>b.app.installWobble(),/incomplete|verification/);assert.equal(b.files.size,0);}pass('Five separate truncated downloads cannot create a partial installation');
 const broken=context();broken.setFailWrite(true);await assert.rejects(()=>broken.app.installWobble(),/interrupted/);assert.equal(broken.files.size,0);pass('An interrupted virtual-drive write rolls back the whole incomplete package');
 await c.disk.writeText(home+'/engine.js','old engine');await c.disk.writeText(home+'/name.txt','My Wobbly Island');await c.app.buildWobble(win,{},c.ctx);assert.equal(c.files.get(home+'/engine.js').text,fs.readFileSync(path.join(root,'store/wobblebay/engine.js'),'utf8'));assert.equal(c.files.get(home+'/name.txt').text,'My Wobbly Island');assert.ok(c.frame.srcdoc.includes('"cash":219'));assert.ok(c.frame.srcdoc.includes('"touchSize":"xl"'));pass('An outdated engine repairs on launch while keeping the custom name, money and touch preferences');
 c.setOffline(true);await c.app.buildWobble(win,{},c.ctx);assert.equal([...c.frame.srcdoc.matchAll(/data:text\/javascript;base64/g)].length,3);pass('An installed island starts with every script offline');c.setOffline(false);
 const a=context(),race='/home/user/Downloads/Apex Rush',raceHTML=fs.readFileSync(path.join(root,'store/apexrush/game.html'),'utf8');await a.disk.ensureDir(race);await a.disk.writeText(race+'/game.html',raceHTML);await a.disk.writeText(race+'/name.txt','My Race');await a.disk.writeBlob(race+'/icon.png',new Blob(['old artwork']));await a.disk.writeBlob(race+'/music.mp3',new Blob(['my music']));a.storage.set('pocketvm.game.apexrush','saved laps');await a.app.syncApexShell(a.ctx);const artwork=Buffer.from(await a.files.get(race+'/icon.png').blob.arrayBuffer());assert.deepEqual(artwork,fs.readFileSync(path.join(root,'store/apexrush/icon-512.png')));assert.equal(a.files.get(race+'/icon-version.txt').text,'illustrated-v1');assert.equal(a.files.get(race+'/name.txt').text,'My Race');assert.equal(a.files.get(race+'/game.html').text,raceHTML);assert.equal(await a.files.get(race+'/music.mp3').blob.text(),'my music');assert.equal(a.storage.get('pocketvm.game.apexrush'),'saved laps');pass('Installed artwork refresh preserves the game, custom name, soundtrack and save');
 const off=context();await off.disk.ensureDir(race);for(const name of ['game.html','music.mp3'])await off.disk.writeText(race+'/'+name,'original');await off.disk.writeBlob(race+'/icon.png',new Blob(['old artwork']));off.setOffline(true);await off.app.syncApexShell(off.ctx);assert.equal(await off.files.get(race+'/icon.png').blob.text(),'old artwork');assert.equal(off.files.has(race+'/icon-version.txt'),false);off.setOffline(false);await off.app.syncApexShell(off.ctx);assert.equal(off.files.get(race+'/icon-version.txt').text,'illustrated-v1');pass('Offline icon refresh retains old artwork and retries successfully when connected');
 const before=c.storage.get('pocketvm.game.wobblebay');await c.app.uninstallWobble();assert.equal(await c.app.wobbleInstalled(),false);assert.equal(c.storage.get('pocketvm.game.wobblebay'),before);pass('Uninstall removes virtual-drive files and retains earned progress');
 fs.writeFileSync(path.join(__dirname,'wobble-package-results.json'),JSON.stringify({checks:tests.length,tests},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1});
