// Render the actual production island and UI boot with a real software canvas.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),native=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/':'')+'@napi-rs/canvas'),THREE=require('../store/wobblebay/three.min.js');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'store/wobblebay/game.html'),'utf8'),elements=new Map(),callbacks=[],messages=[];
function element(id){if(elements.has(id))return elements.get(id);let e=id==='world'||id==='minimap'?native.createCanvas(id==='world'?1024:182,id==='world'?768:142):{};Object.assign(e,{id,hidden:false,style:{},dataset:{},textContent:'',classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return[]},focus(){},setPointerCapture(){},getBoundingClientRect(){return{left:0,top:0,width:100,height:100}}});if(id==='world'){const get=e.getContext.bind(e);e.getContext=type=>type==='2d'?get(type):null;}elements.set(id,e);return e;}
for(const [,id]of html.matchAll(/id="([^"]+)"/g))element(id);
const buttons=[...html.matchAll(/data-action="([^"]+)" id="([^"]+)"/g)].map(([,action,id])=>{const e=element(id);e.dataset.action=action;return e;});
const box={console:{log(){},warn(){},error(){}},THREE,Math,JSON,Map,Set,Array,Float32Array,Uint8Array,Blob,performance:{now:()=>0},innerWidth:1024,innerHeight:768,devicePixelRatio:1,navigator:{getGamepads:()=>[]},location:{reload(){}},localStorage:{getItem:()=>null,setItem(){}},parent:{postMessage:data=>messages.push(data)},requestAnimationFrame:f=>callbacks.push(f),addEventListener(){},document:{getElementById:id=>elements.get(id)||null,createElement:tag=>tag==='canvas'?native.createCanvas(512,128):element('new'),body:{dataset:{}},documentElement:{},querySelectorAll:s=>s==='[data-action]'?buttons:[],addEventListener(){}}};box.window=box;vm.createContext(box);
for(const name of ['engine.js','software-renderer.js','game.js'])vm.runInContext(fs.readFileSync(path.join(root,'store/wobblebay',name),'utf8'),box,{filename:name});
assert.ok(messages.some(m=>m.type==='pocketvm-wobble-ready'),'Production island boots');assert.equal(element('error').hidden,false);assert.equal(box.document.body.dataset.renderer,'software');assert.equal(callbacks.length,1);
let before=performance.now();callbacks.shift()(16.667);const renderMs=performance.now()-before;const canvas=element('world'),data=canvas.getContext('2d').getImageData(0,0,1024,768).data;const colours=new Set();for(let i=0;i<data.length;i+=64)colours.add(data[i]+','+data[i+1]+','+data[i+2]);assert.ok(colours.size>60,'Perspective scene contains ground, buildings, characters and sky');fs.writeFileSync(path.join(__dirname,'wobble-software-island.png'),canvas.toBuffer('image/png'));
element('play').onclick();assert.equal(element('menu').hidden,true);for(let i=2;i<24;i++)callbacks.shift()(i*16.667);assert.ok(element('missionTitle').textContent.includes('home'));assert.equal(element('hud').hidden,false);fs.writeFileSync(path.join(__dirname,'wobble-software-play.png'),canvas.toBuffer('image/png'));
const scene=new THREE.Scene();scene.background=new THREE.Color('#b3dfdf');scene.fog=new THREE.Fog('#b3dfdf',80,220);const camera=new THREE.PerspectiveCamera(55,4/3,.1,300);camera.position.set(0,2,7);camera.lookAt(0,0,0);const red=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:'#ed8068'}));scene.add(red);const testCanvas=native.createCanvas(320,240),render=new box.WobbleSoftwareRenderer({canvas:testCanvas});render.setSize(320,240);render.render(scene,camera);assert.ok(render.faces.length>=2);const far=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:'#70b18c'}),2),m=new THREE.Matrix4();m.makeTranslation(2,0,0);far.setMatrixAt(0,m);m.makeTranslation(-2,0,0);far.setMatrixAt(1,m);scene.add(far);render.render(scene,camera);assert.ok(render.faces.length>=8);red.position.set(0,2,8);render.render(scene,camera);assert.ok(render.faces.every(f=>Number.isFinite(f.z)&&(!f.p||f.p.flat().every(Number.isFinite))));
fs.writeFileSync(path.join(__dirname,'wobble-render-results.json'),JSON.stringify({checks:4,tests:['Production island boots using software graphics when WebGL is missing','Actual island renders perspective geometry and multiple colours','The production Play button opens the playable HUD','Perspective clipping and instanced geometry remain finite'],firstFrameMs:Math.round(renderMs),sampledColours:colours.size},null,2)+'\n');console.log('PASS 4 rendering checks; production island frame '+Math.round(renderMs)+'ms, '+colours.size+' sampled colours');
