/* Original arena art, UI and input for Ball vs Ball. */
(()=>{'use strict';const $=id=>document.getElementById(id),C=globalThis.BallCore;if(!C){$('error').hidden=false;$('error-text').textContent='A game file did not load. Reload or reinstall the game.';return;}
const {BALLS,RARITIES,ARENAS,WORLD,EDGE,CENTER,spawn,overtimeMargin,courtLayout,clamp}=C,canvas=$('arena'),ctx=canvas.getContext('2d'),images=new Map();if(!ctx){$('error').hidden=false;$('error-text').textContent='This browser cannot create a game canvas.';return;}
let raw={};try{raw=window.__POCKETVM_SAVE||JSON.parse(localStorage.getItem('pocketvm.game.ballvsball')||'{}');}catch{}
const profile=new C.Profile(raw);let stage='menu',round=null,panel=null,choosingCollection=false,chooser=0,aimPointer=null,aimAngle=0,count=0,last=0,acc=0,now=0,paused=false,speed=1,toastTime=0,roundDelay=0,filter='all',audioReady=false,soundCtx=null,lastFocus=null,arenaScale=1,court=null,origin={x:0,y:0},shake=0,trail=[],reduced=profile.save.prefs.motion===false;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const glyphs={smile:'',spikes:'',flame:'♨',snow:'❄',laser:'⌖',fangs:'',shield:'⬡',bolt:'ϟ',bomb:'●',grow:'↗',plus:'+',skull:'×',crescent:'☾',split:'••',magnet:'∩',orbit:'⊙',rocket:'↑',swirl:'↻',rock:'◆',ghost:'',thorn:'✦',diamond:'◇',chain:'∞',wings:'⋁',meteor:'☄',drop:'♦',wind:'≋',slime:'●',saw:'✹',wave:'◎',quake:'⌁',swap:'⇄',bee:'',cactus:'✣',sun:'☀',rainbow:'',void:'◉',crown:'♛',bubble:'◌',dice:'⚄',comet:'☄',prism:'△',ninja:'✥',boomerang:'❯',scorpion:'♏',angel:'♧',portal:'◉',drill:'⏶',tornado:'≋',mushroom:'♠',anchor:'⚓',neon:'ϟ',clock:'◷',dragon:'♨',spark:'✧',echo:'◎'};
function art(b,locked=false){const color=locked?'#8190a4':b.color,r=40,spike=['spikes','saw','thorn','cactus'].includes(b.art),points=Array.from({length:24},(_,n)=>{const a=n*Math.PI/12,r=n%2?42:51;return(60+Math.cos(a)*r).toFixed(2)+','+(60+Math.sin(a)*r).toFixed(2);}).join(' '),dark='#26324a',special=b.art==='bee'?'<path d="M35 30V84M53 22V92M72 22V92" stroke="#554c35" stroke-width="9" opacity=".7"/><ellipse cx="39" cy="17" rx="12" ry="16" fill="#e4edee" opacity=".9"/><ellipse cx="76" cy="17" rx="12" ry="16" fill="#e4edee" opacity=".9"/>':b.art==='rainbow'?'<path d="M31 57Q60 15 89 57" fill="none" stroke="#f1a293" stroke-width="11"/><path d="M39 57Q60 28 81 57" fill="none" stroke="#ebd382" stroke-width="8"/><path d="M47 57Q60 43 73 57" fill="none" stroke="#a1d3c7" stroke-width="7"/>':b.art==='fangs'?'<path d="M36 76Q59 94 84 76" fill="#644461"/><path d="M44 80L51 95L56 83M67 83L74 95L80 80" fill="#f2eed8"/>':b.art==='ghost'?'<path d="M34 81L40 95L50 83L61 95L72 83L82 95L88 78" fill="#d7e7ee" opacity=".85"/>':b.art==='flame'?'<path d="M41 58Q33 48 53 30Q54 45 65 42Q67 30 76 50Q85 69 65 76Q42 77 41 58Z" fill="#fff0b0"/>':b.art==='bomb'?'<path d="M61 22V13Q76 13 75 3" fill="none" stroke="#e8c69a" stroke-width="4"/><circle cx="76" cy="5" r="5" fill="#f8df8d"/>':'';
 const hasGlyph=!['smile','spikes','saw','thorn','cactus','bee','fangs','ghost','flame','rainbow'].includes(b.art),eyes=!hasGlyph&&b.art!=='rainbow'?`<ellipse cx="45" cy="60" rx="5" ry="7" fill="${dark}"/><ellipse cx="75" cy="60" rx="5" ry="7" fill="${dark}"/><path d="M47 76Q60 87 74 76" fill="none" stroke="${dark}" stroke-width="3.5" stroke-linecap="round"/>`:'';
 return `<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120" viewBox="0 0 120 120" role="img" aria-label="${escape(b.name)}"><defs><radialGradient id="g-${b.id}-${locked?'locked':'open'}" cx=".32" cy=".27"><stop stop-color="${locked?'#a6b1bc':'#fff8df'}"/><stop offset=".34" stop-color="${color}"/><stop offset="1" stop-color="${color}"/></radialGradient></defs><ellipse cx="62" cy="107" rx="37" ry="6" fill="#07142724"/>${spike?`<polygon points="${points}" fill="${color}" stroke="${dark}" stroke-width="3"/>`:''}<circle cx="60" cy="60" r="${r}" fill="url(#g-${b.id}-${locked?'locked':'open'})" stroke="${dark}" stroke-width="3"/><path d="M31 62Q32 87 59 97Q84 96 94 76" fill="none" stroke="#122e4c" stroke-opacity=".16" stroke-width="7" stroke-linecap="round"/><ellipse cx="42" cy="34" rx="9" ry="5" fill="#fff9e0" opacity=".5" transform="rotate(-35 42 34)"/>${special}${hasGlyph?`<text x="60" y="75" fill="${dark}" font-size="43" text-anchor="middle" font-family="sans-serif" font-weight="bold">${glyphs[b.art]||'✦'}</text>`:''}${eyes}</svg>`;
}
function imageFor(b){if(images.has(b.id))return images.get(b.id);const im=new Image();im.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(art(b));images.set(b.id,im);return im;}
function save(){const data=profile.export();try{localStorage.setItem('pocketvm.game.ballvsball',JSON.stringify(data));}catch{}parent.postMessage({type:'pocketvm-ball-save',data},'*');}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;toastTime=4;}
function effects(kind){if(!profile.save.prefs.effects)return;try{soundCtx=soundCtx||new (window.AudioContext||window.webkitAudioContext)();soundCtx.resume();const t=soundCtx.currentTime,frequencies=kind==='win'?[523,659,784]:kind==='lose'?[260,220]:kind==='unlock'?[440,660,880]:[150+Math.random()*80];for(let i=0;i<frequencies.length;i++){const osc=soundCtx.createOscillator(),g=soundCtx.createGain();osc.type=kind==='hit'?'triangle':'sine';osc.frequency.setValueAtTime(frequencies[i],t+i*.09);g.gain.setValueAtTime(.045,t+i*.09);g.gain.exponentialRampToValueAtTime(.001,t+i*.09+.14);osc.connect(g).connect(soundCtx.destination);osc.start(t+i*.09);osc.stop(t+i*.09+.17);}}catch{}}
function activateAudio(){audioReady=true;music();}
function music(){const active=stage==='menu'?$('menu-music'):$('battle-music'),other=stage==='menu'?$('battle-music'):$('menu-music');if(!profile.save.prefs.music||!audioReady||document.hidden){active.pause();other.pause();return;}active.volume=profile.save.prefs.volume;other.pause();if(active.paused)active.play().catch(()=>{});$('sound').textContent=profile.save.prefs.music?'♫':'♪';}
function updateHUD(){const m=profile.match;$('coins').textContent='◈ '+profile.save.coins.toLocaleString();$('sound').textContent=profile.save.prefs.music?'♫':'♪';const playing=!['menu','choose'].includes(stage);$('battle-score').hidden=!m||stage==='menu';$('pause').hidden=stage==='menu';$('battle-actions').hidden=stage!=='battle';$('battle-status').hidden=stage!=='battle';$('aim-heading').hidden=stage!=='aim';$('aim-ui').hidden=stage!=='aim';$('countdown').hidden=stage!=='countdown';if(m){$('hearts-you').textContent='♥ '.repeat(Math.max(0,m.hearts[0]))+'♡ '.repeat(3-Math.max(0,m.hearts[0]));$('hearts-enemy').textContent='♥ '.repeat(Math.max(0,m.hearts[1]))+'♡ '.repeat(3-Math.max(0,m.hearts[1]));$('round-label').textContent='Round '+m.round;}if(round&&stage==='battle')$('battle-status').textContent=round.overtime?'Sudden death · The walls are closing in':'Auto-battle · '+Math.floor(round.time)+'s';$('aim-heading').textContent=profile.match?.mode==='local'?'Player '+(chooser+1)+' · Set your aim':'Your opening move';}
function setStage(next){stage=next;for(const id of ['menu','choose','result'])$(id).hidden=id!==next;aimPointer=null;updateHUD();music();last=0;acc=0;}
function start(){activateAudio();profile.start();round=null;chooser=0;speed=1;$('speed').textContent='1×';showChoose();save();}
function showChoose(){setStage('choose');const m=profile.match;$('choose-title').textContent=m.mode==='local'?'Player '+(chooser+1)+' · Choose your ball':'Choose your ball';$('choose-lead').textContent='Round '+m.round+' · '+(m.mode==='chaos'?'Four balls per team. Eight balls. Three hearts.':m.mode==='team'?'Two balls per team. Three hearts.':'Three hearts. Choose your opening advantage.');$('offers').innerHTML=m.offers[chooser].map(id=>{const b=BALLS.find(b=>b.id===id);return `<button class="ball-choice" data-ball="${b.id}"><span class="art">${art(b)}</span><b>${b.name}</b><span class="tag">${RARITIES[b.rarity]}</span><span class="desc">${b.description}</span></button>`;}).join('');$('reroll').hidden=chooser!==0;$('reroll').disabled=m.rerolled;$('collection-pick').disabled=m.collectionUsed[chooser];$('leave').textContent=m.round===1?'Back to menu':'Leave match';}
function choose(id,fromCollection=false){if(!profile.choose(id,chooser,fromCollection))return;profile.save.selected=id;aimAngle=chooser===1?Math.PI:0;setStage('aim');save();}
function lock(){if(stage!=='aim')return;profile.match.angles[chooser]=aimAngle;if(profile.match.mode==='local'&&chooser===0){chooser=1;showChoose();return;}round=profile.makeRound(court.worldWidth);trail=[];count=2.5;setStage('countdown');effects('unlock');}
function finishRound(){if(!profile.settleRound(round))return;const m=profile.match,winner=round.result,youWin=winner===0,local=m.mode==='local';$('result-title').textContent=m.finished?(local?'Player '+(m.hearts[0]>m.hearts[1]?1:2)+' wins!':youWin?'Match won!':'Good fight.'):(winner<0?'A perfect tie.':local?'Player '+(winner+1)+' takes the round':youWin?'Round won!':'Round lost');if(m.hearts[0]===0&&m.hearts[1]===0)$('result-title').textContent='A draw!';$('result-symbol').textContent=youWin?'✦':winner<0?'◇':'↻';$('result-info').textContent=m.finished?'+'+m.reward+' coins · '+profile.save.owned.length+' / '+BALLS.length+' balls collected':youWin?'The other side loses a heart. Pick your next ball.':'A new roll. A new opening. The match is still yours to turn around.';$('result-hearts').innerHTML='<span>'+'♥ '.repeat(Math.max(0,m.hearts[0]))+'</span><span>'+'♥ '.repeat(Math.max(0,m.hearts[1]))+'</span>';$('next').textContent=m.finished?'Play another match →':'Next round →';setStage('result');save();effects(youWin?'win':'lose');navigator.vibrate?.(youWin?[20,40,30]:20);}
function goMenu(){round=null;paused=false;chooser=0;closePanel();setStage('menu');save();}
function resize(){const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*ratio);canvas.height=Math.round(innerHeight*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);court=courtLayout(innerWidth,innerHeight);arenaScale=court.scale;origin={x:court.x-28*arenaScale,y:court.y-28*arenaScale*.87};round?.resize(court.worldWidth);trail=[];aimPointer=null;canvas.dataset.court=JSON.stringify({x:court.x,y:court.y,width:court.width,height:court.height,worldWidth:court.worldWidth});}

function ballDraw(b,x,y,r,alpha=1,spin=0){const def=BALLS.find(x=>x.id===(typeof b==='string'?b:b.type))||BALLS[0],im=imageFor(def);ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.scale(1,1/.87);ctx.fillStyle='#0d162d25';ctx.beginPath();ctx.ellipse(3,r*.75,r*.94,r*.28,0,0,Math.PI*2);ctx.fill();ctx.rotate(spin*.28);if(im.complete&&im.naturalWidth){const outer=['spikes','saw','thorn','cactus'].includes(def.art)?51:40,size=r*120/outer;ctx.drawImage(im,-size/2,-size/2,size,size);}else{ctx.fillStyle=def.color;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#26324a';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#253345';for(const dx of [-r*.25,r*.25]){ctx.beginPath();ctx.arc(dx,-r*.1,r*.1,0,Math.PI*2);ctx.fill();}}ctx.restore();}
function avatar(x,y,team,hearts=3){const blue=team===0,color=blue?'#749cce':'#cb7d91';ctx.save();ctx.translate(x,y);ctx.scale(1,1/.87);ctx.fillStyle=blue?'#7dabde':'#d78da0';ctx.beginPath();ctx.ellipse(0,23,35,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#283851';ctx.fillRect(-15,2,12,22);ctx.fillRect(3,2,12,22);ctx.fillStyle=color;ctx.fillRect(-22,-32,44,36);ctx.fillRect(-34,-29,10,32);ctx.fillRect(24,-29,10,32);ctx.fillStyle='#e4c79f';ctx.fillRect(-17,-63,34,32);ctx.fillRect(-34,1,10,8);ctx.fillRect(24,1,10,8);ctx.fillStyle='#293548';ctx.fillRect(-17,-65,34,7);ctx.fillStyle='#2d394c';ctx.fillRect(-9,-50,3,4);ctx.fillRect(6,-50,3,4);ctx.strokeStyle='#695b53';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-44,7,.1,Math.PI-.1);ctx.stroke();ctx.restore();}
function render(dt){now+=dt;const w=innerWidth,h=innerHeight,m=profile.match,arena=round?.arena||ARENAS.find(a=>a.id===(m?.arena||profile.save.prefs.arena))||ARENAS[0];const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,arena.id==='forge'?'#283344':'#25344a');bg.addColorStop(1,'#131c2c');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle='#e4eaf10d';for(let n=0;n<45;n++){const x=(n*131.3%w),y=(n*73.7%h);ctx.beginPath();ctx.arc(x,y,n%3?1:2,0,Math.PI*2);ctx.fill();}
 ctx.save();ctx.translate(origin.x,origin.y);ctx.scale(arenaScale,arenaScale*.87);if(shake>0&&profile.save.prefs.motion){ctx.translate(Math.sin(now*71)*shake,Math.cos(now*57)*shake);shake=Math.max(0,shake-dt*30);}const mapWidth=round?.width||court.worldWidth,centerX=mapWidth/2,margin=overtimeMargin(round?.time||0,mapWidth),low=EDGE+margin,high=WORLD-EDGE-margin,highX=mapWidth-EDGE-margin,span=WORLD-EDGE*2,spanX=mapWidth-EDGE*2;
 ctx.fillStyle='#0d132649';ctx.beginPath();ctx.roundRect(35,65,mapWidth-70,WORLD-65,22);ctx.fill();ctx.fillStyle=arena.wall;ctx.beginPath();ctx.roundRect(28,28,mapWidth-56,WORLD-56,17);ctx.fill();ctx.fillStyle=arena.floor;ctx.beginPath();ctx.roundRect(EDGE,EDGE,spanX,span,7);ctx.fill();ctx.save();ctx.beginPath();ctx.rect(EDGE,EDGE,spanX,span);ctx.clip();ctx.strokeStyle=arena.id==='forge'?'#748ca42c':'#71829323';ctx.lineWidth=1;for(let n=EDGE;n<=mapWidth-EDGE;n+=40){ctx.beginPath();ctx.moveTo(n,EDGE);ctx.lineTo(n,WORLD-EDGE);ctx.stroke();}for(let n=EDGE;n<=WORLD-EDGE;n+=40){ctx.beginPath();ctx.moveTo(EDGE,n);ctx.lineTo(mapWidth-EDGE,n);ctx.stroke();}ctx.strokeStyle=arena.accent;ctx.lineWidth=2;ctx.setLineDash([7,8]);ctx.beginPath();ctx.moveTo(centerX,50);ctx.lineTo(centerX,WORLD-50);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(centerX,CENTER,115,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.22;ctx.fillStyle=arena.accent;ctx.font='bold 39px sans-serif';ctx.textAlign='center';ctx.fillText('BALL  /  BALL',centerX,CENTER+13);ctx.globalAlpha=1;ctx.restore();
 if(margin>0){ctx.fillStyle='#cf778735';ctx.fillRect(EDGE,EDGE,margin,span);ctx.fillRect(mapWidth-EDGE-margin,EDGE,margin,span);ctx.fillRect(EDGE,EDGE,spanX,margin);ctx.fillRect(EDGE,WORLD-EDGE-margin,spanX,margin);ctx.strokeStyle='#e58f99';ctx.lineWidth=3;ctx.strokeRect(low,low,highX-low,high-low);}
 ctx.fillStyle='#bac6d0';ctx.fillRect(28,WORLD-28,mapWidth-56,14);ctx.fillStyle='#43526b';ctx.fillRect(28,EDGE,12,WORLD-68);ctx.fillRect(mapWidth-EDGE,EDGE,12,WORLD-68);ctx.fillStyle='#dce0e7';ctx.fillRect(EDGE,28,spanX,12);ctx.fillStyle=arena.id==='forge'?'#6f879d':'#b8bec7';ctx.fillRect(EDGE,WORLD-EDGE,spanX,12);

 for(const base of arena.obstacles){const o=round?base:{...base,x:base.x*mapWidth/WORLD};ctx.fillStyle='#13213a23';ctx.beginPath();ctx.ellipse(o.x+3,o.y+12,o.r+3,o.r*.7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=arena.wall;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.fillStyle=arena.accent;ctx.beginPath();ctx.arc(o.x,o.y-5,o.r-4,0,Math.PI*2);ctx.fill();}
 // Spectators use screen coordinates so they stay small and outside the floor.
 const portrait=innerWidth<600,playerScale=portrait?.38:Math.min(.68,court.x/78),playerY=portrait?court.y-15:court.y+court.height/2;
 ctx.restore();for(const [x,team]of[[portrait?innerWidth*.10:court.x/2,0],[portrait?innerWidth*.90:innerWidth-court.x/2,1]]){ctx.save();ctx.translate(x,playerY);ctx.scale(playerScale,playerScale*.87);avatar(0,0,team,m?.hearts[team]);ctx.restore();}ctx.save();ctx.translate(origin.x,origin.y);ctx.scale(arenaScale,arenaScale*.87);

 if(stage==='menu'){ballDraw('classic',mapWidth*.32,CENTER,49,1,Math.sin(now*.5));ballDraw('spike',mapWidth*.68,CENTER,49,1,-Math.sin(now*.5));}
 else if(['choose','aim'].includes(stage)){const chosen=m?.selected[chooser],side=chooser,position=spawn(side,0,m?.mode==='chaos'?4:m?.mode==='team'?2:1,mapWidth);ballDraw(chosen||m?.offers[side][0]||'classic',position.x,position.y,30);if(m?.mode==='local'&&m.selected[0]&&chooser===1)ballDraw(m.selected[0],spawn(0,0,1,mapWidth).x,spawn(0).y,30);if(stage==='aim'){const end={x:position.x+Math.cos(aimAngle)*135,y:position.y+Math.sin(aimAngle)*135};ctx.strokeStyle=side?'#a94969':'#376b9f';ctx.lineWidth=4;ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(position.x,position.y);ctx.lineTo(end.x,end.y);ctx.stroke();ctx.setLineDash([]);ctx.save();ctx.translate(end.x,end.y);ctx.rotate(aimAngle);ctx.fillStyle=side?'#a94969':'#376b9f';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-4,-8);ctx.lineTo(-4,8);ctx.closePath();ctx.fill();ctx.restore();}}
 else if(round){
 for(const z of round.zones){ctx.save();ctx.globalAlpha=.2+Math.sin(now*8)*.06;ctx.fillStyle=z.kind==='fire'?'#e78c56':z.kind==='meteor'?'#e5a069':'#6a66ad';ctx.beginPath();ctx.arc(z.x,z.y,z.kind==='meteor'?z.r*(.85+Math.sin(now*8)*.1):z.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=z.kind==='meteor'?'#8c443a':'#efddd4';ctx.lineWidth=2;ctx.stroke();ctx.restore();}
 if(profile.save.prefs.motion){for(const t of trail){ctx.globalAlpha=t.life*.11;ctx.fillStyle=t.color;ctx.beginPath();ctx.arc(t.x,t.y,t.r*.7,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
 for(const p of round.projectiles){ctx.fillStyle=p.color;ctx.strokeStyle='#26354b';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.stroke();}
 for(const b of [...round.entities].sort((a,b)=>a.y-b.y)){if(b.hp<=0)continue;ballDraw(b,b.x,b.y,b.r,b.phased>0?.4:1,b.spin);if(b.flash>0){ctx.strokeStyle='#fff8d9';ctx.lineWidth=3;ctx.beginPath();ctx.arc(b.x,b.y,b.r+4,0,Math.PI*2);ctx.stroke();}if(b.shield>0){ctx.strokeStyle='#91c5e788';ctx.lineWidth=3;ctx.beginPath();ctx.arc(b.x,b.y,b.r+6,0,Math.PI*2);ctx.stroke();}if(b.freeze>0||b.slow>0){ctx.strokeStyle='#a8edf3';ctx.lineWidth=3;ctx.beginPath();ctx.arc(b.x,b.y,b.r+3,0,Math.PI*2);ctx.stroke();}
 ctx.fillStyle='#24344bc9';ctx.beginPath();ctx.roundRect(b.x-25,b.y-b.r-18,50,6,3);ctx.fill();ctx.fillStyle=b.team===0?'#568ac4':'#bf617b';ctx.beginPath();ctx.roundRect(b.x-25,b.y-b.r-18,Math.max(1,50*b.hp/b.max),6,3);ctx.fill();if(b.type==='orbit'){for(let n=0;n<2;n++){const a=now*4+n*Math.PI;ctx.fillStyle='#739fc9';ctx.beginPath();ctx.arc(b.x+Math.cos(a)*43,b.y+Math.sin(a)*43,7,0,Math.PI*2);ctx.fill();}}}
 for(const e of round.effects){const t=e.t/e.life;ctx.save();ctx.globalAlpha=(1-t)*.8;ctx.strokeStyle=e.color;ctx.fillStyle=e.color;ctx.lineWidth=e.kind==='beam'?4:3;if(e.kind==='beam'){ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x2,e.y2);ctx.stroke();}else if(e.kind==='plus'){ctx.font='bold 26px sans-serif';ctx.fillText('+',e.x-7,e.y-25-t*20);}else if(e.kind==='burst'||e.kind==='impact'){for(let n=0;n<8;n++){const a=n*Math.PI/4,x=e.x+Math.cos(a)*e.r*t,y=e.y+Math.sin(a)*e.r*t;ctx.beginPath();ctx.arc(x,y,5*(1-t)+1,0,Math.PI*2);ctx.fill();}}else{ctx.beginPath();ctx.arc(e.x,e.y,e.r*(.3+t*.7),0,Math.PI*2);ctx.stroke();}ctx.restore();}
 ctx.font='bold 14px sans-serif';ctx.textAlign='center';for(const t of round.damageText){ctx.globalAlpha=clamp(t.life*2,0,1);ctx.fillStyle='#fff9e0';ctx.strokeStyle='#35435b';ctx.lineWidth=3;ctx.strokeText('-'+t.value,t.x,t.y);ctx.fillText('-'+t.value,t.x,t.y);}ctx.globalAlpha=1;
 }ctx.restore();}
function animate(time){requestAnimationFrame(animate);const dt=last?Math.min(1,(time-last)/1000):1/60;last=time;if(document.hidden)return;if(!panel&&!paused){if(stage==='countdown'){count-=dt;$('countdown').textContent=count>1?Math.ceil(count- .5):'GO!';if(count<=0)setStage('battle');}else if(stage==='battle'&&round&&!round.done){acc+=dt*speed;while(acc>=1/120){round.step(1/120);acc-=1/120;}for(const e of round.events.splice(0)){if(e.type==='hit'){shake=profile.save.prefs.motion?1.8:0;effects('hit');}if(e.type==='knockout')effects('lose');}for(const b of round.entities)if(b.hp>0)trail.push({x:b.x,y:b.y,r:b.r,color:BALLS.find(x=>x.id===b.type).color,life:1});trail=trail.slice(-100);if(round.done)roundDelay=.8;}else if(stage==='battle'&&round?.done){roundDelay-=dt;if(roundDelay<=0)finishRound();}}
 for(const t of trail)t.life-=dt*2;trail=trail.filter(t=>t.life>0);toastTime-=dt;if(toastTime<=0)$('toast').hidden=true;render(dt);updateHUD();}
function point(e){return{x:(e.clientX-origin.x)/arenaScale,y:(e.clientY-origin.y)/(arenaScale*.87)}}
function aim(e){if(stage!=='aim')return;const p=point(e),{x,y}=spawn(chooser,0,profile.match.mode==='chaos'?4:profile.match.mode==='team'?2:1,court.worldWidth);if(Math.hypot(p.x-x,p.y-y)>10)aimAngle=Math.atan2(p.y-y,p.x-x);}
function openPanel(type,pick=false){lastFocus=document.activeElement;aimPointer=null;panel=type;choosingCollection=pick;$('overlay').hidden=false;renderPanel();$('close').focus();}
function closePanel(){panel=null;choosingCollection=false;$('overlay').hidden=true;last=0;acc=0;lastFocus?.focus?.();}
function renderPanel(){const s=profile.save,body=$('panel-body');$('panel-title').textContent=panel==='collection'?(choosingCollection?'Choose from your collection':'Your collection'):panel==='pause'?'Taking a breather':'Settings';$('panel-subtitle').textContent=panel==='collection'?s.owned.length+' / '+BALLS.length+' balls · '+s.coins.toLocaleString()+' coins':panel==='pause'?'The simulation is paused.':'Music, match settings and controls';
 if(panel==='collection'){const shown=BALLS.filter(b=>filter==='all'||filter==='owned'&&s.owned.includes(b.id)||filter==='locked'&&!s.owned.includes(b.id));body.innerHTML=`${!choosingCollection?`<div class="pack-offer"><div><h3>A surprise in every capsule</h3><p>Common 46% · Uncommon 30% · Rare 18% · Legendary 6%<br>Duplicates refund 60 coins. After four duplicates, the next capsule guarantees a new ball.</p></div><button class="primary" data-action="pack" ${s.coins<150?'disabled':''}>Open · 150 ◈</button></div>`:''}<div class="collection-bar"><select id="filter" aria-label="Collection filter"><option value="all" ${filter==='all'?'selected':''}>All balls</option><option value="owned" ${filter==='owned'?'selected':''}>Owned</option><option value="locked" ${filter==='locked'?'selected':''}>Not collected</option></select><p>${choosingCollection?'One free collection pick per player, per match.':'Unlock directly or try a capsule. Rarity does not guarantee a win.'}</p></div><div class="grid">${shown.map(b=>{const owned=s.owned.includes(b.id);return `<article class="collection-item ${owned?'':'locked'}"><span class="tag">${RARITIES[b.rarity]}</span><div class="art">${art(b,!owned)}</div><h3>${b.name}</h3><p>${b.description}</p><button data-action="${choosingCollection?'pick':'buy'}" data-id="${b.id}" ${choosingCollection?!owned?'disabled':'':owned||s.coins<b.price?'disabled':''} class="${choosingCollection?'blue':''}">${choosingCollection?owned?'Pick this ball':'Locked':owned?'Owned':b.price+' ◈ · Unlock'}</button></article>`;}).join('')}</div>`;}
 else if(panel==='pause'){body.innerHTML='<div class="help">No hurry. Your balls and cooldowns wait while this panel is open.</div><div style="display:flex;gap:10px;margin-top:20px;flex-wrap:wrap"><button class="primary" data-action="resume">Resume</button><button data-action="settings">Settings</button><button data-action="exit">Leave match</button></div>';}
 else{const p=s.prefs;body.innerHTML=`<div class="stats"><span><b>${s.stats.wins}</b>matches won</span><span><b>${s.stats.matches}</b>matches played</span><span><b>${s.stats.bestStreak}</b>best streak</span><span><b>${s.owned.length}</b>balls collected</span></div><div class="setting"><div><b>Music</b><p>Your supplied menu and battle tracks.</p></div><input id="pref-music" type="checkbox" ${p.music?'checked':''} aria-label="Music"></div><div class="setting"><div><b>Music volume</b><p>A quieter background for louder collisions.</p></div><input id="pref-volume" type="range" min="0" max="1" step="0.05" value="${p.volume}" aria-label="Music volume"></div><div class="setting"><div><b>Sound effects</b><p>Collisions, knockouts and collection reveals.</p></div><input id="pref-effects" type="checkbox" ${p.effects?'checked':''} aria-label="Sound effects"></div><div class="setting"><div><b>Motion effects</b><p>Trails and a small impact shake.</p></div><input id="pref-motion" type="checkbox" ${p.motion?'checked':''} aria-label="Motion effects"></div><div class="setting"><div><b>AI difficulty</b><p>Applies to your next match. Local duels use equal stats.</p></div><select id="pref-difficulty" aria-label="AI difficulty">${['easy','normal','hard','random'].map(v=>`<option value="${v}" ${v===p.difficulty?'selected':''}>${v==='normal'?'Standard':v[0].toUpperCase()+v.slice(1)}</option>`).join('')}</select></div><div class="setting"><div><b>Arena</b><p>Six spacious courts. Bumper positions vary each match.</p></div><select id="pref-arena" aria-label="Arena">${ARENAS.map(a=>`<option value="${a.id}" ${a.id===p.arena?'selected':''}>${a.name}</option>`).join('')}<option value="random" ${p.arena==='random'?'selected':''}>Random</option></select></div><p class="help"><b>How to play</b><br>Choose one of three offered balls. Drag anywhere in the arena to aim, then Lock aim. Balls bounce and use abilities automatically. Each round removes one heart from the losing side; lose three hearts and the match ends. A tied round removes a heart from both sides. Sudden death closes the walls after 30 seconds.<br><br>Choose from your full collection once per match, and reroll the offer once. Win coins, open capsules or unlock balls directly. In 2 players, pass the device so each player can choose and aim. Keyboard: arrows or A/D rotate aim, Enter locks it, Escape pauses. Battles can run at 1× or 2× speed.<br><br>An original browser adaptation inspired by Roblox Ball VS Ball. AI battles and local two-player duels work offline. Collection, coins, settings and stats save on this browser. It has no online matchmaking or Roblox account connection.</p><button data-action="fullscreen">Fullscreen</button>`;}}
function action(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;if(a==='buy'){if(profile.buy(id)){save();toast('Unlocked '+BALLS.find(b=>b.id===id).name);effects('unlock');renderPanel();updateHUD();}}if(a==='pick'){closePanel();choose(id,true);}if(a==='pack'){const result=profile.pack();if(!result)return;save();$('pack-art').innerHTML=art(result.ball);$('pack-title').textContent=result.ball.name;$('pack-info').textContent=result.duplicate?'Already collected · 60 coins returned':'New ball unlocked · '+RARITIES[result.ball.rarity];$('pack-result').hidden=false;effects('unlock');renderPanel();updateHUD();}if(a==='resume')closePanel();if(a==='settings'){panel='settings';renderPanel();}if(a==='exit'){goMenu();}if(a==='fullscreen'){document.documentElement.requestFullscreen?.().catch(()=>toast('Fullscreen is unavailable here. Open the game directly for more room.'));}}
function setup(){
 $('menu-art').innerHTML=art(BALLS[0])+'<span>vs</span>'+art(BALLS[1]);document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',profile.save.prefs.mode===b.dataset.mode);b.addEventListener('click',()=>{profile.save.prefs.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));activateAudio();save();});});
 $('play').addEventListener('click',start);$('collection').addEventListener('click',()=>{filter='all';activateAudio();openPanel('collection');});$('settings').addEventListener('click',()=>{activateAudio();openPanel('settings');});$('pause').addEventListener('click',()=>openPanel('pause'));$('close').addEventListener('click',closePanel);$('overlay').addEventListener('click',e=>{if(e.target===$('overlay'))closePanel();});$('sound').addEventListener('click',()=>{audioReady=true;profile.save.prefs.music=!profile.save.prefs.music;music();save();updateHUD();});
 $('offers').addEventListener('click',e=>{const b=e.target.closest('[data-ball]');if(b)choose(b.dataset.ball);});$('reroll').addEventListener('click',()=>{if(profile.reroll())showChoose();});$('collection-pick').addEventListener('click',()=>{filter='owned';openPanel('collection',true);});$('leave').addEventListener('click',goMenu);$('lock-aim').addEventListener('click',lock);$('next').addEventListener('click',()=>{if(profile.match.finished)start();else if(profile.nextRound()){chooser=0;showChoose();}});$('result-menu').addEventListener('click',goMenu);$('speed').addEventListener('click',()=>{speed=speed===1?2:1;$('speed').textContent=speed+'×';});$('pack-close').addEventListener('click',()=>$('pack-result').hidden=true);
 canvas.addEventListener('pointerdown',e=>{if(panel||stage!=='aim')return;e.preventDefault();aimPointer=e.pointerId;canvas.setPointerCapture(e.pointerId);aim(e);activateAudio();});canvas.addEventListener('pointermove',e=>{if(e.pointerId===aimPointer)aim(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(e.pointerId===aimPointer)aimPointer=null;});
 $('panel-body').addEventListener('click',action);$('panel-body').addEventListener('change',e=>{const id=e.target.id;if(id==='filter'){filter=e.target.value;renderPanel();return;}if(id.startsWith('pref-')){const key=id.slice(5);profile.save.prefs[key]=['music','effects','motion'].includes(key)?e.target.checked:key==='volume'?Number(e.target.value):e.target.value;activateAudio();save();}});$('panel-body').addEventListener('input',e=>{if(e.target.id==='pref-volume'){profile.save.prefs.volume=Number(e.target.value);music();}});
 addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target?.tagName))return;if(e.code==='Escape'){e.preventDefault();if(panel)closePanel();else if(stage!=='menu')openPanel('pause');return;}if(panel){if(e.code==='Tab'){const list=[...$('overlay').querySelectorAll('button,input,select')].filter(x=>!x.disabled),first=list[0],end=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end?.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first?.focus();}}return;}if(stage==='aim'){if(['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code)){e.preventDefault();aimAngle+=(e.code==='ArrowLeft'||e.code==='KeyA'?-.1:.1);}if(e.code==='Enter'){e.preventDefault();lock();}}else if(stage==='menu'&&e.code==='Enter'){e.preventDefault();start();}});
 addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);addEventListener('blur',()=>{aimPointer=null;save();});document.addEventListener('visibilitychange',()=>{aimPointer=null;if(document.hidden){last=0;acc=0;save();}music();});addEventListener('pagehide',save);
 for(const b of BALLS)imageFor(b);resize();updateHUD();parent.postMessage({type:'pocketvm-ball-ready'},'*');requestAnimationFrame(animate);
}
try{setup();}catch(e){$('error').hidden=false;$('error-text').textContent=e.message;console.error(e);}
})();
