/* Original models, world art, sound and interface for Fisch: Horizon. */
(()=>{'use strict';
const $=id=>document.getElementById(id),C=globalThis.FischCore,T=globalThis.THREE;
if(!C||!T){$('error').hidden=false;$('error-text').textContent='A game file could not load. Reconnect and reload, or reinstall from the Store.';return;}
const {ISLANDS,FISH,RODS,BAITS,BOATS,ENCHANTS,MUTATIONS,QUESTS,RARITIES,clamp,dist}=C;
let saved={};try{saved=window.__POCKETVM_SAVE||JSON.parse(localStorage.getItem('pocketvm.game.fisch')||'{}');}catch{}
const game=new C.Game(saved),canvas=$('world'),keys=new Set(),held={reel:false,jump:false},joystick={x:0,z:0},materials=new Map(),geometries=new Map(),buckets=new Map();
let rain=[],aurora=[],wake=[],birds=[],stars=[],lineTube;
let renderer,scene,camera,avatar,boatModel,rodModel,line,bobber,sun,water=[],clouds=[],fishDisplay,playing=false,panel=null,sub='rods',mapTarget='reef',search='',filter='all',yaw=0,pitch=.43,zoom=15,look=null,stickPointer=null,castPointer=null,last=0,acc=0,uiTime=0,saveTime=0,catchTime=0,toastTime=0,animTime=0,audio=null,focused=true,lastFocus=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function material(color,glow=false){const k=color+glow;if(!materials.has(k))materials.set(k,new T.MeshStandardMaterial({color,roughness:.87,metalness:0,flatShading:true,emissive:glow?color:'#000000',emissiveIntensity:glow?.28:0}));return materials.get(k);}
function geom(type){if(!geometries.has(type))geometries.set(type,type==='sphere'?new T.SphereGeometry(1,10,7):type==='rock'?new T.IcosahedronGeometry(1,0):type==='cone'?new T.ConeGeometry(1,1,8):type==='roof'?new T.ConeGeometry(1,1,4):type==='cylinder'?new T.CylinderGeometry(1,1,1,12):type==='ring'?new T.TorusGeometry(1,.025,4,32):new T.BoxGeometry(1,1,1));return geometries.get(type);}
function part(parent,type,color,x,y,z,sx=1,sy=1,sz=1,rotation=0,glow=false){const m=new T.Mesh(geom(type),material(color,glow));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.rotation.y=rotation;m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function fixed(type,color,x,y,z,sx,sy,sz,rotation=0,glow=false){const key=type+color+glow;if(!buckets.has(key))buckets.set(key,{type,color,glow,matrices:[]});const o=new T.Object3D();o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.rotation.y=rotation;o.updateMatrix();buckets.get(key).matrices.push(o.matrix.clone());}
function flush(){for(const b of buckets.values()){const m=new T.InstancedMesh(geom(b.type),material(b.color,b.glow),b.matrices.length);b.matrices.forEach((v,i)=>m.setMatrixAt(i,v));m.castShadow=true;m.receiveShadow=true;m.computeBoundingSphere();scene.add(m);}buckets.clear();}
function seeded(n){let x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);}
function sign(text,x,y,z,color='#fff1d6',size=7){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#173e49';ctx.beginPath();ctx.roundRect(4,8,504,108,20);ctx.fill();ctx.strokeStyle='#e0cf9c';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle=color;ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const texture=new T.CanvasTexture(c),sprite=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,depthTest:true}));sprite.position.set(x,y,z);sprite.scale.set(size,size/4,1);scene.add(sprite);return sprite;}
function pine(x,z,h,color,snow=false){fixed('cylinder','#826f59',x,2+h*.22,z,.45,h*.5,.45);for(let k=0;k<3;k++)fixed('cone',snow&&k===2?'#e6f2f1':color,x,2+h*(.43+k*.17),z,h*(.3-k*.045),h*.45,h*(.3-k*.045));game.colliders.push({x,z,r:.7});}
function palm(x,z,h){fixed('cylinder','#a78864',x,2+h*.45,z,.4,h,.4);for(let k=0;k<6;k++){const a=k*Math.PI/3;fixed('rock','#64a67f',x+Math.sin(a)*2,2+h,z+Math.cos(a)*2,2.8,.3,1.1,a);}fixed('sphere','#bb945d',x,2+h-.6,z,.5,.5,.5);game.colliders.push({x,z,r:.7});}
function cabin(i,x,z,w=6,d=5){const col=i.accent;fixed('box','#e8dabb',x,4,z,w,4,d);fixed('box',col,x,6.1,z,w+.6,.4,d+.6);fixed('roof',col,x,7.15,z,(w+1)/1.4,2.5,(d+1)/1.4,Math.PI/4);fixed('box','#6d827e',x,3.5,z+d/2+.03,1.3,3,.08);for(const dx of [-w*.31,w*.31]){fixed('box','#a1d9d4',x+dx,4.5,z+d/2+.05,1.25,1.15,.1);fixed('box','#c8ac82',x+dx,3.85,z+d/2+.1,1.55,.15,.2);}game.colliders.push({x,z,r:Math.max(w,d)*.55});}
function npc(x,z,color,hat,name){const g=makeAvatar(color,hat);g.position.set(x,3.3,z);g.rotation.y=0;scene.add(g);sign(name,x,6.7,z,'#f5ddac',5.5);return g;}
function buildIsland(i,index){
 fixed('cylinder',i.sand,i.x,-.5,i.z,i.r+1,5,i.r+1);fixed('cylinder',i.color,i.x,1.5,i.z,i.r,1,i.r);
 for(let n=0;n<18;n++){const a=n/18*Math.PI*2,r=i.r+seeded(index*300+n)*2;fixed('rock',i.sand,i.x+Math.sin(a)*r,.5,i.z+Math.cos(a)*r,2+seeded(n)*2,1.2,2.5,a);}
 const rim=new T.Mesh(geom('ring'),new T.MeshBasicMaterial({color:'#d2e9da',transparent:true,opacity:.45}));rim.rotation.x=-Math.PI/2;rim.position.set(i.x,.08,i.z);rim.scale.set(i.r+2.5,i.r+2.5,1);scene.add(rim);
 for(let n=0;n<20;n++){const a=seeded(n+index*50)*Math.PI*2,r=8+seeded(n*4+index)*19,x=i.x+Math.sin(a)*r,z=i.z+Math.cos(a)*r;if(z>i.z+12&&Math.abs(x-i.x)<15||dist({x,z},{x:i.x+12,z:i.z-8})<4)continue;
 if(i.biome==='tropical')palm(x,z,7+seeded(n)*3);else if(i.biome==='snow')pine(x,z,8+seeded(n)*4,'#7ab0b0',true);else if(i.biome==='swamp')pine(x,z,9,'#66867d');else if(i.biome==='volcano'){fixed('rock','#545760',x,3,z,3,3,3);if(n%3===0)fixed('rock',i.accent,x,4,z,1,.25,1,0,true);}else pine(x,z,7+seeded(n)*3,i.biome==='ruins'?'#698f8c':'#699367');
 }
 // A continuous collision-matched walkway connects the dock and town.
 for(let k=0;k<22;k++){const z=i.z+i.r-5+k;fixed('box','#bca17b',i.x,2.2,z,6,.35,.86);if(k%4===0){for(const x of [-3,3]){fixed('cylinder','#927b60',i.x+x,1,z,.22,4,.22);fixed('sphere','#eeddb2',i.x+x,3.2,z,.32,.32,.32);}}}
 fixed('box','#d1c29e',i.x,2.05,i.z+21,10,.15,14);cabin(i,i.x-9,i.z+16);cabin(i,i.x+9,i.z+17,6,6);
 fixed('box','#997957',i.x-9,2.7,i.z+22,7,1,2);for(let n=0;n<6;n++)fixed('box',n%2?'#d8e8cf':i.accent,i.x-12+n,6.2,i.z+23,1, .3,5);for(const x of [-12, -6])fixed('cylinder','#9b8466',i.x+x,4.3,i.z+24,.15,4.5,.15);
 npc(i.x-8,i.z+24,'#758cad','#e7cb8f',index===0?'Mara · Fishmonger':'Port Merchant');npc(i.x+8,i.z+25,'#b88a73','#80b7a8','Outfitters');sign(i.name,i.x,5.1,i.z+i.r+3,'#f9e1b8',8);
 // Each island has its own landmark, silhouette and treasure.
 if(i.biome==='harbor'){fixed('cylinder','#eee0c2',i.x-13,10,i.z-8,3.1,16,3.1);fixed('cylinder','#d68763',i.x-13,12,i.z-8,3.2,2,3.2);fixed('cylinder','#678b8e',i.x-13,18.8,i.z-8,3.4,1.2,3.4);fixed('cylinder','#f4d08b',i.x-13,20,i.z-8,2.1,2,2.1,0,true);fixed('cone','#d8805f',i.x-13,22,i.z-8,3.6,2,3.6);game.colliders.push({x:i.x-13,z:i.z-8,r:3.5});}
 if(i.biome==='tropical'){for(let n=0;n<7;n++){fixed('rock',n%2?'#e99596':'#e9b882',i.x+i.r+2, .3,i.z-12+n*3,2,2,2);}fixed('roof','#e9b37c',i.x-6,7,i.z-10,6,8,6,Math.PI/4);}
 if(i.biome==='snow'){fixed('cone','#94bfcf',i.x,10,i.z-10,13,17,12);fixed('cone','#eaf3f1',i.x,15,i.z-10,7,7,6.5);for(let n=0;n<5;n++)fixed('cone','#b3e7e8',i.x+10+n*2,4,i.z+3,1,4+n%3,1,0,true);game.colliders.push({x:i.x,z:i.z-10,r:11});}
 if(i.biome==='volcano'){fixed('cone','#4e505a',i.x,11,i.z-8,14,20,14);fixed('cylinder','#f7a366',i.x,20,i.z-8,3.2,.6,3.2,0,true);fixed('cone','#f8cb7c',i.x,20.5,i.z-8,2,1,2,0,true);game.colliders.push({x:i.x,z:i.z-8,r:12});}
 if(i.biome==='ruins'){for(let n=0;n<6;n++){const a=n*Math.PI/3;fixed('cylinder','#b5c9bb',i.x+Math.sin(a)*9,7,i.z-7+Math.cos(a)*9,1,10,1);fixed('box','#d1d2b7',i.x+Math.sin(a)*9,12,i.z-7+Math.cos(a)*9,3,.6,3);}fixed('rock','#baa0ef',i.x,5,i.z-7,2.6,4,2.6,0,true);game.colliders.push({x:i.x,z:i.z-7,r:3});}
 if(i.biome==='swamp'){fixed('rock','#667d79',i.x-2,5,i.z-9,9,5,8);fixed('box','#213d45',i.x-2,3.8,i.z-1.1,4,3.5,.2);game.colliders.push({x:i.x-2,z:i.z-9,r:8});}
 fixed('box','#7f6750',i.x+12,2.75,i.z-8,2.1,1.3,1.5);fixed('box','#e1bd70',i.x+12,3.5,i.z-8,2.25,.4,1.6);for(const dx of [-.65,.65])fixed('box','#e6c475',i.x+12+dx,2.8,i.z-7.2,.15,1.5,.1);sign('Treasure',i.x+12,5,i.z-8,'#f0d38a',3.8);
 for(let n=0;n<12;n++){const a=seeded(n*13+index)*Math.PI*2,r=5+seeded(n+57)*18;fixed('rock',n%2?'#e3ce91':'#d5a7b0',i.x+Math.sin(a)*r,2.15,i.z+Math.cos(a)*r,.25,.18,.25);}
}
function makeAvatar(color='#e8a068',hat='#cedcae'){
 const g=new T.Group();part(g,'box',color,0,0,0,1.5,1.6,.85);part(g,'box','#e8dab7',0,1.2,0,1.14,1.13,1.02);part(g,'cylinder',hat,0,1.87,0,.84,.16,.84);part(g,'cylinder',hat,0,2.08,0,.58,.32,.58);part(g,'box','#344d4a',0,2.01,.62,.8,.09,.1);
 for(const x of [-.24,.24])part(g,'sphere','#223936',x,1.22,.515,.07,.085,.04);part(g,'box','#ab785b',0,.97,.535,.22,.035,.04);const legs=[],arms=[];
 for(const x of [-.43,.43]){const leg=new T.Group();leg.position.set(x,-.63,0);part(leg,'box','#486675',0,-.45,0,.5,.95,.56);part(leg,'box','#394c4e',0,-.95,.1,.59,.28,.8);g.add(leg);legs.push(leg);}for(const x of [-.95,.95]){const arm=new T.Group();arm.position.set(x,.5,0);part(arm,'box',color,0,-.33,0,.47,.9,.52);part(arm,'box','#e8dab7',0,-.86,0,.45,.38,.5);g.add(arm);arms.push(arm);}part(g,'box','#b6a583',0,0,-.63,1.1,1.25,.45);part(g,'box','#d8ca9e',0,.25,-.91,.8,.12,.12);g.userData={legs,arms};return g;
}
function makeBoat(color){const g=new T.Group();part(g,'box',color,0,.35,0,3.2,1.2,6.5);part(g,'box','#d1bd8c',0,1.04,0,2.6,.3,5.8);part(g,'box',color,-1.55,1.25,0,.22,.6,6.2);part(g,'box',color,1.55,1.25,0,.22,.6,6.2);part(g,'roof',color,0,.35,3.8,2.3,1.2,2.2,Math.PI/4);for(const z of [-1.7,1.5])part(g,'box','#8d7155',0,1.35,z,2.7,.2,.7);part(g,'box','#3c5963',0,.8,-3.4,1.1,1.5,.8);part(g,'cylinder','#e1cb9c',-.9,3.1,-1,.07,4.4,.07);part(g,'box','#c9e4ce',-.3,4.7,-1,1.2,.65,.05);return g;}
function fishSVG(f,mutation='normal',unknown=false){
 const m=MUTATIONS.find(x=>x.id===mutation),color=unknown?'#51727b':m?.color||f.color,outline=unknown?'#3c5f69':'#233f49',eel=f.shape==='eel',ray=f.shape==='ray',whale=['whale','narwhal'].includes(f.shape);let body='';
 if(ray)body='<path d="M48 53 Q65 4 108 35 Q150 5 186 56 Q147 61 113 70 Q76 65 48 53Z"/><path d="M108 58 Q90 90 45 91" fill="none" stroke-width="5"/>';
 else if(eel)body='<path d="M183 34 Q150 6 108 43 T35 65 Q91 88 130 63 Q159 41 188 59Z"/>';
 else body='<path d="M57 48 L28 26 L32 75 L58 60Z"/><ellipse cx="119" cy="49" rx="68" ry="'+(whale?'35':'29')+'"/><path d="M92 23 L112 '+(f.shape==='shark'?'0':'10')+' L137 22M94 69 L119 85 L134 72"/>';
 if(f.shape==='sword'||f.shape==='narwhal')body+='<path d="M180 37 L216 29 L185 47Z"/>';
 if(f.shape==='gator')body+='<path d="M164 37 L216 46 L211 62 L165 65Z"/>';
 const cat=/Catfish|Bullhead/.test(f.name),clown=f.name==='Clownfish';
 return `<svg viewBox="0 0 220 100" role="img" aria-label="${unknown?'Undiscovered fish':escape(f.name)}"><ellipse cx="112" cy="88" rx="62" ry="6" fill="#082b3d22"/><g fill="${color}" stroke="${outline}" stroke-width="2" stroke-linejoin="round">${body}</g>${clown&&!unknown?'<path d="M83 25 Q72 48 86 73M132 21 Q122 49 137 75" fill="none" stroke="#f9f1d8" stroke-width="9"/>':''}${unknown?'<text x="112" y="62" text-anchor="middle" fill="#b2c6c9" font-size="32">?</text>':`<circle cx="${ray?124:166}" cy="42" r="7" fill="#f4f2d9"/><circle cx="${ray?126:168}" cy="42" r="3.4" fill="#183d48"/><path d="M171 60 Q180 65 184 56" fill="none" stroke="#385d60" stroke-width="2"/><path d="M112 43 L96 60 L129 54Z" fill="#eff7d940"/>${cat?'<path d="M180 59 Q184 80 206 76M180 59 Q174 82 159 78" fill="none" stroke="#bad5bc" stroke-width="2"/>':''}`}</svg>`;
}
function makeFish(f){const g=new T.Group(),col=f.color,ray=f.shape==='ray',eel=f.shape==='eel';part(g,'sphere',col,0,0,0,eel?2.3:1.4,ray?.15:eel?.32:.65,ray?1.5:.45);const tail=part(g,'cone',col,eel?-2.3:-1.6,0,0,ray?.2:.7,eel?1.2:.9,.2);tail.rotation.z=-Math.PI/2;if(!ray){part(g,'cone',col,-.1,.65,0,.3,.7,.15);}if(['sword','narwhal','gator'].includes(f.shape)){const nose=part(g,'cone',col,1.8,.1,0,.13,1.3,.13);nose.rotation.z=-Math.PI/2;}for(const z of [-.43,.43]){part(g,'sphere','#f7f0cb',.82,.13,z,.15,.15,.06);part(g,'sphere','#223f44',.85,.13,z*1.12,.07,.08,.04);}g.scale.setScalar(.65);return g;}
function atmosphere(){
 for(let n=0;n<40;n++){const drop=part(scene,'cylinder','#b9dada',0,0,0,.018,1.2,.018);drop.visible=false;rain.push(drop);}
 for(let n=0;n<4;n++){const c=document.createElement('canvas');c.width=128;c.height=128;const ctx=c.getContext('2d'),grad=ctx.createLinearGradient(0,0,0,128);grad.addColorStop(0,'#80eedb00');grad.addColorStop(.5,n%2?'#c7a4ed80':'#80eedb90');grad.addColorStop(1,'#80eedb00');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);const sprite=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),transparent:true,depthWrite:false}));sprite.scale.set(65,34,1);scene.add(sprite);aurora.push(sprite);}
 for(let n=0;n<25;n++){const star=part(scene,'sphere','#edf3d1',0,0,0,.1,.1,.1,0,true);stars.push(star);}
 for(let n=0;n<6;n++){const g=new T.Group();const left=part(g,'box','#d8e2c9',-.5,0,0,1,.09,.28),right=part(g,'box','#d8e2c9',.5,0,0,1,.09,.28);part(g,'sphere','#e4e5cd',0,0,0,.2,.15,.25);g.userData={left,right};scene.add(g);birds.push(g);}
 for(let n=0;n<4;n++){const ring=new T.Mesh(geom('ring'),new T.MeshBasicMaterial({color:'#d3e6d3',transparent:true,opacity:.4}));ring.rotation.x=-Math.PI/2;scene.add(ring);wake.push(ring);}
 lineTube=part(scene,'cylinder','#dfdfb8',0,0,0,.012,1,.012);lineTube.visible=false;
}

function init(){try{
 const options={antialias:true,alpha:false,powerPreference:'high-performance'};let context;try{context=canvas.getContext('webgl2',options)||canvas.getContext('webgl',options);if(!context)throw Error('No GPU');renderer=new T.WebGLRenderer({canvas,context,...options});}catch{renderer=new WobbleSoftwareRenderer({canvas});}
 document.body.dataset.renderer=renderer.isSoftwareRenderer?'software':'webgl';renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.type=T.PCFSoftShadowMap;
 scene=new T.Scene();scene.background=new T.Color('#b9d8d4');scene.fog=new T.Fog('#b9d8d4',75,245);camera=new T.PerspectiveCamera(55,innerWidth/innerHeight,.2,650);
 scene.add(new T.HemisphereLight('#f6f3d8','#709c9a',2.2));sun=new T.DirectionalLight('#fff0c7',2);sun.position.set(-35,60,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-38;sun.shadow.camera.right=38;sun.shadow.camera.top=38;sun.shadow.camera.bottom=-38;sun.shadow.camera.far=150;sun.shadow.bias=-.0008;scene.add(sun);scene.add(sun.target);
 const seaMat=new T.MeshStandardMaterial({color:'#4d94a0',roughness:.6,metalness:.12,flatShading:true});for(let x=-4;x<=4;x++)for(let z=-4;z<=4;z++){const mesh=new T.Mesh(new T.PlaneGeometry(90,90,3,3),seaMat);mesh.rotation.x=-Math.PI/2;mesh.position.set(x*90,0,z*90);mesh.receiveShadow=true;scene.add(mesh);water.push(mesh);}
 ISLANDS.forEach(buildIsland);flush();atmosphere();
 for(let k=0;k<20;k++){const g=new T.Group();for(let n=0;n<4;n++)part(g,'sphere','#ebeee1',n*5,Math.sin(n)*1,0,5,2,3);g.position.set(seeded(k)*700-350,45+seeded(k+40)*22,seeded(k+20)*700-350);scene.add(g);clouds.push(g);}
 avatar=makeAvatar(game.save.prefs.color);scene.add(avatar);boatModel=makeBoat(BOATS.find(x=>x.id===game.save.boat).color);boatModel.visible=false;scene.add(boatModel);
 rodModel=new T.Group();const shaft=part(rodModel,'cylinder',RODS[0].color,0,1.35,0,.045,3.8,.045);shaft.rotation.x=.38;part(rodModel,'sphere','#d5d5b0',0,-.1,0,.16,.2,.18);avatar.userData.arms[1].add(rodModel);rodModel.position.set(0,-.8,.25);rodModel.rotation.x=-1.2;
 const lineGeo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]);line=new T.Line(lineGeo,new T.LineBasicMaterial({color:'#ecebc7',transparent:true,opacity:.7}));line.visible=false;scene.add(line);bobber=new T.Group();part(bobber,'sphere','#efd4a4',0,0,0,.16,.2,.16);part(bobber,'sphere','#d87562',0,.17,0,.13,.12,.13);scene.add(bobber);bobber.visible=false;
 setupInput();resize();updateHUD();parent.postMessage({type:'pocketvm-fisch-ready'},'*');requestAnimationFrame(frame);
 }catch(e){$('error').hidden=false;$('error-text').textContent=e.message||'Unable to open the ocean.';console.error(e);}}
function sound(kind){if(!game.save.prefs.sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime,notes=kind==='catch'?[523,659,784,1047]:kind==='bite'?[880,660]:kind==='coins'?[660,880,990]:kind==='escape'?[330,220]:[420];notes.forEach((freq,i)=>{const o=audio.createOscillator(),gain=audio.createGain();o.type=kind==='bite'?'triangle':'sine';o.frequency.setValueAtTime(freq,now+i*.085);gain.gain.setValueAtTime(0,now+i*.085);gain.gain.linearRampToValueAtTime(.07,now+i*.085+.012);gain.gain.exponentialRampToValueAtTime(.001,now+i*.085+.23);o.connect(gain).connect(audio.destination);o.start(now+i*.085);o.stop(now+i*.085+.25);});}catch{}}
function persist(){try{const data=game.export();localStorage.setItem('pocketvm.game.fisch',JSON.stringify(data));}catch{}parent.postMessage({type:'pocketvm-fisch-save',data:game.export()},'*');}
function toast(text,seconds=4){$('toast').textContent=text;$('toast').hidden=false;toastTime=seconds;}
function clearInput(){keys.clear();held.reel=false;held.jump=false;castPointer=null;look=null;stickPointer=null;joystick.x=joystick.z=0;$('stick').style.transform='';if(game.fishing.state==='casting')game.cancel();}
function touchMode(){const mode=game.save.prefs.touch,on=mode==='on'||mode==='auto'&&((navigator.maxTouchPoints||0)>0||matchMedia('(pointer:coarse)').matches);document.body.classList.toggle('touch',on);$('touch-controls').hidden=!on;}
function resize(){const w=innerWidth,h=innerHeight;renderer.setPixelRatio(renderer.isSoftwareRenderer?Math.min(.8,900/w):game.save.prefs.quality==='low'?1:Math.min(devicePixelRatio,game.save.prefs.quality==='high'?2:1.5));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.shadowMap.enabled=!renderer.isSoftwareRenderer&&game.save.prefs.quality!=='low';touchMode();}
function begin(){playing=true;$('intro').hidden=true;clearInput();sound('start');toast(game.save.stats.catches?'Welcome back. Your horizon is waiting.':'Hold the fishing button. Release in the green zone. Then keep the gold fish inside your mint bar.',7);$('cast').focus();}
function castDown(){if(!playing||panel)return;const state=game.fishing.state;if(state==='idle'){if(game.startCast())held.reel=true;}else if(state==='waiting')game.shake();else if(state==='reeling')held.reel=true;}
function castUp(){held.reel=false;if(game.fishing.state==='casting')game.releaseCast();}
function use(){if(!playing||panel)return;if(game.openChest()){persist();return;}if(game.nearPort())openPanel('shop');else if(game.boat)game.launchBoat();else toast('Find an island port to trade, or a treasure chest to open.');}
function setupInput(){
 $('play').addEventListener('click',begin);$('intro-help').addEventListener('click',()=>openPanel('help'));$('settings').addEventListener('click',()=>openPanel('settings'));$('quest-peek').addEventListener('click',()=>openPanel('quests'));$('minimap-box').addEventListener('click',()=>openPanel('map'));$('interact').addEventListener('click',use);$('touch-use').addEventListener('click',use);$('touch-boat').addEventListener('click',()=>{game.launchBoat();persist();});$('touch-jump').addEventListener('pointerdown',e=>{e.preventDefault();$('touch-jump').setPointerCapture(e.pointerId);held.jump=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('touch-jump').addEventListener(type,()=>held.jump=false);
 document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));
 $('close-panel').addEventListener('click',closePanel);$('overlay').addEventListener('click',e=>{if(e.target===$('overlay'))closePanel();});
 $('cast').addEventListener('pointerdown',e=>{e.preventDefault();if(castPointer!==null)return;castPointer=e.pointerId;$('cast').setPointerCapture(e.pointerId);castDown();});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('cast').addEventListener(type,e=>{if(e.pointerId!==castPointer)return;castPointer=null;castUp();});
 canvas.addEventListener('pointerdown',e=>{if(panel||!playing)return;look={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!look||look.id!==e.pointerId)return;const s=game.save.prefs.sensitivity;yaw-=(e.clientX-look.x)*.006*s;pitch=clamp(pitch+(e.clientY-look.y)*.004*s,.15,1.15);look.x=e.clientX;look.y=e.clientY;});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(look?.id===e.pointerId)look=null;});canvas.addEventListener('wheel',e=>{if(panel)return;e.preventDefault();zoom=clamp(zoom+e.deltaY*.012,7,28);},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
 $('joystick').addEventListener('pointerdown',e=>{if(stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;$('joystick').setPointerCapture(e.pointerId);moveStick(e);});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)moveStick(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(type,e=>{if(e.pointerId!==stickPointer)return;stickPointer=null;joystick.x=joystick.z=0;$('stick').style.transform='';});
 addEventListener('keydown',e=>{const tag=e.target?.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag)&&e.code!=='Escape')return;if(panel){if(e.code==='Escape'){e.preventDefault();closePanel();}if(e.code==='Tab'){const els=[...$('overlay').querySelectorAll('button,input,select,[tabindex="0"]')].filter(x=>!x.disabled),first=els[0],end=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end?.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first?.focus();}}return;}
 if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;keys.add(e.code);if(!playing){if(e.code==='Enter')begin();return;}if(e.code==='Space')castDown();if(e.code==='KeyB'){game.launchBoat();persist();}if(e.code==='KeyE')use();const m={KeyI:'bag',KeyJ:'journal',KeyM:'map',KeyR:'shop',KeyQ:'quests',Escape:'settings'};if(m[e.code])openPanel(m[e.code]);if(e.code==='KeyX')game.cancel();});
 addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')castUp();});addEventListener('blur',()=>{focused=false;clearInput();persist();});addEventListener('focus',()=>{focused=true;last=0;});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();persist();}});addEventListener('pagehide',persist);addEventListener('resize',()=>{clearInput();resize();});window.visualViewport?.addEventListener('resize',resize);
 $('panel-body').addEventListener('click',panelAction);$('panel-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b){sub=b.dataset.tab;renderPanel();}});$('panel-body').addEventListener('change',panelChange);$('panel-body').addEventListener('input',e=>{if(e.target.id==='fish-search'){search=e.target.value;renderFishList();}});$('panel-body').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.destination){e.preventDefault();mapTarget=e.target.dataset.destination;renderPanel();}});
 }
function moveStick(e){const r=$('joystick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dz=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dz),max=r.width*.31,scale=len>max?max/len:1;joystick.x=dx*scale/max;joystick.z=dz*scale/max;$('stick').style.transform=`translate(${dx*scale}px,${dz*scale}px)`;}
function input(){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joystick.x,z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joystick.z;
 const pads=navigator.getGamepads?.(),pad=pads&&[...pads].find(p=>p?.connected);if(pad){x+=Math.abs(pad.axes[0])>.16?pad.axes[0]:0;z+=Math.abs(pad.axes[1])>.16?pad.axes[1]:0;yaw-=Math.abs(pad.axes[2])>.18?pad.axes[2]*.035:0;pitch=clamp(pitch+(Math.abs(pad.axes[3])>.18?pad.axes[3]*.022:0),.15,1.15);const reel=!!pad.buttons[0]?.pressed;if(reel&&!held.pad){castDown();}if(!reel&&held.pad)castUp();held.pad=reel;}
 const dx=x*Math.cos(yaw)+z*Math.sin(yaw),dz=-x*Math.sin(yaw)+z*Math.cos(yaw);return{x:dx,z:dz,forward:-z,turn:x,jump:held.jump||keys.has('ShiftRight'),sprint:keys.has('ShiftLeft'),reel:held.reel};}
function events(){for(const e of game.events.splice(0)){
 if(e.type==='notice')toast(e.text);if(e.type==='cast'){sound('start');if(e.perfect)toast('Perfect cast · +15% catch value',2);}if(e.type==='bite'){sound('bite');toast('Fish on! Hold to move right. Release to move left.',3);navigator.vibrate?.(35);}if(e.type==='catch'){sound('catch');catchTime=6;showCatch(e);persist();navigator.vibrate?.([25,35,25]);}if(e.type==='escape'){sound('escape');toast('It slipped away. Keep the gold marker inside your mint bar.',5);persist();}if(e.type==='island'){toast('Discovered '+e.island.name+' · +80 XP',5);sound('catch');persist();}if(e.type==='weather')toast(e.weather==='aurora'?'Aurora! Rare fish are more likely across the sea.':e.weather==='storm'?'A storm is rolling in. Giants stir at Ember Reach.':'The weather has changed to '+e.weather+'.');if(e.type==='treasure'){sound('coins');toast('Treasure! +'+e.coins+' coins and an enchantment relic.',5);persist();}if(e.type==='unlock')toast(e.text,8);if(e.type==='relic')toast('An enchantment relic came up with your catch!',4);if(e.type==='bump')sound('escape');} }
function showCatch(e){$('catch-card').hidden=false;$('catch-rarity').innerHTML=RARITIES[e.species.rarity]+(e.fresh?'<span class="new">NEW SPECIES</span>':'');$('catch-art').innerHTML=fishSVG(e.species,e.catch.mutation);const m=MUTATIONS.find(m=>m.id===e.catch.mutation);$('catch-title').textContent=(m.name?m.name+' ':'')+e.species.name;$('catch-info').textContent=e.catch.weight.toFixed(2)+' kg · '+e.catch.value.toLocaleString()+' coins'+(e.perfect?' · Perfect cast':'');if(fishDisplay)scene.remove(fishDisplay);fishDisplay=makeFish(e.species);scene.add(fishDisplay);}
function updateHUD(){const s=game.save,i=game.island(),hour=Math.floor(s.clock/30),period=game.isNight()?'Night':hour<12?'Morning':'Afternoon';$('coins').textContent=s.coins.toLocaleString();$('level').textContent=game.level();$('place').querySelector('strong').textContent=i.name;$('weather').textContent=({clear:'☀',rain:'☂',fog:'≋',storm:'ϟ',aurora:'✧'}[s.weather])+' '+s.weather[0].toUpperCase()+s.weather.slice(1)+' · '+period;const destination=ISLANDS.find(x=>x.id===mapTarget);$('compass').textContent=destination.name.toUpperCase()+' · '+Math.round(dist(game.player,destination))+' m'+(game.boat?' · '+Math.round(Math.abs(game.boat.speed))+' kn':'');
 const q=QUESTS.find(q=>!s.claimed.includes(q.id));if(q){$('quest-peek').querySelector('strong').textContent=q.name;$('quest-peek').querySelector('em').textContent=q.text+' '+Math.min(q.goal,game.progress(q))+' / '+q.goal;}else{$('quest-peek').querySelector('strong').textContent='Beyond the horizon';$('quest-peek').querySelector('em').textContent=Object.keys(s.seen).length+' / 60 species discovered';}
 const f=game.fishing,state=f.state;$('fishing').hidden=state==='idle'||!playing;$('cast-track').hidden=state!=='casting';$('wait-wave').hidden=state!=='waiting';$('reel-track').hidden=state!=='reeling';$('progress-track').hidden=state!=='reeling';
 const labels={idle:['Hold to cast','Release in the green zone'],casting:['Release to cast','Aim for the green zone'],waiting:['Shake the line','Tap to attract a bite'],reeling:['Hold to reel','Hold → right · Release → left']};$('cast').innerHTML=labels[state][0]+'<span>'+labels[state][1]+'</span>';
 $('fish-label').textContent=state==='casting'?'A little patience. A perfect cast.':state==='waiting'?'Something is watching your bait…':'Keep the fish inside your bar';$('fish-hint').textContent=state==='reeling'?'Hold to move right. Release to move left.':'Your equipped rod: '+game.rod().name;$('fish-stage').textContent=state==='reeling'?Math.round(f.progress*100)+'%':state.toUpperCase();$('bottom-hint').textContent=state==='waiting'?'Tap the fishing button or Space to shake the rod':state==='reeling'?'Gold = fish · Mint = your rod’s control bar':'Release in the green zone for extra value';
 if(state==='casting')$('cast-meter').style.width=f.power*100+'%';if(state==='reeling'){const width=game.rod().control;$('reel-bar').style.width=width*100+'%';$('reel-bar').style.left=(f.bar-width/2)*100+'%';$('fish-marker').style.left=f.fish*100+'%';$('reel-progress').style.width=clamp(f.progress,0,1)*100+'%';$('reel-bar').style.background=f.inside?'#b3eed09c':'#b3eed044';}
 const chest={x:i.x+12,z:i.z-8},nearChest=dist(game.player,chest)<4;$('interact').textContent=nearChest?'Open treasure · E':game.boat?'Dock / Trade · E':game.nearPort()?'Trade · E':'Explore the shore';$('touch-use').textContent=nearChest?'Chest':'Trade';$('touch-boat').textContent=game.boat?'Dock':'Boat';drawMinimap();}
function drawMinimap(){const ctx=$('minimap').getContext('2d'),size=240,p=game.player;ctx.clearRect(0,0,size,size);ctx.fillStyle='#184554';ctx.fillRect(0,0,size,size);ctx.strokeStyle='#6b969341';for(let k=0;k<5;k++){ctx.beginPath();ctx.arc(120,120,22+k*23,0,Math.PI*2);ctx.stroke();}const scale=.28;
 for(const i of ISLANDS){const x=120+(i.x-p.x)*scale,z=120+(i.z-p.z)*scale;ctx.fillStyle=game.save.visited.includes(i.id)?i.color:'#6d8a88';ctx.beginPath();ctx.arc(x,z,Math.max(5,i.r*scale),0,Math.PI*2);ctx.fill();ctx.fillStyle='#d6d9b2';ctx.fillRect(x-1,z+i.r*scale,2,5);if(i.id===mapTarget){ctx.strokeStyle='#f3d49a';ctx.beginPath();ctx.arc(x,z,i.r*scale+4,0,Math.PI*2);ctx.stroke();}}
 ctx.save();ctx.translate(120,120);ctx.rotate(-game.player.heading);ctx.fillStyle='#f6dc9c';ctx.beginPath();ctx.moveTo(0,9);ctx.lineTo(-5,-5);ctx.lineTo(5,-5);ctx.closePath();ctx.fill();ctx.restore();ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillStyle='#d1e7d8';ctx.fillText('N',120,19);}
function updateWorld(dt){animTime+=dt;const p=game.player,night=game.isNight(),storm=game.save.weather==='storm',bg=night?'#2b4869':storm?'#7f9baf':game.save.weather==='fog'?'#aec8c1':'#b9d8d4';scene.background.lerp(new T.Color(bg),.025);scene.fog.color.copy(scene.background);sun.intensity=night?.45:storm?1:2;sun.position.set(p.x-35,60,p.z+25);sun.target.position.set(p.x,0,p.z);
 avatar.position.set(p.x,p.y+(p.swimming?Math.sin(animTime*4)*.12:0),p.z);avatar.rotation.y=p.heading;avatar.userData.legs.forEach((l,i)=>l.rotation.x=Math.sin(animTime*9+i*Math.PI)*Math.min(.55,p.moving*.07));avatar.userData.arms[0].rotation.x=Math.sin(animTime*9)*Math.min(.4,p.moving*.04);avatar.userData.arms[1].rotation.x=game.fishing.state==='reeling'?-.7+Math.sin(animTime*12)*.07:game.fishing.state==='casting'?-.9:-.3;
 const color=game.save.prefs.color;avatar.children[0].material=material(color);for(const a of avatar.userData.arms)a.children[0].material=material(color);rodModel.children[0].material=material(game.rod().color);
 boatModel.visible=!!game.boat;if(game.boat){boatModel.position.set(game.boat.x,Math.sin(animTime*2)*.12,game.boat.z);boatModel.rotation.set(Math.sin(animTime)*.015,game.boat.heading,Math.sin(animTime*1.6)*.025);boatModel.children[0].material=material(BOATS.find(x=>x.id===game.save.boat).color);}
 for(let k=0;k<water.length;k++)water[k].position.y=Math.sin(animTime*.75+k*.7)*.035;for(const cloud of clouds){cloud.position.x+=dt*.5;if(cloud.position.x>400)cloud.position.x=-400;}
 const f=game.fishing,hasLine=f.state==='waiting'||f.state==='reeling';bobber.visible=hasLine;line.visible=hasLine;lineTube.visible=hasLine&&renderer.isSoftwareRenderer;if(hasLine){const i=game.island(),dx=p.x-i.x,dz=p.z-i.z,a=game.boat?p.heading:Math.atan2(dx,dz),distance=8+f.cast*7;bobber.position.set(p.x+Math.sin(a)*distance,.12+Math.sin(animTime*3)*.08,p.z+Math.cos(a)*distance);const arr=line.geometry.attributes.position.array;arr[0]=p.x;arr[1]=p.y+2.1;arr[2]=p.z;arr[3]=bobber.position.x;arr[4]=bobber.position.y;arr[5]=bobber.position.z;line.geometry.attributes.position.needsUpdate=true;line.geometry.computeBoundingSphere();const start=new T.Vector3(p.x,p.y+2.1,p.z),end=bobber.position.clone(),direction=end.clone().sub(start);lineTube.position.copy(start.add(end).multiplyScalar(.5));lineTube.scale.y=direction.length();lineTube.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),direction.normalize());}
 for(let n=0;n<rain.length;n++){const drop=rain[n];drop.visible=['rain','storm'].includes(game.save.weather);drop.position.set(p.x+(seeded(n+22)*30-15),2+((seeded(n)*20-animTime*13)%20+20)%20,p.z+(seeded(n+43)*30-15));drop.rotation.z=.15;}for(let n=0;n<aurora.length;n++){const a=aurora[n];a.visible=game.save.weather==='aurora';a.position.set(p.x-60+n*38,38+Math.sin(animTime*.2+n)*4,p.z-85);}for(let n=0;n<stars.length;n++){stars[n].visible=night;stars[n].position.set(p.x+(seeded(n)*160-80),32+seeded(n+20)*30,p.z-75+seeded(n+30)*60);}for(let n=0;n<birds.length;n++){const b=birds[n],a=animTime*.09+n;b.position.set(p.x+Math.sin(a)*35,15+Math.sin(a*2)*3,p.z+Math.cos(a)*35);b.rotation.y=-a;b.userData.left.rotation.z=Math.sin(animTime*5+n)*.25;b.userData.right.rotation.z=-Math.sin(animTime*5+n)*.25;}for(let n=0;n<wake.length;n++){const w=wake[n];w.visible=!!game.boat&&Math.abs(game.boat.speed)>2;w.position.set(p.x-Math.sin(p.heading)*(4+n*2),.09,p.z-Math.cos(p.heading)*(4+n*2));w.scale.set(1+n*.7,1+n*.7,1);w.material.opacity=.4-n*.08;}
 if(fishDisplay){fishDisplay.visible=catchTime>0;if(catchTime>0){fishDisplay.position.set(p.x+2.2,p.y+2+Math.sin(animTime*3)*.2,p.z);fishDisplay.rotation.y=animTime;}}
 const target=new T.Vector3(p.x,p.y+1.2,p.z),desired=new T.Vector3(p.x+Math.sin(yaw)*zoom*Math.cos(pitch),p.y+2+Math.sin(pitch)*zoom,p.z+Math.cos(yaw)*zoom*Math.cos(pitch));if(!playing){desired.set(p.x+Math.sin(animTime*.015)*19,p.y+10,p.z+18);target.set(p.x-2,p.y+3,p.z-14);}camera.position.lerp(desired,1-Math.exp(-dt*8));if(camera.position.y<3)camera.position.y=3;camera.lookAt(target);renderer.render(scene,camera);}
function frame(time){requestAnimationFrame(frame);const dt=last?Math.min(.1,(time-last)/1000):1/60;last=time;if(document.hidden)return;
 if(playing&&!panel&&focused){acc+=dt;let n=0;const control=input();while(acc>=1/60&&n++<7){game.step(1/60,control);acc-=1/60;}if(n>=7)acc=0;events();saveTime+=dt;if(saveTime>20){saveTime=0;persist();}}
 catchTime=Math.max(0,catchTime-dt);if(!catchTime)$('catch-card').hidden=true;toastTime=Math.max(0,toastTime-dt);if(!toastTime)$('toast').hidden=true;updateWorld(dt);uiTime+=dt;if(uiTime>.04){uiTime=0;updateHUD();}}
function openPanel(type){lastFocus=document.activeElement;clearInput();panel=type;$('overlay').hidden=false;if(type==='shop')sub='rods';if(type==='journal'){filter='all';search='';}renderPanel();$('close-panel').focus();persist();}
function closePanel(){panel=null;$('overlay').hidden=true;clearInput();last=0;acc=0;persist();lastFocus?.focus?.();}
function item(header,art,text,foot,tag=''){return `<article class="item">${tag?'<span class="tag">'+tag+'</span>':''}<div class="icon">${art}</div><h3>${header}</h3><p>${text}</p><footer>${foot}</footer></article>`;}
function rodArt(r){return `<svg viewBox="0 0 220 90" aria-hidden="true"><path d="M53 78 L157 7" stroke="${r.color}" stroke-width="6" stroke-linecap="round"/><path d="M147 13 Q170 43 187 61" fill="none" stroke="#e9e5bd" stroke-width="1"/><path d="M52 79 L79 61" stroke="#b59471" stroke-width="11" stroke-linecap="round"/><circle cx="82" cy="60" r="9" fill="#cdceb0"/><circle cx="83" cy="60" r="4" fill="#466b73"/><circle cx="187" cy="64" r="4" fill="#ed9d7e"/></svg>`;}
function boatArt(b){return `<svg viewBox="0 0 220 90" aria-hidden="true"><path d="M36 57 L191 57 L167 79 L62 79Z" fill="${b.color}" stroke="#153d48" stroke-width="2"/><path d="M58 57 L66 41 L157 41 L166 57" fill="#c9c6a0"/><path d="M100 44 V10" stroke="#e6d6aa" stroke-width="4"/><path d="M104 10 L135 15 L104 28Z" fill="#a7efc6"/><path d="M28 83 Q60 72 90 83 T158 83 T208 83" fill="none" stroke="#92c6c2" stroke-width="3"/></svg>`;}
function renderPanel(){const s=game.save,title={bag:'Your creel',journal:'The field journal',map:'A sea of possibilities',shop:'The Outfitters',quests:'Your next chapter',settings:'Make yourself at home',help:'Find your fishing rhythm'};$('panel-title').textContent=title[panel];$('panel-subtitle').textContent=panel==='bag'?s.bag.length+' catches · Locked fish stay with you':panel==='journal'?Object.keys(s.seen).length+' of 60 species · A story behind every scale':panel==='shop'?s.coins.toLocaleString()+' coins · '+s.relics+' relics · Level '+game.level():panel==='map'?'Sail to new islands. Fast travel to places you have discovered.':'Progress saves automatically on this device.';
 $('panel-tabs').innerHTML=panel==='shop'?['rods','bait','boats','enchants'].map(t=>`<button data-tab="${t}" class="${sub===t?'active':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join(''):'';
 const body=$('panel-body');body.scrollTop=0;
 if(panel==='bag'){body.innerHTML=`<div class="statline"><span><b>${s.bag.length}</b>fish in creel</span><span><b>${s.bag.filter(x=>!x.locked).reduce((a,x)=>a+x.value,0).toLocaleString()}</b>unlocked value</span><span><b>${s.stats.catches}</b>lifetime catches</span></div><div class="filter"><button class="gold" data-action="sell-all">Sell all unlocked fish</button><button data-action="lock-all">Lock all</button><button data-action="unlock-all">Unlock all</button></div>${!game.nearPort()?'<div class="notice">Sail or walk to an island port to sell your fish.</div>':''}<div class="grid">${s.bag.slice().reverse().map(x=>{const f=FISH.find(f=>f.id===x.fish),m=MUTATIONS.find(m=>m.id===x.mutation);return item(escape((m.name?m.name+' ':'')+f.name),fishSVG(f,x.mutation),x.weight.toFixed(2)+' kg · '+x.value.toLocaleString()+' coins',`<button data-action="lock" data-id="${x.uid}">${x.locked?'Unlock 🔒':'Keep / lock'}</button><button data-action="sell" data-id="${x.uid}" ${x.locked?'disabled':''}>Sell</button>`,RARITIES[f.rarity]);}).join('')}</div>${!s.bag.length?'<div class="empty">Your next great catch belongs here.<br>Close this panel and hold the fishing button at the dock.</div>':''}`;}
 if(panel==='journal'){body.innerHTML=`<div class="filter"><input id="fish-search" type="search" placeholder="Search a fish…" aria-label="Search fish" value="${escape(search)}"><select id="fish-filter" aria-label="Filter fish by island"><option value="all">All islands</option>${ISLANDS.map(i=>`<option value="${i.id}" ${filter===i.id?'selected':''}>${i.name}</option>`).join('')}<option value="found" ${filter==='found'?'selected':''}>Discovered only</option></select></div><div id="fish-list" class="grid"></div>`;renderFishList();}
 if(panel==='shop'){let html=!game.nearPort()?'<div class="notice">Browse from anywhere. Return to an island port to buy supplies or enchant your rod.</div>':'';
 if(sub==='rods')html+='<p class="lead">Control makes your reel bar wider. Resilience gives you time to recover. Luck brings rarer fish. All rods can catch the harbor’s biggest prize.</p><div class="grid">'+RODS.map(r=>{const owned=s.rods.includes(r.id),equipped=s.rod===r.id;return item(r.name,rodArt(r),`Luck ${Math.round(r.luck*100)}% · Control ${Math.round(r.control*100)}%<br>Resilience ${r.resilience.toFixed(2)} · Speed ${r.speed.toFixed(2)}<br>${r.collection?'Discover 35 species':r.price.toLocaleString()+' coins · Level '+r.level}`,`<button class="${equipped?'':'primary'}" data-action="rod" data-id="${r.id}" ${equipped||!owned&&(r.collection||game.level()<r.level||s.coins<r.price||!game.nearPort())?'disabled':''}>${equipped?'Equipped':owned?'Equip':r.collection?'Collection reward':'Buy & equip'}</button>`,owned?'OWNED':'NEW ROD');}).join('')+'</div>';
 if(sub==='bait')html+='<p class="lead">Each pack contains ten casts. A fish’s favourite bait multiplies its chance. Equipped bait is consumed only when you cast.</p><div class="filter"><button data-action="bait-equip" data-id="none">Fish without bait</button></div><div class="grid">'+BAITS.slice(1).map((b,i)=>item(b.name,`<span style="font-size:48px;color:${PALETTES_SAFE(i)}">${['〰','♧','♋','✧','♆','⋆'][i]}</span>`,`${s.bait[b.id]} in your tackle box · +${Math.round(b.luck*100)}% luck<br>${b.cost} coins / 10`, `<button data-action="bait-equip" data-id="${b.id}" ${!s.bait[b.id]||s.baitId===b.id?'disabled':''}>${s.baitId===b.id?'Equipped':'Equip'}</button><button class="primary" data-action="bait-buy" data-id="${b.id}" ${s.coins<b.cost||!game.nearPort()?'disabled':''}>Buy 10</button>`)).join('')+'</div>';
 if(sub==='boats')html+='<p class="lead">Your first skiff is free. Summon it beside a dock with B or the Boat button. W/S controls throttle; A/D steers. Come close to a dock and press Boat again to disembark.</p><div class="grid">'+BOATS.map(b=>item(b.name,boatArt(b),`${b.speed} knots · ${b.price?b.price.toLocaleString()+' coins':'Yours, on the house'}`,`<button class="primary" data-action="boat-buy" data-id="${b.id}" ${s.boat===b.id||!s.boats.includes(b.id)&&(s.coins<b.price||!game.nearPort())?'disabled':''}>${s.boat===b.id?'Equipped':s.boats.includes(b.id)?'Equip':'Buy & equip'}</button>`)).join('')+'</div>';
 if(sub==='enchants')html+='<p class="lead">Relics sometimes arrive with a fish. Treasure chests and the daily quest also award relics. Choose an enchantment; it applies to your equipped fishing gear and replaces your previous effect.</p><div class="grid">'+ENCHANTS.slice(1).map(e=>item(e.name,'<span style="font-size:48px;color:#bfabe8">✧</span>',e.id==='lucky'?'+65% luck':e.id==='steady'?'+8% control width':e.id==='swift'?'+0.3 reel and bite speed':'+40% catch value',`<button class="primary" data-action="enchant" data-id="${e.id}" ${s.enchant===e.id||s.relics<e.cost||!game.nearPort()?'disabled':''}>${s.enchant===e.id?'Active':e.cost+' relic'+(e.cost===1?'':'s')+' · Enchant'}</button>`)).join('')+'</div>';body.innerHTML=html;}
 if(panel==='quests'){body.innerHTML='<p class="lead">Mara’s field notes lead you from your first sprat to the Horizon Rod. Rewards are yours to claim, once per chapter.</p><div class="grid">'+QUESTS.map(q=>{const progress=Math.min(q.goal,game.progress(q)),done=s.claimed.includes(q.id);return `<article class="item"><span class="tag">${done?'COMPLETED':'FIELD NOTE '+(QUESTS.indexOf(q)+1)}</span><h3>${q.name}</h3><p>${q.text}</p><div class="bar"><i style="width:${progress/q.goal*100}%"></i></div><div class="values">${progress} / ${q.goal} · ${q.coins} coins · ${q.xp} XP</div><footer><button class="primary" data-action="claim" data-id="${q.id}" ${done||progress<q.goal?'disabled':''}>${done?'Reward claimed':'Claim reward'}</button></footer></article>`;}).join('')+`<article class="item"><span class="tag">DAILY TIDE · ${s.dayKey}</span><h3>Eight before sunset</h3><p>Land eight fish today. The calendar resets in UTC.</p><div class="bar"><i style="width:${Math.min(1,s.dailyCount/8)*100}%"></i></div><div class="values">${Math.min(8,s.dailyCount)} / 8 · 450 coins · 1 relic</div><footer><button class="gold" data-action="claim" data-id="daily" ${s.dailyCount<8||s.claimed.includes('daily')?'disabled':''}>${s.claimed.includes('daily')?'Reward claimed':'Claim daily reward'}</button></footer></article></div>`;}
 if(panel==='map')renderMap();
 if(panel==='settings'){const prefs=s.prefs;body.innerHTML=`<div class="setting"><div><b>Sound effects</b><p>Soft cast, bite, catch and treasure cues.</p></div><input id="pref-sound" type="checkbox" ${prefs.sound?'checked':''} aria-label="Sound effects"></div><div class="setting"><div><b>Gentle fishing</b><p>Widens your rod’s control bar by 7%. Turn off for a tougher reel.</p></div><input id="pref-assist" type="checkbox" ${prefs.assist?'checked':''} aria-label="Gentle fishing"></div><div class="setting"><div><b>Graphics</b><p>Balanced is ideal for tablets and everyday laptops.</p></div><select id="pref-quality" aria-label="Graphics quality">${['high','balanced','low'].map(v=>`<option ${v===prefs.quality?'selected':''}>${v}</option>`).join('')}</select></div><div class="setting"><div><b>Touch controls</b><p>Joystick, camera drag, large reel and boat buttons.</p></div><select id="pref-touch" aria-label="Touch controls">${['auto','on','off'].map(v=>`<option ${v===prefs.touch?'selected':''}>${v}</option>`).join('')}</select></div><div class="setting"><div><b>Your jacket</b><p>A little colour for a big adventure.</p></div><input id="pref-color" type="color" value="${prefs.color}" aria-label="Jacket colour"></div><div class="setting"><div><b>Camera sensitivity</b><p>Drag anywhere in the world to look around.</p></div><input id="pref-sensitivity" type="range" min="0.4" max="2" step="0.1" value="${prefs.sensitivity}" aria-label="Camera sensitivity"></div><div class="filter" style="margin-top:22px"><button data-action="help">How to play</button><button data-action="rescue">Return to nearest dock</button><button data-action="fullscreen">Fullscreen</button></div><p class="lead">An original single-player PocketVM adventure inspired by Roblox’s Fisch. Your catches, discoveries, gear, quests, appearance and position save on this browser. Built with original models and sound, and Three.js (MIT).</p>`;}
 if(panel==='help')body.innerHTML=`<div class="help-grid"><article><h3>01 · Cast with purpose</h3><p>Start on the dock. Hold the big fishing button or <kbd>Space</kbd> to charge, then release in the green zone. A perfect cast adds 15% value. Tap to shake while waiting for a bite.</p></article><article><h3>02 · Learn the reel</h3><p>Keep the gold fish marker inside the mint bar. Hold to move your bar right; release to move it left. Small taps keep it steady. Fill the progress meter to land the fish. <kbd>X</kbd> cancels your line.</p></article><article><h3>03 · Find your way</h3><p>Move with <kbd>WASD / arrows</kbd>, or the touch joystick. Drag the world to look; scroll to zoom. <kbd>Left Shift</kbd> sprints and <kbd>Right Shift</kbd> jumps. The Chart sets a destination and lets you revisit discovered docks.</p></article><article><h3>04 · Sail beyond the harbor</h3><p>Press <kbd>B</kbd> or Boat at a dock to summon your free skiff. <kbd>W / S</kbd> accelerates / reverses; <kbd>A / D</kbd> turns. On touch, push the joystick up and move it sideways to steer. Press Boat near a dock to leave.</p></article><article><h3>05 · Make it a living</h3><p>Sell your creel at a port. Lock any fish you want to keep. Buy rods, bait and boats at the Outfitters. Claim quest rewards and find each island’s treasure. Relics enchant your rod.</p></article><article><h3>06 · A world that changes</h3><p>Weather changes every three minutes and a day lasts twelve minutes. Night, storms, fog and aurora attract special fish. Find favourite bait and conditions in the Bestiary. Discover 35 species to earn the Horizon Rod.</p></article></div>`;
 }
function PALETTES_SAFE(i){return['#d1a27c','#9ac594','#e59e95','#a7dce2','#bdabe3','#f2d195'][i];}
function renderFishList(){const list=$('fish-list');if(!list)return;const s=game.save,found=FISH.filter(f=>(filter==='all'||filter==='found'&&s.seen[f.id]||f.island===filter)&&f.name.toLowerCase().includes(search.toLowerCase()));list.innerHTML=found.map(f=>{const seen=s.seen[f.id],i=ISLANDS.find(i=>i.id===f.island),bait=BAITS.find(b=>b.id===f.bait);return item(f.name,fishSVG(f,'normal',!seen),`${i.name}<br>${seen?'Landed '+seen.count+' · Record '+seen.weight.toFixed(2)+' kg':'Not yet discovered'}<br>${bait.name} · ${f.time==='night'?'Night':'Any time'} · ${f.weather==='any'?'Any weather':f.weather}`,`<p>${f.lore}</p>`,RARITIES[f.rarity]);}).join('')||'<p class="empty">No matching fish.</p>';}
function renderMap(){const s=game.save,target=ISLANDS.find(i=>i.id===mapTarget)||ISLANDS[1],p=game.player,xy=i=>({x:300+i.x*.95,y:290+i.z*.95});$('panel-body').innerHTML=`<div class="chart-wrap"><svg class="chart" viewBox="0 0 600 580" role="img" aria-label="Sea chart: select an island"><defs><pattern id="chart-grid" width="60" height="60" patternUnits="userSpaceOnUse"><path d="M60 0H0V60" fill="none" stroke="#83b7b025"/></pattern></defs><rect width="600" height="580" fill="url(#chart-grid)"/><text x="32" y="43" fill="#d7e5c3" font-family="Georgia" font-size="21">THE HORIZON SEA</text><text x="32" y="65" fill="#a8c9c1" font-size="10" letter-spacing="3">SIX ISLANDS · A THOUSAND STORIES</text><path d="M${300+p.x*.95},${290+p.z*.95} L${xy(target).x},${xy(target).y}" stroke="#edcd8b" stroke-dasharray="6 7" opacity=".65"/>${ISLANDS.map(i=>{const pos=xy(i),selected=i.id===mapTarget;return `<g class="chart-point" data-destination="${i.id}" tabindex="0" role="button" aria-label="${i.name}"><circle cx="${pos.x}" cy="${pos.y}" r="${i.r*.9+4}" fill="${i.sand}" stroke="${selected?'#f8db9c':'#94baaa'}" stroke-width="${selected?4:1}"/><circle cx="${pos.x}" cy="${pos.y-2}" r="${i.r*.9}" fill="${i.color}"/><text x="${pos.x}" y="${pos.y+4}" text-anchor="middle" font-size="19">${{harbor:'♜',reef:'♧',marsh:'♠',ice:'❄',ember:'▲',ruins:'✧'}[i.id]}</text><text x="${pos.x}" y="${pos.y+i.r+23}" fill="#e5edd3" text-anchor="middle" font-size="13">${i.name}</text><text x="${pos.x}" y="${pos.y+i.r+39}" fill="#a8c4b7" text-anchor="middle" font-size="9">${s.visited.includes(i.id)?'DISCOVERED':'SAIL TO DISCOVER'}</text></g>`;}).join('')}<circle cx="${300+p.x*.95}" cy="${290+p.z*.95}" r="5" fill="#f9d390" stroke="#102d38" stroke-width="2"/><text x="553" y="39" fill="#c6dbc1" font-size="13">N ↑</text></svg><div class="chart-details"><span class="tag">YOUR DESTINATION</span><h3>${target.name}</h3><p>${target.hint}</p><p>${Math.round(dist(p,target))} metres away · ${Object.keys(s.seen).filter(id=>id.startsWith(target.id+'-')).length} / 10 species found</p><button class="gold" data-action="waypoint" data-id="${target.id}">Set compass destination</button><button data-action="travel" data-id="${target.id}" ${!s.visited.includes(target.id)||game.fishing.state!=='idle'?'disabled':''}>Travel to dock</button><p>${s.visited.includes(target.id)?'This dock is on your chart. You can return whenever your line is reeled in.':'Summon your skiff and follow the golden ring on your minimap.'}</p><p class="lead">Treasure chests are on land. Each chest gives coins and an enchantment relic.</p></div></div>`;}
function panelAction(e){const dest=e.target.closest('[data-destination]');if(dest){mapTarget=dest.dataset.destination;renderMap();return;}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;let ok=true,message='';
 if(a==='sell-all'||a==='sell'){const result=game.sell(a==='sell'?id:null);ok=result.ok;message=result.text;}
 if(a==='lock')game.toggleLock(id);if(a==='lock-all')game.save.bag.forEach(x=>x.locked=true);if(a==='unlock-all')game.save.bag.forEach(x=>x.locked=false);
 if(a==='rod'){ok=game.buyRod(id);message=ok?'Equipped '+game.rod().name+'.':'Return to a port with enough coins and the required level.';}
 if(a==='boat-buy'){ok=game.buyBoat(id);message=ok?'Your boat is ready. Summon it beside a dock.':'Return to a port with enough coins.';}
 if(a==='bait-buy'){ok=game.buyBait(id);message=ok?'Ten casts of fresh bait, equipped.':'Return to a port with enough coins.';}
 if(a==='bait-equip'){game.save.baitId=id;message='Bait selected.';}
 if(a==='enchant'){ok=game.enchant(id);message=ok?'Your rod hums with its new enchantment.':'You need more relics and an island port.';}
 if(a==='claim'){ok=game.claim(id);message=ok?'Chapter complete. Your reward is in your pocket.':'This chapter is still waiting for you.';}
 if(a==='waypoint'){mapTarget=id;toast('Following '+ISLANDS.find(i=>i.id===id).name+'.');closePanel();return;}
 if(a==='travel'){ok=game.travel(id);closePanel();events();persist();return;}
 if(a==='rescue'){game.respawn();closePanel();events();persist();return;}
 if(a==='help'){panel='help';renderPanel();return;}
 if(a==='fullscreen'){const request=document.documentElement.requestFullscreen;if(request)request.call(document.documentElement).catch(()=>toast('Fullscreen is unavailable here. Open the game directly for more room.'));else toast('Use your browser’s fullscreen or Add to Home Screen option.');return;}
 if(message)toast(message);if(ok&&['sell-all','sell','claim','bait-buy','rod','boat-buy','enchant'].includes(a))sound('coins');persist();renderPanel();updateHUD();}
function panelChange(e){const id=e.target.id;if(id==='fish-filter'){filter=e.target.value;renderFishList();return;}if(!id.startsWith('pref-'))return;const key=id.slice(5),value=['sound','assist'].includes(key)?e.target.checked:key==='sensitivity'?Number(e.target.value):e.target.value;game.save.prefs[key]=value;persist();if(key==='quality'||key==='touch')resize();}
init();
})();
