/* Wobble Bay: original, deterministic gameplay and physics, shared by browser and tests. */
(()=>{'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),angle=a=>Math.atan2(Math.sin(a),Math.cos(a)),TAU=Math.PI*2;
const JOBS=[
 {id:'parcel',name:'Parcel Run',tag:'PICK UP & DELIVER',pay:75,time:240,site:{x:36,z:43},description:'Grab the parcel at the depot. Carry it or load it into a vehicle, then deliver three packages.'},
 {id:'pizza',name:'Pizza Express',tag:'HOT FOOD, QUICK FEET',pay:70,time:210,site:{x:-30,z:20},description:'Deliver three hot pizzas from Sunny Slice. A fast finish earns a warm-pizza bonus.'},
 {id:'taxi',name:'Taxi, Please!',tag:'THREE HAPPY PASSENGERS',pay:85,time:260,site:{x:-58,z:9},description:'Use a taxi, pick up each passenger and drive them to their destination. Press ACT to board and drop off.'},
 {id:'cleanup',name:'Park Patrol',tag:'GRAB, TOSS, RECYCLE',pay:65,time:210,site:{x:-24,z:-53},description:'Pick up four rubbish bags in the park and drop them into the recycling zone.'},
 {id:'fishing',name:'Gone Fishing',tag:'WAIT FOR THE BITE',pay:60,time:240,site:{x:174,z:66},description:'Reach the pier. Press ACT to cast, then GRAB when a fish bites. Catch three fish.'},
 {id:'builder',name:'Builder Buddy',tag:'DELIVER THE MATERIALS',pay:90,time:240,site:{x:-93,z:-18},description:'Move three heavy material crates from the yard to the orange foundation. Grabbing and throwing both work.'},
 {id:'rally',name:'Island Rally',tag:'EIGHT CHECKPOINTS',pay:95,time:150,site:{x:0,z:-80},description:'Use a road vehicle and pass all eight rings in order. Corners, crashes and shortcuts are part of the fun.'},
 {id:'rescue',name:'Coastal Rescue',tag:'FLY, LAND, HELP',pay:120,time:300,site:{x:84,z:120},description:'Take a helicopter to the little offshore island. Land, press ACT to board the castaway, then return to the hospital.'}
];
const RIDES={runabout:{name:'Sunny Runabout',price:0,max:16,acc:10,colour:'#ed8068',size:1.45},pickup:{name:'Cargo Pickup',price:150,max:15,acc:8,colour:'#79a6ca',size:1.7},taxi:{name:'Bay Taxi',price:180,max:17,acc:9,colour:'#f6c963',size:1.55},van:{name:'Parcel Van',price:210,max:14,acc:7.8,colour:'#96c2b0',size:1.75},buggy:{name:'Beach Buggy',price:270,max:21,acc:13,colour:'#ecad72',size:1.35},boat:{name:'Seabreeze Boat',price:340,max:20,acc:9,colour:'#eae8d3',size:1.9},heli:{name:'Bumble Helicopter',price:550,max:22,acc:8,colour:'#f3c75f',size:1.7}};
const HATS={none:{name:'No hat',price:0},cap:{name:'Bay baseball cap',price:0},hardhat:{name:'Builder hard hat',price:70},beanie:{name:'Cosy beanie',price:80},cowboy:{name:'Explorer hat',price:100},crown:{name:'Very important crown',price:180},propeller:{name:'Propeller cap',price:130}};
const HOMES=[{id:'cottage',name:'Seabreeze Cottage',price:220,x:-86,z:44},{id:'townhouse',name:'Peach Townhouse',price:450,x:99,z:-42},{id:'hillhouse',name:'Hilltop Hideaway',price:850,x:-117,z:-117}];
const LANDMARKS=[{id:'board',name:'Town Square',x:0,z:25,type:'jobs'},{id:'shop',name:'Threads & Things',x:-18,z:-18,type:'shop'},{id:'garage',name:'Bay Motors',x:24,z:-17,type:'garage'},{id:'parcel',name:'Parcel Depot',x:36,z:43,type:'jobs'},{id:'pizza',name:'Sunny Slice',x:-30,z:20,type:'jobs'},{id:'taxi',name:'Taxi Rank',x:-58,z:9,type:'jobs'},{id:'cleanup',name:'Seaglass Park',x:-24,z:-53,type:'jobs'},{id:'builder',name:'Build Yard',x:-93,z:-18,type:'jobs'},{id:'fishing',name:'Bluewater Pier',x:174,z:66,type:'jobs'},{id:'airport',name:'Bumble Airfield',x:84,z:120,type:'jobs'},{id:'hospital',name:'Bay Clinic',x:42,z:-67,type:'npc'},...HOMES.map(h=>({...h,type:'home'}))];
const BUILDINGS=[
 {x:-18,z:-29,w:15,d:15,h:7,colour:'#ecacb7',roof:'#767ea8',name:'THREADS'}, {x:24,z:-29,w:19,d:15,h:7,colour:'#8caebe',roof:'#557580',name:'BAY MOTORS'},
 {x:36,z:54,w:20,d:15,h:8,colour:'#a6c5b3',roof:'#e4b776',name:'PARCEL POST'}, {x:-30,z:31,w:18,d:15,h:7,colour:'#efc79f',roof:'#d77e68',name:'SUNNY SLICE'},
 {x:42,z:-80,w:24,d:19,h:9,colour:'#e8e7d5',roof:'#91b9c0',name:'CLINIC'}, {x:105,z:125,w:34,d:26,h:10,colour:'#a9bdc4',roof:'#7797a1',name:'BUMBLE AIR'},
 {x:-86,z:54,w:16,d:14,h:6,colour:'#eac59e',roof:'#87a9a8',name:'COTTAGE'}, {x:99,z:-53,w:17,d:15,h:9,colour:'#e8a893',roof:'#9ba39f',name:'TOWNHOUSE'}, {x:-117,z:-129,w:22,d:16,h:8,colour:'#efd8b4',roof:'#bb8474',name:'HILLTOP'},
 ...[-47,47].flatMap((x,k)=>[-103,-32,99].map((z,i)=>({x,z,w:14+(i%2)*3,d:15,h:7+(i%2)*2,colour:['#d3b6c9','#aec9b7','#efcf91','#a8c2d6'][(i+k)%4],roof:['#928499','#96a7a2','#cb947b'][i%3],name:''}))),
 {x:89,z:36,w:16,d:16,h:7,colour:'#b5c5b0',roof:'#8b9f9b',name:''},{x:-106,z:99,w:18,d:15,h:8,colour:'#efc993',roof:'#aa8f85',name:''}
];
const STARS=[[-15,12,0],[47,89,0],[-77,68,0],[114,-78,0],[136,24,0],[187,66,0],[-146,-84,0],[-111,-148,0],[76,144,0],[-118,117,0],[121,99,0],[25,-120,0],[-258,88,0],[-111,-24,3],[38,53,10],[-37,-69,0]].map((p,i)=>({id:'star'+i,x:p[0],z:p[1],y:p[2]}));
const ROUTE=[{x:0,z:-65},{x:65,z:-65},{x:65,z:0},{x:65,z:65},{x:0,z:65},{x:-65,z:65},{x:-65,z:0},{x:-65,z:-65}];
const DOORS=[{x:46,z:88},{x:100,z:-42},{x:-47,z:-90},{x:-86,z:44},{x:89,z:25}];
function terrain(x,z){const islet=Math.hypot(x+258,z-88);if(islet<25)return clamp((25-islet)*.35-1.5,-2,1.5);if(x>154&&x<202&&z>60&&z<73)return 1;const coast=(Math.abs(x)/203)**4+(Math.abs(z)/176)**4;if(coast>1.22)return-5;if(coast>.92)return lerp(1,-5,(coast-.92)/.3);return 1+20*Math.exp(-(((x+119)/43)**2+((z+120)/43)**2))}
function safePosition(p){return p&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&Math.abs(p.x)<300&&Math.abs(p.z)<190&&terrain(p.x,p.z)>0?p:{x:0,z:27}}
function sanitize(d={}){const p=d.prefs||{},n=(v,a,b,f)=>Number.isFinite(Number(v))?clamp(Number(v),a,b):f,hex=(v,f)=>/^#[0-9a-f]{6}$/i.test(String(v))?v:f,allowed=(v,keys,f)=>keys.includes(v)?v:f,list=(a,keys)=>Array.isArray(a)?[...new Set(a.filter(v=>keys.includes(v)))]:[],jobs={};for(const j of JOBS)jobs[j.id]=Math.floor(n(d.jobs?.[j.id],0,1e6,0));return{cash:Math.floor(n(d.cash,0,1e9,80)),earned:Math.floor(n(d.earned,0,1e9,0)),jobs,stars:list(d.stars,STARS.map(s=>s.id)),hats:[...new Set(['none','cap',...list(d.hats,Object.keys(HATS))])],rides:[...new Set(['runabout',...list(d.rides,Object.keys(RIDES))])],homes:list(d.homes,HOMES.map(h=>h.id)),pet:d.pet===true,skin:hex(d.skin,'#f4d16b'),shirt:hex(d.shirt,'#ed896e'),hat:allowed(d.hat,Object.keys(HATS),'cap'),carColour:hex(d.carColour,'#ed8068'),prefs:{sound:p.sound!==false,volume:n(p.volume,0,1,.45),graphics:allowed(p.graphics,['auto','low','high'],'auto'),touchSize:allowed(p.touchSize,['large','xl'],'large'),touchControls:p.touchControls===true,time:allowed(p.time,['day','golden','night','cycle','random'],'day'),camera:allowed(p.camera,['near','standard','wide'],'standard')},position:safePosition(d.position)}}
class World{
 constructor(saved={},seed=321){this.save=sanitize(saved);this.seed=seed>>>0;this.time=0;this.events=[];this.colliders=BUILDINGS.map(b=>({...b,y:terrain(b.x,b.z)}));this.colliders.push({x:-110,z:-24,w:7,d:7,h:2.6,y:terrain(-110,-24),colour:'#b9ab91',platform:true});this.player={...this.save.position,y:terrain(this.save.position.x,this.save.position.z),vx:0,vy:0,vz:0,angle:Math.PI,grounded:true,ragdoll:null,flop:0,water:0};this.vehicles=[];this.props=[];this.serial=1;this.driving=null;this.held=null;this.job=null;this.waypoint=null;this.bite=0;this.joystick={x:0,y:0};this.completed=0;this.cooldown=0;this.stars=STARS.map(s=>({...s,y:['star13','star14'].includes(s.id)?this.floorAt(s.x,s.z)+1.3:s.y||terrain(s.x,s.z)+1.3}));this.spawnCar('runabout',6,18,Math.PI);this.spawnCar('pickup',30,38,Math.PI/2);this.spawnCar('taxi',-53,8,Math.PI/2);this.spawnCar('van',43,40,Math.PI);this.spawnCar('buggy',104,88,Math.PI/2);this.spawnCar('boat',210,84,-Math.PI/2);this.spawnCar('heli',84,120,Math.PI);for(let i=0;i<12;i++)this.spawnProp(i%3===0?'ball':i%3===1?'crate':'cone',-11+(i%4)*5,44+Math.floor(i/4)*5);this.npcs=[{id:'mayor',x:3,z:25,name:'Bea',colour:'#88bdc3',line:'Welcome to Wobble Bay! The board has eight ways to earn. Your first house is only $220.'},{id:'tailor',x:-18,z:-18,name:'Pip',colour:'#c39dc1',line:'A new hat, a new you! Try the shop or change your colours.'},{id:'mechanic',x:24,z:-17,name:'Milo',colour:'#9eb98a',line:'Parked vehicles are free to borrow. Buy a ride to call it from your garage anywhere.'},{id:'fisher',x:173,z:67,name:'Finn',colour:'#b9a679',line:'Wait for BITE, then GRAB! The tiny offshore island has a visitor who needs a lift.'},{id:'builder',x:-92,z:-20,name:'Ash',colour:'#e7b875',line:'The orange pad needs three crates. Stack them, throw them or take a pickup.'},{id:'walker',x:12,z:-6,name:'Dot',colour:'#a6bfe1',line:'There are sixteen golden stars. Some are higher than others!',patrol:true}];this.traffic=this.spawnCar('runabout',65,-15,0);this.traffic.traffic=true;this.traffic.pathIndex=2;this.petPos={x:this.player.x-1,z:this.player.z+1,y:this.player.y};this.lastBasket=0;this.dayMode=this.save.prefs.time==='random'?['day','golden','night'][Math.floor(this.random()*3)]:this.save.prefs.time}
 random(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296}
 emit(type,data={}){this.events.push({type,...data});if(this.events.length>60)this.events.shift()}
 message(text){this.emit('toast',{text})}
 position(){return this.driving||this.player}
 snapshot(){this.save.position=safePosition({x:this.player.x,z:this.player.z});return JSON.parse(JSON.stringify(this.save))}
 spawnCar(type,x,z,a=0){const cfg=RIDES[type];if(!cfg)return null;const c={id:'car'+this.serial++,type,x,z,y:terrain(x,z)+.35,angle:a,vx:0,vy:0,vz:0,spin:0,roll:0,damage:0,water:0,energy:100,cargo:null,home:{x,z,a},size:cfg.size,traffic:false};if(type==='boat')c.y=-.25;this.vehicles.push(c);return c}
 spawnProp(type,x,z,extra={}){const p={id:'prop'+this.serial++,type,x,z,y:terrain(x,z)+.6,vx:0,vy:0,vz:0,angle:this.random()*TAU,spin:0,r:type==='ball'?.36:type==='cone'?.34:.48,mass:type==='material'?2:1,home:{x,z},follow:null,...extra};this.props.push(p);return p}
 nearestCar(){const p=this.player;return this.vehicles.filter(c=>!c.traffic&&dist(p,c)<3.4&&Math.abs(c.y-p.y)<3.5).sort((a,b)=>dist(a,p)-dist(b,p))[0]||null}
 nearSite(){const p=this.position();return LANDMARKS.filter(l=>dist(p,l)<3.3).sort((a,b)=>dist(a,p)-dist(b,p))[0]||null}
 context(){const p=this.position(),j=this.job;if(j?.id==='fishing'&&dist(p,JOBS[4].site)<5)return j.cast==='bite'?'BITE! GRAB':j.cast?'WAIT FOR BITE':'CAST LINE';if(j&&(j.id==='taxi'||j.id==='rescue')&&this.driving&&j.target&&dist(p,j.target)<5)return j.stage==='pickup'?'BOARD PASSENGER':'DROP OFF';if(this.driving)return'EXIT VEHICLE';const c=this.nearestCar();if(c)return'DRIVE '+RIDES[c.type].name.toUpperCase();const site=this.nearSite();if(site)return site.type==='home'?'VISIT '+site.name.toUpperCase():site.type==='shop'?'OPEN SHOP':site.type==='garage'?'OPEN GARAGE':site.type==='jobs'?'VIEW JOBS':'SAY HELLO';const npc=this.npcs.find(n=>dist(p,n)<2.5);return npc?'TALK TO '+npc.name.toUpperCase():'EXPLORE THE BAY'}
 interact(){const p=this.position(),j=this.job;if(j?.id==='fishing'&&dist(p,JOBS[4].site)<5&&!this.driving){if(!j.cast){j.cast='waiting';j.castTime=1.8+this.random()*3;this.message('Line cast. Wait for BITE, then press GRAB.');this.emit('cast')}return}
  if(j&&(j.id==='taxi'||j.id==='rescue')&&this.driving&&dist(p,j.target)<5){if(j.id==='taxi'&&this.driving.type!=='taxi'){this.message('This passenger asked for a taxi. Borrow the yellow Bay Taxi.');return}if(j.id==='rescue'&&(this.driving.type!=='heli'||this.driving.y>terrain(p.x,p.z)+4)){this.message('Land the helicopter close to the castaway first.');return}if(j.stage==='pickup'){j.stage='drop';j.target=j.id==='rescue'?{x:42,z:-67}:DOORS[(j.count+1)%DOORS.length];j.passenger=true;this.message('Passenger aboard. Follow the destination marker.')}else{j.passenger=false;j.count++;if(j.count>=(j.id==='rescue'?1:3))this.finishJob();else{j.stage='pickup';j.target=[{x:-58,z:9},{x:47,z:85},{x:99,z:-40}][j.count];this.message('Happy passenger! Pick up the next fare.')}}return}
  if(this.driving){this.exitCar();return}const car=this.nearestCar();if(car){this.enterCar(car);return}const site=this.nearSite();if(site){this.emit('panel',{panel:site.type==='npc'?'talk':site.type,id:site.id});return}const npc=this.npcs.find(n=>dist(p,n)<2.5);if(npc)this.emit('talk',{name:npc.name,text:npc.line})
 }
 enterCar(car){if(this.player.ragdoll)return;if(this.held){car.cargo=this.held.id;this.held.follow=car.id;this.held=null}this.driving=car;car.traffic=false;this.player.vx=this.player.vz=0;this.message(RIDES[car.type].name+' · '+(car.type==='heli'?'move to fly · JUMP up · FLOP down':car.type==='boat'?'steer & accelerate · JUMP to boost':'steer & accelerate · BRAKE slows & reverses'));this.emit('vehicle',{action:'enter'})}
 exitCar(){const car=this.driving;if(!car)return;const candidates=[1,-1,2].map(s=>({x:car.x+Math.cos(car.angle)*s*2.1,z:car.z-Math.sin(car.angle)*s*2.1})),safe=candidates.find(p=>terrain(p.x,p.z)>-.5&&!this.colliders.some(b=>Math.abs(p.x-b.x)<b.w/2+.4&&Math.abs(p.z-b.z)<b.d/2+.4))||candidates[0];Object.assign(this.player,{x:safe.x,z:safe.z,y:Math.max(terrain(safe.x,safe.z),car.type==='heli'?car.y-.4:terrain(safe.x,safe.z)),vx:car.vx*.6,vz:car.vz*.6,vy:0,angle:car.angle});this.driving=null;if(car.type==='heli'&&car.y>terrain(safe.x,safe.z)+3)this.flop(2);this.emit('vehicle',{action:'exit'})}
 grab(){if(this.player.ragdoll)return;const j=this.job;if(j?.id==='fishing'&&j.cast==='bite'&&dist(this.position(),JOBS[4].site)<5){j.count++;j.cast=null;this.emit('fish');if(j.count>=3)this.finishJob();else this.message('Fish caught! '+j.count+' / 3. Press ACT to cast again.');return}if(this.driving){this.message('Exit the vehicle to grab objects. Cargo stays in the back.');return}if(this.held){this.held.follow=null;this.held=null;return}const p=this.player,prop=this.props.filter(q=>dist(q,p)<2.1&&Math.abs(q.y-p.y-1)<2.3).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(prop){for(const c of this.vehicles)if(c.cargo===prop.id)c.cargo=null;prop.follow='player';this.held=prop;this.emit('grab')}else this.message('Get close to a crate, bag, ball or cone, then GRAB.')}
 throw(){if(!this.held)return;const p=this.player,q=this.held;q.follow=null;q.vx=p.vx+Math.sin(p.angle)*10;q.vz=p.vz+Math.cos(p.angle)*10;q.vy=q.type==='ball'?8:5;q.spin=3;q.grace=.4;this.held=null;this.emit('throw')}
 jump(){if(this.driving)return;if(this.player.grounded&&!this.player.ragdoll){this.player.vy=6.5;this.player.grounded=false;this.emit('jump')}}
 flop(force=1){if(this.driving||this.player.ragdoll)return;const p=this.player,offsets=[[0,1.65,0],[0,1.06,0],[-.4,1.1,0],[.4,1.1,0],[-.65,.65,0],[.65,.65,0],[-.22,.55,0],[.22,.55,0],[-.24,.05,.1],[.24,.05,.1]],nodes=offsets.map(o=>({x:p.x+o[0],y:p.y+o[1],z:p.z+o[2],vx:p.vx+Math.sin(p.angle)*force,vy:p.vy+force,vz:p.vz+Math.cos(p.angle)*force})),pairs=[[0,1],[1,2],[1,3],[2,4],[3,5],[1,6],[1,7],[6,8],[7,9],[2,3],[6,7]],links=pairs.map(([a,b])=>({a,b,len:Math.hypot(offsets[a][0]-offsets[b][0],offsets[a][1]-offsets[b][1],offsets[a][2]-offsets[b][2])}));p.ragdoll={nodes,links,age:0};this.emit('flop')}
 recover(){if(this.driving){const c=this.driving;Object.assign(c,{x:c.home.x,z:c.home.z,y:c.type==='boat'?-.25:terrain(c.home.x,c.home.z)+.35,angle:c.home.a,vx:0,vy:0,vz:0,spin:0,roll:0,water:0,damage:Math.min(c.damage,25)})}else{const home=HOMES.find(h=>this.save.homes.includes(h.id))||{x:0,z:27};Object.assign(this.player,{x:home.x,z:home.z,y:terrain(home.x,home.z),vx:0,vz:0,vy:0,ragdoll:null,water:0})}if(this.held){this.held.follow=null;this.held=null}this.message('Back on your feet. Your cash and progress are safe.');this.emit('recover')}
 startJob(id){if(id==='random')id=JOBS[Math.floor(this.random()*JOBS.length)].id;const def=JOBS.find(j=>j.id===id);if(!def)return false;this.cancelJob(false);this.job={id,count:0,left:def.time,elapsed:0,stage:'pickup',target:{...def.site},cast:null,passenger:false};const j=this.job;if(id==='parcel'||id==='pizza')this.spawnDelivery();if(id==='cleanup'){j.stage='collect';j.target={x:-24,z:-53};[[-36,-43],[-12,-43],[-39,-58],[-15,-59]].forEach(([x,z])=>this.spawnProp('trash',x,z,{job:id}))}if(id==='builder'){j.stage='collect';j.target={x:-108,z:-19};[[-78,-20],[-78,-24],[-78,-28]].forEach(([x,z])=>this.spawnProp('material',x,z,{job:id}))}if(id==='rally'){j.stage='race';j.target={...ROUTE[0]}}if(id==='taxi')j.target={x:-58,z:9};if(id==='rescue')j.target={x:-258,z:88};this.waypoint=null;this.message(def.name+' started. '+def.description);return true}
 spawnDelivery(){const j=this.job,site=JOBS.find(d=>d.id===j.id).site;j.stage='pickup';j.target={...site};j.item=this.spawnProp(j.id==='pizza'?'pizza':'parcel',site.x,site.z,{job:j.id}).id}
 cancelJob(notify=true){if(!this.job)return;const id=this.job.id;this.props=this.props.filter(p=>p.job!==id);if(this.held?.job===id)this.held=null;for(const c of this.vehicles)if(!this.props.some(p=>p.id===c.cargo))c.cargo=null;this.job=null;if(notify)this.message('Job cancelled. Choose another whenever you like.')}
 finishJob(){if(!this.job)return;const j=this.job,def=JOBS.find(d=>d.id===j.id),bonus=j.id==='pizza'?Math.round(j.left/15):j.id==='rally'?Math.round(j.left/12):0,pay=def.pay+Math.max(0,bonus);this.save.cash+=pay;this.save.earned+=pay;this.save.jobs[j.id]++;this.completed++;if(j.id==='builder'&&!this.save.hats.includes('hardhat'))this.save.hats.push('hardhat');this.emit('jobComplete',{name:def.name,pay,bonus});this.cancelJob(false);this.emit('save')}
 buy(category,id){let cost=0,list=null;if(category==='hat'){if(!HATS[id])return false;cost=HATS[id].price;list=this.save.hats}else if(category==='ride'){if(!RIDES[id])return false;cost=RIDES[id].price;list=this.save.rides}else if(category==='home'){const h=HOMES.find(h=>h.id===id);if(!h)return false;cost=h.price;list=this.save.homes}else if(category==='pet'){if(this.save.pet){this.message('Your companion is already waiting for you.');return false}cost=140}else return false;if(list?.includes(id)){this.message('Already yours.');return false}if(this.save.cash<cost){this.message('You need $'+(cost-this.save.cash)+' more. A job can help!');return false}this.save.cash-=cost;if(list)list.push(id);else this.save.pet=true;this.message('Yours! Enjoy your new '+(category==='pet'?'companion':category)+'.');this.emit('save');return true}
 callRide(type){if(!this.save.rides.includes(type)||this.cooldown>0){this.message(this.cooldown>0?'Let your last vehicle settle first.':'Buy that vehicle in the garage first.');return null}if(this.vehicles.length>=18){const old=this.vehicles.find(c=>!c.traffic&&c!==this.driving&&!c.cargo);if(old)this.vehicles.splice(this.vehicles.indexOf(old),1);else return null}const p=this.position();let x=p.x+Math.sin(p.angle)*5,z=p.z+Math.cos(p.angle)*5;if(type==='boat'){x=210;z=84}if(type==='heli'){x=p.x+5;z=p.z+5}if(type!=='boat'&&(terrain(x,z)<0||this.colliders.some(b=>Math.abs(x-b.x)<b.w/2+2&&Math.abs(z-b.z)<b.d/2+2))){x=6;z=18}const c=this.spawnCar(type,x,z,p.angle);c.colour=this.save.carColour;this.cooldown=8;this.message(RIDES[type].name+' is ready'+(type==='boat'?' at the pier.':'.'));return c}
 setWaypoint(x,z){if(Number.isFinite(x)&&Number.isFinite(z)&&Math.abs(x)<350&&Math.abs(z)<250)this.waypoint={x,z}}
 floorAt(x,z,prevY=Infinity){let h=terrain(x,z);for(const b of this.colliders)if(Math.abs(x-b.x)<b.w/2&&Math.abs(z-b.z)<b.d/2&&prevY>=b.y+b.h-.2)h=Math.max(h,b.y+b.h+(b.platform?0:3.4*Math.max(0,1-Math.max(Math.abs(x-b.x)/(b.w/2+1),Math.abs(z-b.z)/(b.d/2+1)))));return h}
 pushBody(o,r,base,height){for(const b of this.colliders){if(base>b.y+b.h-.05||base+height<b.y)continue;const dx=o.x-clamp(o.x,b.x-b.w/2,b.x+b.w/2),dz=o.z-clamp(o.z,b.z-b.d/2,b.z+b.d/2),len=Math.hypot(dx,dz);if(len>=r)continue;let nx=dx/(len||1),nz=dz/(len||1),depth=r-len;if(len<.001){const px=b.w/2+r-Math.abs(o.x-b.x),pz=b.d/2+r-Math.abs(o.z-b.z);if(px<pz){nx=Math.sign(o.x-b.x)||1;nz=0;depth=px}else{nz=Math.sign(o.z-b.z)||1;nx=0;depth=pz}}o.x+=nx*depth;o.z+=nz*depth;const vn=o.vx*nx+o.vz*nz;if(vn<0){o.vx-=vn*nx*1.25;o.vz-=vn*nz*1.25;if(o.id?.startsWith('car')){const impact=-vn;o.damage=clamp(o.damage+impact*.65,0,100);o.spin+=(nx*Math.cos(o.angle)-nz*Math.sin(o.angle))*impact*.08;if(impact>5)this.emit('impact',{x:o.x,y:o.y,z:o.z,power:impact})}}}}
 update(dt,input={}){dt=clamp(dt,0,.05);if(!dt)return;this.time+=dt;this.cooldown=Math.max(0,this.cooldown-dt);const p=this.player;if(this.driving){this.driveVehicle(this.driving,dt,input);Object.assign(p,{x:this.driving.x,z:this.driving.z,y:this.driving.y,angle:this.driving.angle})}else if(p.ragdoll)this.ragdoll(dt);else this.walk(dt,input);for(const c of this.vehicles)if(c!==this.driving){if(c.traffic){const target=ROUTE[c.pathIndex],heading=Math.atan2(target.x-c.x,target.z-c.z),steer=clamp(-angle(heading-c.angle)*2,-1,1);this.driveVehicle(c,dt,{forward:.28,steer});if(dist(c,target)<5)c.pathIndex=(c.pathIndex+1)%ROUTE.length}else this.driveVehicle(c,dt,{})}this.carContacts();this.updateProps(dt);this.propContacts();this.updateJob(dt);this.collectStars();if(!this.driving){for(const c of this.vehicles){const speed=Math.hypot(c.vx,c.vz);if(dist(c,p)<c.size+.4&&Math.abs(c.y-p.y)<2&&speed>3&&!p.ragdoll){p.vx=c.vx*.8;p.vz=c.vz*.8;this.flop(speed*.25)}}}for(const n of this.npcs)if(n.patrol){n.x=12+Math.sin(this.time*.13)*8;n.z=-6+Math.cos(this.time*.13)*4}this.petPos.x=lerp(this.petPos.x,p.x-Math.sin(p.angle)*1.5,1-Math.exp(-dt*2.4));this.petPos.z=lerp(this.petPos.z,p.z-Math.cos(p.angle)*1.5,1-Math.exp(-dt*2.4));this.petPos.y=terrain(this.petPos.x,this.petPos.z);if(p.y<-.4&&terrain(p.x,p.z)<-.7&&!this.driving){p.water+=dt;if(p.water>1.6){this.emit('splash',{x:p.x,z:p.z});this.recover()}}else p.water=0}
 walk(dt,i){const p=this.player,speed=i.sprint?7.4:4.8,mag=Math.min(1,Math.hypot(i.x||0,i.z||0)),normal=Math.max(1,Math.hypot(i.x||0,i.z||0)),vx=(i.x||0)*speed/normal,vz=(i.z||0)*speed/normal,k=1-Math.exp(-dt*(p.grounded?11:4));p.vx=lerp(p.vx,vx,k);p.vz=lerp(p.vz,vz,k);const prevY=p.y;p.x+=p.vx*dt;p.z+=p.vz*dt;p.vy-=16*dt;p.y+=p.vy*dt;const floor=this.floorAt(p.x,p.z,prevY);if(p.y<=floor){p.y=floor;p.vy=0;p.grounded=true}else p.grounded=false;this.pushBody(p,.43,p.y,1.7);if(mag>.12)p.angle+=angle(Math.atan2(p.vx,p.vz)-p.angle)*(1-Math.exp(-dt*12));p.x=clamp(p.x,-550,550);p.z=clamp(p.z,-500,500)}
 driveVehicle(c,dt,i){const cfg=RIDES[c.type],forward=clamp(i.forward||0,-1,1),steer=clamp(i.steer||0,-1,1),old=c.angle,fx=Math.sin(old),fz=Math.cos(old),rx=Math.cos(old),rz=-Math.sin(old);let vf=c.vx*fx+c.vz*fz,side=c.vx*rx+c.vz*rz;const water=terrain(c.x,c.z)<-.6;
  if(c.type==='heli'){const lift=(i.up?1:0)-(i.down?1:0),targetFloor=this.floorAt(c.x,c.z,c.y)+.8;c.vy=lerp(c.vy,lift*7,1-Math.exp(-dt*3));if(c.y<targetFloor&&lift<=0)c.vy=Math.max(c.vy,(targetFloor-c.y)*4);c.y=clamp(c.y+c.vy*dt,-.2,45);c.angle-=steer*dt*1.25;vf+=forward*cfg.acc*dt;vf*=Math.exp(-dt*.45);side*=Math.exp(-dt*2);if(!forward)vf*=Math.exp(-dt*.6)}else{const boost=i.boost&&c.energy>3,brake=i.brake||0;vf+=forward*cfg.acc*(1-c.damage*.0035)*(boost?1.5:1)*dt;if(brake){vf-=Math.sign(vf||1)*Math.min(Math.abs(vf),dt*19);if(Math.abs(vf)<.4)vf-=dt*cfg.acc*.5}vf*=Math.exp(-dt*(water&&c.type!=='boat'?2:c.type==='boat'&&!water?3:.11));if(!forward)vf*=Math.exp(-dt*.65);c.angle-=steer*clamp(vf/8,-1.2,1.2)*dt*(i.handbrake?2.3:1.55);side*=Math.exp(-dt*(i.handbrake?1.1:c.type==='boat'?2:8));c.energy=clamp(c.energy+(boost?-30:14)*dt,0,100);c.y=lerp(c.y,c.type==='boat'&&water?-.1+Math.sin(this.time*2+c.x)*.08:terrain(c.x,c.z)+.35,1-Math.exp(-dt*10));c.roll=lerp(c.roll,-steer*Math.abs(vf)*.006,1-Math.exp(-dt*5))}vf=clamp(vf,-6,cfg.max*(i.boost?1.25:1));c.vx=fx*vf+rx*side;c.vz=fz*vf+rz*side;c.angle+=c.spin*dt;c.spin*=Math.exp(-dt*4);c.x+=c.vx*dt;c.z+=c.vz*dt;this.pushBody(c,c.size,c.y-.35,c.type==='heli'?2:1.5);c.damage=Math.max(0,c.damage-dt*.9);if(water&&c.type!=='boat'&&c.y<1){c.water+=dt;if(c.water>2){if(c===this.driving){this.emit('splash',{x:c.x,z:c.z});this.recover()}else Object.assign(c,{x:c.home.x,z:c.home.z,y:terrain(c.home.x,c.home.z)+.35,vx:0,vz:0,water:0})}}else c.water=0;c.x=clamp(c.x,-550,550);c.z=clamp(c.z,-500,500)}
 carContacts(){for(let a=0;a<this.vehicles.length;a++)for(let b=a+1;b<this.vehicles.length;b++){const u=this.vehicles[a],v=this.vehicles[b];if(Math.abs(u.y-v.y)>2)continue;const dx=v.x-u.x,dz=v.z-u.z,len=Math.hypot(dx,dz),sum=u.size+v.size;if(len>=sum)continue;const nx=dx/(len||1),nz=dz/(len||1),overlap=sum-len;u.x-=nx*overlap*.5;u.z-=nz*overlap*.5;v.x+=nx*overlap*.5;v.z+=nz*overlap*.5;const relative=(v.vx-u.vx)*nx+(v.vz-u.vz)*nz;if(relative<0){const force=-relative*.66;u.vx-=nx*force;u.vz-=nz*force;v.vx+=nx*force;v.vz+=nz*force;u.damage=clamp(u.damage+force*.6,0,100);v.damage=clamp(v.damage+force*.6,0,100);u.spin-=force*.045;v.spin+=force*.045;if(force>2)this.emit('impact',{x:(u.x+v.x)/2,y:u.y,z:(u.z+v.z)/2,power:force})}}}
 ragdoll(dt){const p=this.player,r=p.ragdoll;r.age+=dt;for(const n of r.nodes){n.vy-=16*dt;n.vx*=Math.exp(-dt*.7);n.vz*=Math.exp(-dt*.7);n.x+=n.vx*dt;n.y+=n.vy*dt;n.z+=n.vz*dt;const f=this.floorAt(n.x,n.z,n.y+.2)+.14;if(n.y<f){n.y=f;n.vy=Math.abs(n.vy)*.13;n.vx*=.8;n.vz*=.8}this.pushBody(n,.16,n.y-.12,.3)}for(let iteration=0;iteration<6;iteration++)for(const l of r.links){const a=r.nodes[l.a],b=r.nodes[l.b],dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,len=Math.hypot(dx,dy,dz)||1,k=(len-l.len)/len*.48;a.x+=dx*k;a.y+=dy*k;a.z+=dz*k;b.x-=dx*k;b.y-=dy*k;b.z-=dz*k}const center=r.nodes[1];p.x=center.x;p.z=center.z;p.y=Math.max(terrain(p.x,p.z),center.y-.8);if(r.age>2.3&&Math.abs(center.vy)<3){p.ragdoll=null;p.vx=p.vz=p.vy=0;p.y=this.floorAt(p.x,p.z,p.y+.3);this.message('A little wobble never hurt. Back to it!')}}
 updateProps(dt){for(const q of this.props){q.grace=Math.max(0,(q.grace||0)-dt);if(q.follow){const holder=q.follow==='player'?this.player:this.vehicles.find(c=>c.id===q.follow);if(holder){const car=q.follow!=='player',offset=car?-1.2:1.1,tx=holder.x+Math.sin(holder.angle)*offset,tz=holder.z+Math.cos(holder.angle)*offset,ty=holder.y+(car?.8:1.15);q.vx+=(tx-q.x)*80*dt;q.vz+=(tz-q.z)*80*dt;q.vy+=(ty-q.y)*80*dt;const f=Math.exp(-dt*11);q.vx*=f;q.vy*=f;q.vz*=f}else q.follow=null}else q.vy-=16*dt;const prev=q.y;q.x+=q.vx*dt;q.z+=q.vz*dt;q.y+=q.vy*dt;q.angle+=q.spin*dt;const ground=this.floorAt(q.x,q.z,prev)+q.r;if(q.y<ground){q.y=ground;q.vy=Math.abs(q.vy)*(q.type==='ball'?.6:.15);q.vx*=Math.exp(-dt*(q.type==='ball'?1:5));q.vz*=Math.exp(-dt*(q.type==='ball'?1:5));q.spin*=.98}if(!q.follow)this.pushBody(q,q.r,q.y-q.r,q.r*2);if(q.y<-1.2){q.x=q.home.x;q.z=q.home.z;q.y=terrain(q.x,q.z)+1;q.vx=q.vy=q.vz=0;q.follow=null;if(this.held===q)this.held=null;for(const c of this.vehicles)if(c.cargo===q.id)c.cargo=null;this.emit('splash',{x:q.x,z:q.z})}if(q.type==='ball'&&this.time-this.lastBasket>1&&prev>4&&q.y<=4&&q.vy<0&&Math.hypot(q.x+10,q.z-41)<.85){this.lastBasket=this.time;this.save.cash+=2;this.save.earned+=2;this.message('Nothing but net! +$2');this.emit('save')}}}
 propContacts(){const free=this.props.filter(q=>!q.follow);for(let a=0;a<free.length;a++)for(let b=a+1;b<free.length;b++){const u=free[a],v=free[b],dx=v.x-u.x,dy=v.y-u.y,dz=v.z-u.z,len=Math.hypot(dx,dy,dz),sum=u.r+v.r;if(len>=sum)continue;const nx=len?dx/len:1,ny=len?dy/len:0,nz=len?dz/len:0,invU=1/u.mass,invV=1/v.mass,den=invU+invV,depth=sum-len;u.x-=nx*depth*invU/den;u.y-=ny*depth*invU/den;u.z-=nz*depth*invU/den;v.x+=nx*depth*invV/den;v.y+=ny*depth*invV/den;v.z+=nz*depth*invV/den;const rel=(v.vx-u.vx)*nx+(v.vy-u.vy)*ny+(v.vz-u.vz)*nz;if(rel<0){const j=-rel*(u.type==='ball'||v.type==='ball'?1.52:1.18)/den;u.vx-=nx*j*invU;u.vy-=ny*j*invU;u.vz-=nz*j*invU;v.vx+=nx*j*invV;v.vy+=ny*j*invV;v.vz+=nz*j*invV;u.spin-=j*.12;v.spin+=j*.12;}}for(const q of free){for(const c of this.vehicles){if(q.y-q.r>c.y+1.35||q.y+q.r<c.y-.35)continue;const dx=q.x-c.x,dz=q.z-c.z,len=Math.hypot(dx,dz),sum=q.r+c.size;if(len>=sum)continue;const nx=len?dx/len:1,nz=len?dz/len:0,depth=sum-len,rel=(q.vx-c.vx)*nx+(q.vz-c.vz)*nz;q.x+=nx*depth;q.z+=nz*depth;if(rel<0){const j=-rel*1.3/(1/q.mass+1/20);q.vx+=nx*j/q.mass;q.vz+=nz*j/q.mass;q.vy+=Math.min(2.5,j*.1);q.spin+=j*.2;c.vx-=nx*j/20;c.vz-=nz*j/20;}}const p=this.player;if(!this.driving&&!p.ragdoll&&!q.grace&&Math.abs(q.y-p.y-1)<1&&dist(p,q)<q.r+.43&&Math.hypot(q.vx,q.vz)>7){p.vx=q.vx*.35;p.vz=q.vz*.35;this.flop(1.2);this.emit('impact',{x:q.x,y:q.y,z:q.z,power:3});}}}
 updateJob(dt){const j=this.job;if(!j)return;j.left-=dt;j.elapsed+=dt;if(j.left<=0){this.cancelJob(false);this.message('Time is up. No money lost. Try another job!');return}const p=this.position();if(j.id==='parcel'||j.id==='pizza'){const q=this.props.find(q=>q.id===j.item);if(!q)return;if(j.stage==='pickup'&&(q.follow||dist(q,q.home)>2)){j.stage='deliver';j.target={...DOORS[(j.count+(j.id==='pizza'?2:0))%DOORS.length]};this.message('Package collected. Follow the gold destination marker.')}if(j.stage==='deliver'&&dist(q,j.target)<3.6&&dist(p,j.target)<7){this.props=this.props.filter(p=>p!==q);if(this.held===q)this.held=null;for(const c of this.vehicles)if(c.cargo===q.id)c.cargo=null;j.count++;if(j.count>=3)this.finishJob();else{this.spawnDelivery();this.message('Delivered! Return for package '+(j.count+1)+' of 3.')}}}else if(j.id==='cleanup'||j.id==='builder'){const delivered=this.props.filter(q=>q.job===j.id&&!q.follow&&dist(q,j.target)<3.5&&Math.abs(q.y-terrain(q.x,q.z))<3);for(const q of delivered){this.props.splice(this.props.indexOf(q),1);j.count++}if(j.count>=(j.id==='cleanup'?4:3))this.finishJob()}else if(j.id==='rally'){if(this.driving&&!['boat','heli'].includes(this.driving.type)&&dist(p,j.target)<6){j.count++;if(j.count>=ROUTE.length)this.finishJob();else{j.target={...ROUTE[j.count]};this.emit('checkpoint')}}}else if(j.id==='fishing'&&j.cast){j.castTime-=dt;if(j.cast==='waiting'&&j.castTime<=0){j.cast='bite';j.castTime=2.4;this.message('BITE! Press GRAB now!');this.emit('bite')}else if(j.cast==='bite'&&j.castTime<=0){j.cast=null;this.message('That one got away. Press ACT to cast again.')}}}
 collectStars(){const p=this.position();for(const s of this.stars)if(!this.save.stars.includes(s.id)&&Math.hypot(p.x-s.x,p.z-s.z)<1.4&&Math.abs(p.y+1-s.y)<2){this.save.stars.push(s.id);this.save.cash+=10;this.save.earned+=10;this.message('Golden star! '+this.save.stars.length+' / 16 · +$10');this.emit('star',{id:s.id});this.emit('save')}}
 target(){return this.job?.target||this.waypoint}
 jobText(){const j=this.job;if(!j)return'Choose a job, borrow a ride or just explore.';const def=JOBS.find(d=>d.id===j.id);return def.name+' · '+(j.id==='fishing'?(j.cast==='bite'?'BITE! GRAB NOW':j.cast?'Waiting for a bite':j.count+' / 3 fish · ACT to cast'):j.id==='rally'?j.count+' / 8 rings':j.stage==='pickup'?'Pick up '+(j.id==='taxi'||j.id==='rescue'?'passenger':'package'):j.stage==='drop'?'Drive passenger to destination':j.id==='builder'||j.id==='cleanup'?j.count+' / '+(j.id==='builder'?3:4)+' objects delivered':'Deliver package '+(j.count+1)+' / 3')+' · '+Math.ceil(j.left)+'s'}
}
globalThis.WobbleCore={World,JOBS,RIDES,HATS,HOMES,LANDMARKS,BUILDINGS,STARS,ROUTE,terrain,sanitize,clamp,lerp,dist,angle};
})();
