/* Grade School — original game rules and question generator. */
(function(root){
'use strict';
const SUBJECTS=[{id:'math',name:'Maths',short:'123',colour:'#f3b75d',day:1},{id:'english',name:'English',short:'Aa',colour:'#d291ab',day:1},{id:'science',name:'Science',short:'⚗',colour:'#8cb8a3',day:2},{id:'geography',name:'Geography',short:'◎',colour:'#82afca',day:2},{id:'history',name:'History',short:'⌛',colour:'#b8a1d0',day:3},{id:'art',name:'Art & logic',short:'✎',colour:'#e79b76',day:3}];
const STUDENTS=[
 ['Milo','A professional daydreamer.','#df9872','#49392e','#6ba49f',0],['Ruby','Always has a very good excuse.','#f2c3a4','#783e38','#d97879',1],['Theo','Future astronaut. Current doodler.','#9c674d','#24292c','#d5ac56',2],['Poppy','Reads the last page first.','#efba91','#b17d3e','#9397c3',3],['Arlo','Thinks every lesson needs a joke.','#bc825f','#49332c','#82a65f',0],['Freya','Knows things. Lots of things.','#f1c5a1','#50312d','#c688a4',1],['Kai','A calculator with trainers.','#d99d74','#222e32','#6f9cc1',2],['Bea','Collects stickers and compliments.','#ad7559','#39312d','#e9aa58',3],['Finn','The dog definitely ate it.','#efc3a3','#bf7543','#7eaf92',0],['Luna','Has at least three imaginary pets.','#c58e68','#322d35','#a894c4',1],['Oscar','Working on his next big invention.','#dbad88','#7b533b','#d68b66',2],['Ada','Writes beautifully. Spells creatively.','#925e49','#27272e','#77afba',3]
].map((s,i)=>({id:i,name:s[0],bio:s[1],skin:s[2],hair:s[3],shirt:s[4],style:s[5]}));
// Each row is a deliberately unambiguous question, accepted answer and wrong alternatives.
const BANK={
 english:[
 ['What is the plural of "child"?','Children',['Childs','Childrens','A whole classroom']],['Which word is a noun: quickly, table, or happy?','Table',['Quickly','Happy','All of them, probably']],['What is the opposite of "ancient"?','Modern',['Old','Very old','A dinosaur']],['Which word is a verb: run, blue, or pillow?','Run',['Blue','Pillow','Homework']],['Complete: "She ___ to school every day."','Goes',['Go','Going','Teleports']],['What is the past tense of "eat"?','Ate',['Eated','Eats','Hungry']],['Standard British spelling: colour or colur?','Colour',['Colur','Coulor','Crayon']],['What punctuation ends a direct question?','Question mark',['Full stop','Comma','A dramatic pause']],['What is the opposite of "generous"?','Stingy',['Kind','Giving','Extremely rich']],['What is the plural of "mouse" (the animal)?','Mice',['Mouses','Mousees','Tiny roommates']],['Which word describes a noun?','Adjective',['Verb','Preposition','A really long word']],['Complete: "___ going to be late."','They are',['Their','There','Them are']],['A comparison using "like" or "as" is a…','Simile',['Metaphor','Noun','Shopping review']],['Which is a synonym of "happy"?','Joyful',['Gloomy','Furious','Homework']],['How many vowels are in the word "apple"?','2',['1','3','5']],['What is the past tense of "write"?','Wrote',['Writed','Writtened','Forgot']],['Which word is spelled correctly?','Necessary',['Neccessary','Necesary','Nesesary']],['Which sentence uses an apostrophe for possession?','The cat’s toy',['The cats play','The cat is asleep','The cat’s are playing']]
 ],
 science:[
 ['Which planet is closest to the Sun?','Mercury',['Earth','Venus','My house in summer']],['How many legs does an insect have?','6',['8','4','Too many']],['Which organ pumps blood?','Heart',['Lungs','Brain','A tiny bicycle pump']],['What do plants take in during photosynthesis?','Carbon dioxide',['Oxygen','Orange juice','Homework']],['What gas do humans need to breathe?','Oxygen',['Helium','Carbon dioxide','Wi-Fi']],['At standard pressure, water freezes at…','0 °C',['100 °C','10 °C','When it feels like it']],['Which force pulls objects towards Earth?','Gravity',['Magnetism','Friction','A very large vacuum']],['A solid changing directly into a gas is…','Sublimation',['Melting','Condensation','Magic']],['Which state of matter has a fixed shape and volume?','Solid',['Liquid','Gas','Pudding']],['How many bones does a typical adult human have?','206',['106','306','A skeleton-full']],['What is Earth’s natural satellite?','The Moon',['Mars','The Sun','A giant lamp']],['Which material is usually a good electrical conductor?','Copper',['Rubber','Wood','A woolly jumper']],['Animals that eat only plants are…','Herbivores',['Carnivores','Omnivores','Gardeners']],['What is the largest planet in our solar system?','Jupiter',['Earth','Saturn','The school cafeteria']],['Which part of a plant usually absorbs water from soil?','Roots',['Flowers','Leaves','The gardener’s hat']],['A liquid changing into a gas is…','Evaporation',['Freezing','Condensation','Disappearing']],['What is the chemical symbol for gold?','Au',['Ag','Go','Shiny']],['Which animal is a mammal?','Dolphin',['Shark','Trout','Octopus']]
 ],
 geography:[
 ['What is the capital of France?','Paris',['Rome','Berlin','The Eiffel Tower']],['Which is the largest ocean?','Pacific Ocean',['Atlantic Ocean','Indian Ocean','The swimming pool']],['Which continent is Egypt in?','Africa',['Europe','Asia','Atlantis']],['Which direction is opposite to north?','South',['East','West','Backwards']],['What is the capital of Japan?','Tokyo',['Kyoto','Beijing','Sushi']],['What is the imaginary line at 0° latitude?','Equator',['Prime meridian','Tropic of Cancer','The finish line']],['Which country has the city of Barcelona?','Spain',['Italy','Portugal','France']],['Which continent contains the South Pole?','Antarctica',['Africa','Australia','The freezer']],['What is the capital of Italy?','Rome',['Venice','Madrid','Pizza']],['Which ocean lies between Europe and North America?','Atlantic Ocean',['Pacific Ocean','Indian Ocean','Arctic Ocean']],['A map’s key explains its…','Symbols',['Weather','Age','Secrets']],['Which country contains the Great Barrier Reef?','Australia',['New Zealand','South Africa','Brazil']],['What is the capital of the United Kingdom?','London',['Manchester','Edinburgh','The King’s kitchen']],['A narrow strip of land joining two larger areas is an…','Isthmus',['Island','Ocean','Land sandwich']],['Which is the largest hot desert?','Sahara',['Gobi','Kalahari','My garden in July']],['Which country has the Taj Mahal?','India',['China','Egypt','Turkey']]
 ],
 history:[
 ['Who was the first person to walk on the Moon?','Neil Armstrong',['Buzz Aldrin','Yuri Gagarin','My uncle Steve']],['In which year did humans first land on the Moon?','1969',['1959','1979','Last Tuesday']],['Ancient Egyptian rulers were called…','Pharaohs',['Emperors','Presidents','Pyramid managers']],['In which year did World War II end?','1945',['1939','1918','1955']],['The Roman numeral X means…','10',['5','100','Wrong answer']],['Who wrote "Romeo and Juliet"?','William Shakespeare',['Charles Dickens','Jane Austen','The drama teacher']],['Which civilisation built Machu Picchu?','Inca',['Roman','Viking','Minecraft players']],['The Magna Carta was first issued in…','1215',['1066','1492','1815']],['Who is associated with the theory of evolution by natural selection?','Charles Darwin',['Isaac Newton','Albert Einstein','The school hamster']],['The Roman numeral IV means…','4',['6','5','A very important person']],['In which year was the Battle of Hastings?','1066',['1215','1666','1966']],['Who painted the Mona Lisa?','Leonardo da Vinci',['Vincent van Gogh','Pablo Picasso','A really patient person']],['Which ancient civilisation used cuneiform writing?','Sumerian',['Aztec','Viking','Victorian']],['Who was the first president of the United States?','George Washington',['Abraham Lincoln','Thomas Jefferson','Benjamin Franklin']],['The Great Fire of London happened in…','1666',['1066','1766','1866']],['Which civilisation built the Colosseum?','Roman',['Greek','Egyptian','Inca']]
 ]};
const INCIDENTS=[
 {title:'The mysterious identical answers',text:'Milo and Ruby both wrote “Paris” for France’s capital. You saw no copying.',choices:['Punish both for cheating','Mark both answers correct','Give both an F'],right:1,why:'Matching correct answers are not evidence of cheating. Grade the work fairly.',scene:'twins'},
 {title:'A paper plane emergency',text:'Arlo is launching paper planes. Bea is quietly reading her book.',choices:['Ask Arlo to stop throwing planes','Send Bea out of the classroom','Ignore the flying planes'],right:0,why:'Address the behaviour you can actually see, calmly and specifically.',scene:'plane'},
 {title:'The suspicious note',text:'Finn’s paper says “PLEASE GIVE ME AN A”. His answer says 7 × 8 = 54.',choices:['Give an A for the polite note','Give an A because he looks sad','Mark the answer wrong'],right:2,why:'7 × 8 is 56. A polite note does not change the answer.',scene:'note'},
 {title:'A tiny classroom spill',text:'Luna knocked a cup of water onto the floor. Nobody is hurt.',choices:['Ask for a careful clean-up','Give everyone detention','Make the class run through it'],right:0,why:'A calm clean-up solves the problem and keeps the floor safe.',scene:'spill'},
 {title:'The forgotten glasses',text:'Theo can’t read the board from the back. He forgot his glasses.',choices:['Mark every answer wrong','Move him nearer the board','Tell him to guess faster'],right:1,why:'Give him a fair chance to see the question before judging his answer.',scene:'glasses'},
 {title:'One answer, two spellings',text:'The question asks for the colour of grass. Ada wrote “green”, Kai wrote “Green”.',choices:['Mark Kai wrong for the capital G','Mark both wrong','Accept both answers'],right:2,why:'Both answers name the same colour. Capitalisation is not what this question tests.',scene:'twins'},
 {title:'An unfinished worksheet',text:'Poppy left the last answer blank. Her first two answers are correct.',choices:['Count two correct and one incorrect','Give a perfect score','Ignore all three answers'],right:0,why:'Credit the correct work. A blank answer earns no mark on this worksheet.',scene:'note'},
 {title:'The doodle defence',text:'Oscar drew a rocket in the margin. All of his science answers are correct.',choices:['Fail him because of the rocket','Mark his answers correct','Take away two marks'],right:1,why:'A harmless doodle is not an incorrect science answer.',scene:'rocket'}
];
const SHOP=[
 {id:'room-mint',type:'room',name:'Mint classroom',price:0,colour:'#bddace'}, {id:'room-peach',type:'room',name:'Peach classroom',price:100,colour:'#eed0bc'}, {id:'room-blue',type:'room',name:'Blue classroom',price:180,colour:'#b5cedf'}, {id:'room-lavender',type:'room',name:'Lavender classroom',price:260,colour:'#cdc1df'},
 {id:'desk-oak',type:'desk',name:'Oak desk',price:0,colour:'#c38b61'}, {id:'desk-walnut',type:'desk',name:'Walnut desk',price:120,colour:'#835c48'}, {id:'desk-cream',type:'desk',name:'Cream desk',price:220,colour:'#e6d9b8'},
 {id:'stamp-red',type:'stamp',name:'Classic red pen',price:0,colour:'#cb5d59'},{id:'stamp-purple',type:'stamp',name:'Purple pen',price:90,colour:'#9471bc'},{id:'stamp-gold',type:'stamp',name:'Golden pen',price:300,colour:'#c59b42'},
 {id:'plant',type:'decor',name:'Window fern',price:80},{id:'globe',type:'decor',name:'Little blue globe',price:130},{id:'books',type:'decor',name:'Rainbow bookshelf',price:160},{id:'hamster',type:'decor',name:'Class hamster',price:240},{id:'clock',type:'decor',name:'Happy wall clock',price:110},{id:'bunting',type:'decor',name:'Celebration bunting',price:170}
];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=Math.imul(a^a>>>15,1|a);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296}}
function hash(s){let a=2166136261;for(const c of String(s)){a^=c.charCodeAt(0);a=Math.imul(a,16777619)}return a>>>0}
function choose(a,r){return a[Math.floor(r()*a.length)]}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function question(subject,level,r,index=0){
 const truthful=r()<.52;
 let prompt,answer,wrong,visual=null;
 if(subject==='math'){
  const tier=clamp(Math.floor((level-1)/3),0,5),kind=Math.floor(r()*(tier===0?3:6)),a=2+Math.floor(r()*(8+tier*7)),b=2+Math.floor(r()*(7+tier*3));
  if(kind===0){prompt=`${a} + ${b} = ?`;answer=a+b}else if(kind===1){prompt=`${a+b} − ${b} = ?`;answer=a}else if(kind===2){prompt=`${a} × ${b} = ?`;answer=a*b}else if(kind===3){prompt=`${a*b} ÷ ${b} = ?`;answer=a}else if(kind===4){prompt=`What is ${b*5}% of ${a*20}?`;answer=b*a}else{prompt=`Next number: ${a}, ${a+b}, ${a+b*2}, …`;answer=a+b*3}
  wrong=[String(answer+1),String(answer+b),String(Math.max(0,answer-2)),choose(['A potato','Ask my calculator','Infinity plus one','My dog knows','A very big number'],r)];answer=String(answer);
 }else if(subject==='art'){
  const kind=Math.floor(r()*5),colours=[['red','#d76662'],['blue','#6d9bc5'],['green','#69a389'],['yellow','#e2bc56'],['purple','#aa87c0']];
  if(kind===0){const sides=choose([3,4,5,6,8],r);prompt='How many sides does this shape have?';answer=String(sides);wrong=[String(sides+1),String(sides-1),'A hundred'];visual={kind:'polygon',sides,colour:'#8fbca8'}}
  else if(kind===1){const [name,hex]=choose(colours,r);prompt='What colour is the paint swatch?';answer=name[0].toUpperCase()+name.slice(1);wrong=colours.filter(c=>c[0]!==name).map(c=>c[0][0].toUpperCase()+c[0].slice(1));visual={kind:'swatch',colour:hex}}
  else if(kind===2){const n=3+Math.floor(r()*7);prompt='Count the gold stars.';answer=String(n);wrong=[String(n+1),String(n-1),'Enough for everyone'];visual={kind:'stars',count:n}}
  else if(kind===3){const step=choose([2,3,4,5],r),start=1+Math.floor(r()*8);prompt=`Complete the pattern: ${start}, ${start+step}, ${start+step*2}, ?`;answer=String(start+step*3);wrong=[String(start+step*4),String(start+step*3+1),'Banana']}
  else{const item=choose([['A triangle has how many corners?','3',['4','2','It depends on its mood']],['A square has how many equal sides?','4',['3','5','None']],['Which two primary paint colours mix to make orange?','Red and yellow',['Blue and red','Blue and yellow','Orange and more orange']],['A shape with five sides is a…','Pentagon',['Hexagon','Triangle','Very confused square']],['Red, yellow and blue are traditional paint…','Primary colours',['Secondary colours','Invisible colours','Breakfast colours']]],r);[prompt,answer,wrong]=item}
 }else{
  const rows=BANK[subject]||BANK.english,item=rows[index%rows.length];[prompt,answer,wrong]=item;
 }
 return{subject,prompt,answer,submitted:truthful?answer:choose(wrong,r),correct:truthful,visual};
}
function grade(n,total){const p=n/total;return p>=1?'A+':p>=.75?'B':p>=.5?'C':p>0?'D':'F'}
function expected(round){return round.kind==='incident'?String(round.incident.right):round.kind==='worksheet'?grade(round.questions.filter(q=>q.correct).length,round.questions.length):round.questions[0].correct?'A+':'F'}
function makeRounds(session){
 const r=rng(session.seed),day=session.day,mode=session.mode,subjects=SUBJECTS.filter(s=>mode!=='career'||day>=s.day),order=shuffle(subjects,r),bankOrders={};for(const [k,v]of Object.entries(BANK))bankOrders[k]=shuffle(v.map((_,i)=>i),r);
 const length=mode==='rush'?150:mode==='endless'?150:mode==='daily'?12:day<3?6:8;
 const rounds=[];
 for(let i=0;i<length;i++){
  const student=STUDENTS[(Math.floor(r()*12)+i)%12],subject=order[i%order.length].id,level=mode==='career'?day:mode==='endless'?5+Math.floor(i/12):7;
  if((mode==='career'&&day>=2&&i===(day%5===0?2:length-2))||(mode==='daily'&&i===5)||(mode==='endless'&&i%12===11)){
   rounds.push({kind:'incident',student,incident:INCIDENTS[((mode==='career'?day:session.seed%INCIDENTS.length)+Math.floor(i/12)-2+INCIDENTS.length)%INCIDENTS.length],subject:'homeroom'});continue;
  }
  const multiple=(mode==='career'?day>=5:mode!=='rush')&&i%4===3,count=multiple?4:1,questions=[];
  for(let j=0;j<count;j++){const o=bankOrders[subject];let q=question(subject,level,r,o?o[(Math.floor(i/order.length)*count+j+session.seed%o.length)%o.length]:i*count+j);for(let tries=0;tries<8&&questions.some(x=>x.prompt===q.prompt);tries++)q=question(subject,level,r,o?o[(i*count+j+tries+1)%o.length]:i*count+j);questions.push(q)}
  rounds.push({kind:multiple?'worksheet':'paper',student,subject,questions,inspection:mode==='career'&&day%5===0&&i>=length-3});
 }
 return rounds;
}
function sanitiseSession(d){if(!d||!['career','endless','rush','daily'].includes(d.mode)||!Number.isFinite(d.seed))return null;const day=clamp(Math.floor(Number(d.day)||1),1,9999),limit=d.mode==='career'?(day<3?6:8):d.mode==='daily'?12:150,marks=Array.isArray(d.marks)?d.marks.slice(0,limit).map(v=>typeof v==='string'&&/^(A\+|B|C|D|F|[0-2]|timeout)$/.test(v)?v:'timeout'):[];return{mode:d.mode,day,seed:d.seed>>>0,marks,hinted:Array.isArray(d.hinted)?[...new Set(d.hinted.filter(v=>Number.isInteger(v)&&v>=0&&v<limit))]:[],timeLeft:clamp(Number(d.timeLeft)||0,0,60),paperTime:clamp(Number.isFinite(Number(d.paperTime))?Number(d.paperTime):15,0,15),date:/^\d{4}-\d{2}-\d{2}$/.test(d.date||'')?d.date:'',settled:d.settled===true};}
function sanitise(d={}){
 if(!d||typeof d!=='object')d={};const n=(k,max,def=0)=>clamp(Number.isFinite(Number(d[k]))?Math.floor(Number(d[k])):def,0,max),owned=[...new Set(['room-mint','desk-oak','stamp-red',...(Array.isArray(d.owned)?d.owned.filter(v=>SHOP.some(x=>x.id===v)):[])])],p=d.prefs&&typeof d.prefs==='object'?d.prefs:{};const equipped={};for(const [key,def]of [['room','room-mint'],['desk','desk-oak'],['stamp','stamp-red']])equipped[key]=owned.includes(d.equipped?.[key])&&SHOP.find(i=>i.id===d.equipped[key])?.type===key?d.equipped[key]:def;
 return{version:1,day:Math.max(1,n('day',9999,1)),coins:n('coins',1e8),reputation:n('reputation',100,70),total:n('total',1e7),correct:Math.min(n('correct',1e7),n('total',1e7)),bestStreak:n('bestStreak',150),bestRush:n('bestRush',150),bestEndless:n('bestEndless',150),stars:n('stars',30000),owned,equipped,prefs:{sound:p.sound!==false,timers:p.timers!==false,motion:p.motion!==false,large:p.large!==false},daily:{date:/^\d{4}-\d{2}-\d{2}$/.test(d.daily?.date||'')?d.daily.date:'',score:clamp(Math.floor(Number(d.daily?.score)||0),0,12)},session:sanitiseSession(d.session)};
}
class School {
 constructor(save){this.save=sanitise(save);this.session=this.save.session;this.rounds=this.session?makeRounds(this.session):[];}
 get round(){return this.rounds[this.session?.marks.length||0]}
 get index(){return this.session?.marks.length||0}
 get accuracy(){return this.save.total?Math.round(this.save.correct/this.save.total*100):100}
 get streak(){if(!this.session)return 0;let n=0;for(let i=this.index-1;i>=0;i--){if(this.session.marks[i]!==expected(this.rounds[i]))break;n++}return n}
 start(mode='career',seed=Date.now(),date=''){this.session={mode,day:this.save.day,seed:mode==='daily'?hash('grade-school:'+date):seed>>>0,marks:[],hinted:[],timeLeft:60,paperTime:15,date,settled:false};this.save.session=this.session;this.rounds=makeRounds(this.session);return this.round}
 get finished(){if(!this.session)return true;return this.session.settled||this.index>=this.rounds.length||(this.session.mode==='rush'&&this.session.timeLeft<=0)||(this.session.mode==='endless'&&this.mistakes>=3)}
 get mistakes(){return this.session?this.session.marks.filter((a,i)=>a!==expected(this.rounds[i])).length:0}
 hint(){if(!this.session||this.finished||this.session.hinted.includes(this.index))return false;this.session.hinted.push(this.index);return true}
 submit(choice){
  if(this.finished||!this.round)return null;
  const round=this.round,answer=expected(round),valid=round.kind==='incident'?['0','1','2']:round.kind==='worksheet'?['A+','B','C','D','F']:['A+','F'];if(!valid.includes(String(choice))&&choice!=='timeout')return null;
  const correct=choice===answer,hinted=this.session.hinted.includes(this.index);this.session.marks.push(String(choice));this.session.paperTime=15;this.save.total++;if(correct)this.save.correct++;const streak=this.streak,coins=correct?(hinted?1:5+Math.min(5,Math.floor(streak/3))+(round.inspection?3:0)):0;this.save.coins+=coins;this.save.reputation=clamp(this.save.reputation+(correct?1:-3),0,100);this.save.bestStreak=Math.max(this.save.bestStreak,streak);return{correct,answer,coins,hinted,round,choice};
 }
 tick(dt){if(!this.session||this.finished)return null;dt=clamp(Number(dt)||0,0,1);if(this.session.mode==='rush')this.session.timeLeft=Math.max(0,this.session.timeLeft-dt);if(this.round?.inspection&&this.save.prefs.timers){this.session.paperTime=Math.max(0,this.session.paperTime-dt);if(this.session.paperTime===0)return this.submit('timeout')}return null}
 settle(){if(!this.session||this.session.settled||!this.finished)return null;const s=this.session,right=this.index-this.mistakes,record=s.marks.filter((a,i)=>a===expected(this.rounds[i])&&!s.hinted.includes(i)).length,ratio=this.index?right/this.index:0,stars=ratio===1?3:ratio>=.75?2:ratio>=.5?1:0,bonus=s.mode==='career'?10+stars*5:0;this.save.coins+=bonus;if(s.mode==='career'){this.save.day=Math.min(9999,s.day+1);this.save.stars+=stars}if(s.mode==='rush')this.save.bestRush=Math.max(this.save.bestRush,record);if(s.mode==='endless')this.save.bestEndless=Math.max(this.save.bestEndless,record);if(s.mode==='daily'&&s.date){if(this.save.daily.date!==s.date)this.save.daily={date:s.date,score:record};else this.save.daily.score=Math.max(this.save.daily.score,record)}s.settled=true;return{right,total:this.index,stars,bonus,mode:s.mode,day:s.day,record}}
 purchase(id){const item=SHOP.find(i=>i.id===id);if(!item)return false;if(!this.save.owned.includes(id)){if(this.save.coins<item.price)return false;this.save.coins-=item.price;this.save.owned.push(id)}if(item.type!=='decor')this.save.equipped[item.type]=id;return true}
 export(){return JSON.parse(JSON.stringify(this.save))}
}
root.GradeCore={SUBJECTS,STUDENTS,SHOP,BANK,INCIDENTS,rng,hash,question,grade,expected,makeRounds,sanitise,School};
})(typeof globalThis!=='undefined'?globalThis:this);
