/* Original classroom artwork, touch UI and audio for Grade School. */
(() => {
'use strict';
const C=globalThis.GradeCore,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!C){$('fatal').hidden=false;return}
let initial=window.__POCKETVM_SAVE;try{if(!initial)initial=JSON.parse(localStorage.getItem('pocketvm.game.gradeschool')||'null')}catch{}
const school=new C.School(initial||{}),canvas=$('room'),g=canvas.getContext('2d');
let modalName='',modalReturn='',result=null,activeStudent=C.STUDENTS[0],emotion=0,emotionUntil=0,frameTime=0,last=0,lastDraw=0,lastSave=0,hidden=document.hidden,paused=false,toastTimer=0,audio=null,feedbackUntil=0,lastFocus=null;
const idleLines=['I studied. Mostly.','My brain is still loading.','Please admire my handwriting.','Is lunch a subject?','I have a very good feeling.','My dog checked this one.','No pressure, but my mum is waiting.','I definitely used a pencil.','Can effort count as an answer?','I was listening. To something.','This is my final-ish answer.','Please ignore the doodle.'];
const correctLines=['I knew you’d understand!','A+? A-plus-tastic!','I’m telling everyone.','That one was definitely mine.','Can I frame this?'];
const fairLines=['Okay. I’ll try that again.','Right. Learning happened.','My calculator owes me an apology.','I was testing you, obviously.','At least the doodle was good.'];
const unfairLines=['Wait… could you check that again?','I think my paper needs a second look.','But that doesn’t match the answer key.'];
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function localDate(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function save(){try{localStorage.setItem('pocketvm.game.gradeschool',JSON.stringify(school.export()))}catch{}if(window.parent!==window)window.parent.postMessage({type:'pocketvm-grade-save',data:school.export()},'*');lastSave=performance.now()}
function ready(){if(window.parent!==window)window.parent.postMessage({type:'pocketvm-grade-ready'},'*')}
function sound(type){if(!school.save.prefs.sound)return;try{audio ||=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime,notes=type==='bell'?[[880,0,.18],[1108,.12,.16],[1318,.24,.3]]:type==='good'?[[660,0,.08],[880,.08,.12],[1108,.17,.18]]:type==='bad'?[[230,0,.13],[175,.1,.19]]:type==='buy'?[[520,0,.08],[780,.07,.1],[1040,.14,.14]]:[[220,0,.055]];for(const [freq,delay,duration]of notes){const o=audio.createOscillator(),v=audio.createGain();o.type=type==='stamp'?'triangle':'sine';o.frequency.setValueAtTime(freq,now+delay);v.gain.setValueAtTime(0,now+delay);v.gain.linearRampToValueAtTime(.08,now+delay+.01);v.gain.exponentialRampToValueAtTime(.0001,now+delay+duration);o.connect(v);v.connect(audio.destination);o.start(now+delay);o.stop(now+delay+duration+.03)}}catch{}}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2400)}
function prefs(){document.body.classList.toggle('no-motion',!school.save.prefs.motion);document.body.classList.toggle('large-controls',school.save.prefs.large);const pen=C.SHOP.find(x=>x.id===school.save.equipped.stamp);document.documentElement.style.setProperty('--stamp',pen.colour)}
function stats(){const s=school.save;$('coins').textContent=s.coins.toLocaleString();$('reputation').textContent=s.reputation;$('accuracy').textContent=school.accuracy+'%';$('streak').textContent=school.streak;$('bestStreak').textContent=s.bestStreak;const mode=school.session?.mode;$('sideLabel').textContent=mode==='rush'?'Seconds left':mode==='endless'?'Mistakes left':'Papers marked';$('sideValue').textContent=mode==='rush'?Math.ceil(school.session.timeLeft):mode==='endless'?3-school.mistakes:s.total;}
function svgVisual(v){if(!v)return'';if(v.kind==='swatch')return'<svg class="visual" viewBox="0 0 280 90" aria-label="'+esc(C.SHOP.find(x=>x.colour===v.colour)?.name||'Paint colour swatch')+'"><path d="M57 11h163l-9 10 17 11-8 13 10 10-17 12 5 13H56l9-10-13-9 10-14-9-11 11-11z" fill="'+v.colour+'"/><path d="M76 25h126M72 39h131M83 54h115" stroke="#fff" stroke-opacity=".15" stroke-width="5"/></svg>';
 if(v.kind==='polygon'){let p=[];for(let i=0;i<v.sides;i++){const a=-Math.PI/2+i*Math.PI*2/v.sides;p.push((140+Math.cos(a)*40)+','+(45+Math.sin(a)*38))}return'<svg class="visual" viewBox="0 0 280 90" aria-label="Outlined shape"><polygon points="'+p.join(' ')+'" fill="'+v.colour+'" stroke="#426c5a" stroke-width="3" stroke-linejoin="round"/></svg>'}
 let stars='';for(let i=0;i<v.count;i++){const x=32+(i%5)*51,y=v.count>5?25+Math.floor(i/5)*43:45;let p=[];for(let j=0;j<10;j++){const a=-Math.PI/2+j*Math.PI/5,r=j%2?8:18;p.push((x+Math.cos(a)*r)+','+(y+Math.sin(a)*r))}stars+='<polygon points="'+p.join(' ')+'" fill="#e7b653" stroke="#9a7437" stroke-width="1.5"/>'}return'<svg class="visual" viewBox="0 0 280 90" aria-label="Gold stars to count">'+stars+'</svg>';
}
function paperHTML(round){return round.questions.map((q,i)=>'<section class="question-block"><span class="question-number">'+(round.kind==='worksheet'?'QUESTION '+(i+1):'THE QUESTION')+'</span><div class="question">'+esc(q.prompt)+'</div>'+svgVisual(q.visual)+'<span class="answer-label">STUDENT’S ANSWER</span><div class="answer">'+esc(q.submitted)+'</div></section>').join('')}
function buttonGrade(value,label,good){return'<button class="stamp '+(good?'good':'bad')+'" data-grade="'+value+'" aria-label="'+esc(label)+'"><span class="stamp-mark">'+value+'</span><span><b>'+esc(label)+'</b><small>STAMP THE PAPER</small></span></button>'}
function renderRound(){
 if(!school.session||school.finished){showSummary();return}
 result=null;$('feedback').hidden=true;$('hintBox').hidden=true;const round=school.round,mode=school.session.mode,subject=C.SUBJECTS.find(s=>s.id===round.subject),count=school.rounds.length;activeStudent=round.student;emotion=0;$('studentName').textContent=activeStudent.name;$('studentBio').textContent=activeStudent.bio;$('speech').textContent=idleLines[activeStudent.id];$('paperName').textContent=activeStudent.name;$('paperNumber').textContent='No. '+String(school.index+1).padStart(3,'0');$('lessonMeta').textContent=(mode==='career'?'DAY '+school.session.day:mode==='daily'?'DAILY CHALLENGE':mode==='rush'?'BELL RUSH':'CLASS MARATHON')+' · '+(subject?.name||'CLASSROOM');$('countMeta').textContent=mode==='rush'?Math.ceil(school.session.timeLeft)+' SECONDS':mode==='endless'?'PAPER '+(school.index+1)+' · '+(3-school.mistakes)+' LIVES':'PAPER '+(school.index+1)+' / '+count;$('progressFill').style.width=(mode==='rush'?(60-school.session.timeLeft)/60*100:school.index/count*100)+'%';$('boardSmall').textContent=round.inspection?'THE PRINCIPAL IS WATCHING':mode==='career'?'WILLOWBROOK · DAY '+school.session.day:'WILLOWBROOK · AFTER SCHOOL';$('boardTitle').textContent=round.kind==='incident'?'Classroom moment':subject?.name||'Classroom';$('paperTag').textContent=round.kind==='incident'?'STAFF NOTE':subject.name.toUpperCase();$('paperTag').style.background=subject?subject.colour+'44':'#d9e3c5';$('paper').classList.toggle('worksheet',round.kind==='worksheet');$('paper').classList.remove('enter');if(school.save.prefs.motion)requestAnimationFrame(()=>$('paper').classList.add('enter'));
 $('paperTitle').textContent=round.kind==='incident'?round.incident.title:round.kind==='worksheet'?'The whole worksheet':'A little pop quiz';$('rubricNote').hidden=round.kind!=='worksheet';$('rubricNote').textContent='Grade all 4 answers: 4 correct = A+ · 3 = B · 2 = C · 1 = D · 0 = F.';$('rubric').hidden=round.kind!=='worksheet';$('doodle').textContent=['☆','✿','☁','⌁','♡','☀'][activeStudent.id%6];$('doodle').hidden=round.kind==='incident';$('inspection').hidden=!round.inspection||!school.save.prefs.timers;$('inspectionTime').textContent=Math.ceil(school.session.paperTime);
 const actions=$('actions');actions.className='actions';
 if(round.kind==='incident'){
  $('questions').innerHTML='<section class="question-block"><div class="question" style="font-size:19px">'+esc(round.incident.text)+'</div><div class="rubric-note">Pick the fairest response to what you can see.</div></section>';
  actions.classList.add('incident-choices');actions.innerHTML=round.incident.choices.map((s,i)=>'<button data-grade="'+i+'">'+esc(s)+'</button>').join('');$('keyboardHint').textContent='Press 1, 2 or 3';$('notebookHelp').textContent='Take a breath. Check the evidence. Choose the response that helps the class learn.';
 }else{
  $('questions').innerHTML=paperHTML(round);$('notebookHelp').innerHTML='Read the question and the student’s answer. '+(round.kind==='worksheet'?'Count how many answers are correct, then use the rubric.':'A+ for correct. F for incorrect.')+'<br><br>Yes, even if their excuse is excellent.';
  if(round.kind==='worksheet'){actions.classList.add('grades');actions.innerHTML=['A+','B','C','D','F'].map(a=>buttonGrade(a,a,a!=='F')).join('');$('keyboardHint').textContent='Keys 1–5 · A+ / B / C / D / F'}else{actions.innerHTML=buttonGrade('F','Incorrect',false)+buttonGrade('A+','Correct',true);$('keyboardHint').innerHTML='← F &nbsp; · &nbsp; A+ →'}
 }
 for(const b of actions.querySelectorAll('[data-grade]'))b.addEventListener('click',()=>mark(b.dataset.grade));$('hintButton').disabled=false;if(school.session.hinted.includes(school.index))showHint(false);$('paper').scrollTop=0;stats();save();
}
function explanation(round){if(round.kind==='incident')return esc(round.incident.why);return round.questions.map((q,i)=>'<div>'+(round.kind==='worksheet'?'<b>'+(i+1)+'.</b> ':'')+esc(q.prompt)+'<br><b style="color:#325e4c">Answer: '+esc(q.answer)+'</b>'+(round.kind==='worksheet'?' <span style="color:'+(q.correct?'#3a7c68':'#c2645b')+'">'+(q.correct?'✓ Correct':'✗ Incorrect')+'</span>':'')+'</div>').join('<div style="height:10px"></div>')}
function showHint(record=true){if(record&&!school.hint())return;const round=school.round;$('hintBox').hidden=false;$('hintBox').innerHTML='<b>Answer key</b> · '+(round.kind==='incident'?esc(round.incident.why):round.questions.map(q=>esc(q.answer)).join(' · '))+'<br><small>Practice help: a correct stamp earns 1 coin. Hinted papers don’t count towards challenge records.</small>';$('hintButton').disabled=true;save();}
function mark(choice){if(modalName||result||school.finished||hidden||paused)return;sound('stamp');const answer=school.submit(choice);if(!answer)return;result=answer;feedbackUntil=frameTime+.42;emotion=answer.correct?1:-1;emotionUntil=frameTime+3.5;const pupilRight=answer.round.questions?.every(q=>q.correct);$('speech').textContent=answer.correct?(pupilRight?pick(correctLines):pick(fairLines)):pick(unfairLines);
 if(school.session.mode==='rush'){
  $('feedback').innerHTML='<div class="seal">'+(answer.correct?'GOOD MARK!':'CHECK THE KEY')+'</div><p class="correct-answer">'+explanation(answer.round)+'</p><p class="reward">'+(answer.correct?'+'+answer.coins+' coins':'Correct stamp: '+answer.answer)+'</p><button class="primary" id="nextPaper">Next paper →</button>';
 }else{
  $('feedback').innerHTML='<div class="seal">'+(answer.correct?'FAIR & SQUARE':'SECOND LOOK!')+'</div><h2>'+(answer.correct?'Good marking, teacher.':'That stamp needs a correction.')+'</h2><div class="correct-answer"><p style="margin:0">'+explanation(answer.round)+'</p></div><p style="text-align:center;margin-top:15px">'+(answer.round.kind==='incident'?'Classroom judgement':answer.round.kind==='worksheet'?'The worksheet deserves <b>'+answer.answer+'</b>.':'This answer deserves <b>'+answer.answer+'</b>.')+'</p><p class="reward">'+(answer.correct?'+'+answer.coins+' coins'+(answer.hinted?' · Answer-key help':school.streak>=3?' · '+school.streak+'-paper streak!':''):'Keep going. The next paper is a fresh start.')+'</p><button class="primary" id="nextPaper">'+(school.finished?'Ring the bell →':'Next student →')+'</button>';
 }
 $('feedback').classList.toggle('wrong',!answer.correct);$('feedback').hidden=false;$('nextPaper').addEventListener('click',next);$('nextPaper').focus({preventScroll:true});sound(answer.correct?'good':'bad');if(answer.correct&&school.streak>0&&school.streak%5===0)confetti(12);stats();save();
}
function next(){if(modalName||!result||frameTime<feedbackUntil)return;if(school.finished){showSummary();return}renderRound()}
function confetti(n=28){if(!school.save.prefs.motion)return;for(let i=0;i<n;i++){const b=document.createElement('i');b.className='confetti';b.style.left=25+Math.random()*50+'%';b.style.top=20+Math.random()*15+'%';b.style.background=['#e9b755','#cb7775','#74a694','#9a8db8'][i%4];b.style.setProperty('--dx',(Math.random()-.5)*450+'px');b.style.setProperty('--dy',200+Math.random()*350+'px');document.body.appendChild(b);setTimeout(()=>b.remove(),1800)}}
function openModal(name,html){lastFocus=document.activeElement;$('modal').innerHTML=html;$('modalBackdrop').hidden=false;modalName=name;$('modal').scrollTop=0;const focus=$('modal').querySelector('button,input');focus?.focus({preventScroll:true});}
function closeModal(){modalName='';$('modalBackdrop').hidden=true;last=performance.now();lastFocus?.focus?.({preventScroll:true})}
function modalHead(title){return'<div class="modal-head"><h2>'+esc(title)+'</h2><button class="icon-button" data-close aria-label="Close menu">×</button></div>'}
function bindClose(back){$('modal').querySelector('[data-close]')?.addEventListener('click',()=>back?back():closeModal())}
function titleArt(){return'<svg viewBox="0 0 260 280" aria-hidden="true"><ellipse cx="127" cy="253" rx="96" ry="16" fill="#254d4120"/><g transform="rotate(-8 127 137)"><rect x="34" y="19" width="181" height="230" rx="12" fill="#dfcaa3"/><rect x="27" y="12" width="181" height="230" rx="12" fill="#fff9e8" stroke="#32554a" stroke-width="3"/><path d="M48 92h120m-120 31h138m-138 31h138m-138 31h78" stroke="#9db4b0" stroke-width="3"/><path d="M55 14h58l6 21H49z" fill="#d8cbb0" stroke="#6b8670" stroke-width="2"/><circle cx="149" cy="198" r="37" fill="#e2ebd1" stroke="#3c8066" stroke-width="3"/><text x="149" y="212" text-anchor="middle" fill="#3c8066" font-family="cursive" font-size="39" font-weight="bold">A+</text><path d="M53 51l17 18 27-28" fill="none" stroke="#cc6b60" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></g><g transform="rotate(31 195 123)"><path d="M184 40h23v166l-12 23-11-23z" fill="#e6b857" stroke="#32554a" stroke-width="3"/><path d="M184 59h23M195 61v143" stroke="#f4d88c" stroke-width="4"/><path d="M184 202l11 25 12-25" fill="#e6d1ab" stroke="#32554a" stroke-width="3"/><path d="M191 218l4 9 5-9" fill="#32554a"/><rect x="184" y="33" width="23" height="22" rx="7" fill="#d38586" stroke="#32554a" stroke-width="3"/></g><path d="M225 12l4 10 11 4-11 4-4 11-4-11-10-4 10-4z" fill="#e4b44d"/></svg>'}
function welcome(){
 const active=school.session&&!school.session.settled&&!school.finished,day=school.save.day;
 openModal('welcome','<div class="title-card"><div><span class="eyebrow">Welcome to Willowbrook</span><h1>Grade<br><em>School.</em></h1><p>They’ve done the homework.<br>You decide if any of it makes sense.</p><button class="primary" id="careerStart">'+(active?'Continue '+(school.session.mode==='career'?'day '+school.session.day:'your class'):'Start school day '+day)+' →</button></div><div class="title-art">'+titleArt()+'</div></div><div class="mode-grid"><button class="mode" data-mode="rush"><strong>◷ Bell Rush</strong><small>60 seconds. How many fair stamps?<br>Best: '+school.save.bestRush+'</small></button><button class="mode" data-mode="endless"><strong>♡ Class Marathon</strong><small>Three mistakes. Up to 150 papers.<br>Best: '+school.save.bestEndless+'</small></button><button class="mode" data-mode="daily"><strong>☀ Daily class</strong><small>12 shared-seed papers.<br>'+(school.save.daily.date===localDate()?'Today’s best: '+school.save.daily.score+'/12':'A fresh challenge every day.')+'</small></button></div><div class="modal-footer"><button class="text-button" id="welcomeShop">Classroom upgrades</button><button class="text-button" id="welcomeHelp">How to play</button><button class="text-button" id="welcomeSettings">Settings</button></div>');
 $('careerStart').addEventListener('click',()=>{if(active){closeModal();renderRound()}else lessonStart()});for(const b of $('modal').querySelectorAll('[data-mode]'))b.addEventListener('click',()=>confirmMode(b.dataset.mode));$('welcomeShop').addEventListener('click',()=>shop('welcome'));$('welcomeSettings').addEventListener('click',()=>settings('welcome'));$('welcomeHelp').addEventListener('click',()=>help('welcome'));stats();
}
function confirmMode(mode){if(school.session&&!school.session.settled&&!school.finished){openModal('replace',modalHead('Switch class?')+'<p class="lesson-choice">Your coins and completed marks are saved. Starting another mode replaces the unfinished class.</p><button class="primary" id="switchMode">Start '+(mode==='rush'?'Bell Rush':mode==='daily'?'Daily class':'Class Marathon')+'</button><div class="modal-footer"><button class="text-button" id="keepClass">Keep current class</button></div>');bindClose(welcome);$('keepClass').addEventListener('click',welcome);$('switchMode').addEventListener('click',()=>begin(mode));return}begin(mode)}
function lessonStart(){const day=school.save.day,unlocks=C.SUBJECTS.filter(s=>s.day===day&&day>1),inspection=day%5===0;openModal('lesson',modalHead('School day '+day)+'<div class="lesson-choice"><span class="eyebrow">TODAY’S TIMETABLE</span><h2 style="margin:8px 0 12px;font-size:24px">'+(inspection?'The principal is visiting.':unlocks.length?'New subjects on the timetable!':'Fresh papers. Fresh excuses.')+'</h2><p style="margin:0">'+(unlocks.length?'Now teaching '+unlocks.map(s=>s.name).join(' and ')+'. ':day===1?'Tap <b>A+</b> for a correct answer and <b>F</b> for an incorrect one. ':'')+(day>=5?'Some students hand in a whole worksheet. Count all four answers and use the grade rubric. ':'')+(inspection?'The final three papers have a 15-second inspection timer. You can switch this off in Settings.':'There is no time limit. Take a moment to read each answer.')+'</p></div><button class="primary" id="ringIn" style="width:100%">Ring the bell →</button>');bindClose(welcome);$('ringIn').addEventListener('click',()=>begin('career'))}
function begin(mode){school.start(mode,Date.now()^(Math.random()*0xffffffff),localDate());closeModal();paused=false;renderRound();sound('bell');save();}
function showSummary(){
 const settlement=school.settle();if(settlement){save();sound('bell');if(settlement.stars>=2||settlement.right>=8)confetti()}
 const s=school.session;if(!s){welcome();return}const right=school.index-school.mistakes,stars=school.index&&right===school.index?3:right/school.index>=.75?2:right/school.index>=.5?1:0,mode=s.mode,record=mode==='rush'?school.save.bestRush:mode==='endless'?school.save.bestEndless:mode==='daily'?school.save.daily.score:null;
 openModal('summary','<div class="summary"><span class="eyebrow" style="display:block;text-align:center">'+(mode==='career'?'DAY '+s.day+' COMPLETE':mode==='daily'?'DAILY CLASS COMPLETE':mode==='rush'?'THE BELL HAS RUNG':'CLASS DISMISSED')+'</span><div class="summary-stars">'+('★'.repeat(stars)+'☆'.repeat(3-stars))+'</div><h2 class="summary-title">'+(stars===3?'Teacher of the day!':stars===2?'Nicely marked.':stars===1?'Room to grow.':'Another lesson learned.')+'</h2><p class="summary-sub">'+(mode==='career'?'Day '+school.save.day+' is ready when you are.':mode==='rush'?'Every fair stamp before the bell counts.':mode==='daily'?'Come back tomorrow for a new set of papers.':'Three mistakes ends the marathon. All 150 papers is a complete run.')+'</p><div class="summary-grid"><div><b>'+right+'/'+school.index+'</b><small>Fair judgements</small></div><div><b>'+(mode==='career'?'+'+(10+stars*5):record)+'</b><small>'+(mode==='career'?'Day bonus coins':'Your best score')+'</small></div><div><b>'+school.save.coins+'</b><small>Coins to spend</small></div></div><button class="primary" id="summaryNext">'+(mode==='career'?'Next school day →':'Play again →')+'</button><div class="modal-footer"><button class="text-button" id="summaryShop">Upgrade the classroom</button><button class="text-button" id="summaryMenu">Main menu</button></div></div>');$('summaryNext').addEventListener('click',()=>mode==='career'?lessonStart():begin(mode));$('summaryShop').addEventListener('click',()=>shop('summary'));$('summaryMenu').addEventListener('click',welcome);stats();
}
function menu(){if(modalName==='welcome')return;openModal('pause',modalHead('The class is paused')+'<div class="lesson-choice">Take your time. Papers and timers wait while the menu is open.</div><button class="primary" id="resumeClass" style="width:100%">Back to class →</button><div class="mode-grid"><button class="mode" id="pauseShop"><strong>Classroom</strong><small>Spend your earned coins.</small></button><button class="mode" id="pauseSettings"><strong>Settings</strong><small>Sound, motion and timers.</small></button><button class="mode" id="pauseHelp"><strong>How to play</strong><small>A few teacher’s notes.</small></button></div><div class="modal-footer"><button class="text-button" id="mainMenu">Main menu · keep this class</button></div>');bindClose(closeModal);$('resumeClass').addEventListener('click',()=>{paused=false;closeModal()});$('pauseShop').addEventListener('click',()=>shop('pause'));$('pauseSettings').addEventListener('click',()=>settings('pause'));$('pauseHelp').addEventListener('click',()=>help('pause'));$('mainMenu').addEventListener('click',welcome);save();}
function goBack(back){if(back==='welcome')welcome();else if(back==='summary')showSummary();else menu()}
function shop(back='pause'){
 modalReturn=back;const icons={room:'▦',desk:'▰',stamp:'A+',plant:'✿',globe:'🌐',books:'▤',hamster:'🐹',clock:'◷',bunting:'⚑'};openModal('shop',modalHead('Make it your classroom')+'<p style="color:#71816c;font-size:13px;line-height:1.5;margin:0 0 19px">'+school.save.coins+' coins saved. Every upgrade is cosmetic — your judgement earns the marks.</p><div class="shop-grid">'+C.SHOP.map(item=>{const owned=school.save.owned.includes(item.id),equipped=school.save.equipped[item.type]===item.id;return'<article class="shop-item"><div class="swatch" style="background:'+(item.colour||'#dce6cc')+';color:'+(item.type==='stamp'?'#fff5dd':'#385f50')+'">'+icons[item.type==='decor'?item.id:item.type]+'</div><strong>'+esc(item.name)+'</strong><button data-buy="'+item.id+'" class="'+(equipped?'equipped':'')+'" '+(!owned&&school.save.coins<item.price?'disabled':'')+'>'+(equipped?'Equipped':owned?item.type==='decor'?'In your classroom':'Equip':item.price+' coins')+'</button></article>'}).join('')+'</div>');bindClose(()=>goBack(back));for(const b of $('modal').querySelectorAll('[data-buy]'))b.addEventListener('click',()=>{if(school.purchase(b.dataset.buy)){prefs();save();stats();sound('buy');shop(back);toast('A little classroom glow-up.')}})
}
function settings(back='pause'){modalReturn=back;openModal('settings',modalHead('Teacher’s settings')+[['sound','Sound effects','Soft classroom bells, stamps and reward notes.'],['timers','Principal inspection timers','Turn off the 15-second inspection limit. Bell Rush always lasts 60 seconds.'],['motion','Animations','Student reactions, paper movement and celebration confetti.'],['large','Extra-large stamps','Comfortable tablet controls. All buttons also work with a mouse or keyboard.']].map(([key,name,description])=>'<div class="settings-row"><label class="setting-label" for="setting-'+key+'"><div><strong>'+name+'</strong><small>'+description+'</small></div></label><input type="checkbox" id="setting-'+key+'" data-pref="'+key+'" '+(school.save.prefs[key]?'checked':'')+' aria-label="'+name+'"></div>').join('')+'<p style="font-size:11px;line-height:1.6;color:#7e8971">Career, purchases and an unfinished class save automatically on this browser or PocketVM profile.</p>');bindClose(()=>goBack(back));for(const x of $('modal').querySelectorAll('[data-pref]'))x.addEventListener('change',()=>{school.save.prefs[x.dataset.pref]=x.checked;prefs();save();if(x.dataset.pref==='timers'&&school.round?.inspection)$('inspection').hidden=!x.checked})}
function help(back='pause'){modalReturn=back;openModal('help',modalHead('The teacher’s notes')+'<div class="help-list"><p><b>Read. Decide. Stamp.</b><br>A+ means the answer is correct. F means it is wrong. Use the big stamps, Left/Right arrows, or F/A keys. Enter continues after feedback.</p><p><b>Whole worksheets</b><br>There are four answers. 4 correct = A+, 3 = B, 2 = C, 1 = D, 0 = F. The rubric stays on the paper.</p><p><b>Classroom moments</b><br>Sometimes you handle an incident instead of a paper. Read the evidence and choose the fairest response. Keyboard: 1, 2, 3.</p><p><b>Accurate work pays</b><br>Fair judgements earn 5 coins, with streak and inspection bonuses. A career day earns 10–25 extra coins. Spend them on the classroom. An answer-key-assisted stamp earns 1 coin and is excluded from challenge records.</p><p><b>Career & challenges</b><br>Six subjects unlock over the first three days. Whole worksheets and inspections start on day 5. Bell Rush is 60 seconds, including feedback; Class Marathon allows three mistakes, up to 150 papers. Daily Class uses the same date seed for everyone.</p><p><b>Touch, keyboard & pause</b><br>Large controls work in iPad portrait, landscape and split view. Escape pauses. Menus and hidden tabs pause all clocks. Papers stay saved if you leave.</p></div>');bindClose(()=>goBack(back))}
function trapFocus(e){if(!modalName||e.key!=='Tab')return;const nodes=[...$('modal').querySelectorAll('button:not(:disabled),input,select,a[href]')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
$('menuButton').addEventListener('click',()=>{if(!school.session||school.session.settled)welcome();else menu()});$('shopButton').addEventListener('click',()=>shop(modalName==='welcome'?'welcome':modalName==='summary'?'summary':'pause'));$('hintButton').addEventListener('click',()=>showHint());
document.addEventListener('keydown',e=>{trapFocus(e);if(e.repeat)return;if(e.key==='Escape'){e.preventDefault();if(modalName==='pause')closeModal();else if(modalName==='shop'||modalName==='settings'||modalName==='help')goBack(modalReturn||'pause');else if(!modalName)menu();return}if(modalName||document.activeElement?.tagName==='INPUT')return;if(result&&(e.key==='Enter'||e.key===' ')){e.preventDefault();next();return}if(result)return;const round=school.round;if(!round)return;let choice;if(round.kind==='incident'&&/^[123]$/.test(e.key))choice=String(Number(e.key)-1);else if(round.kind==='worksheet'&&/^[1-5]$/.test(e.key))choice=['A+','B','C','D','F'][Number(e.key)-1];else if(round.kind==='paper'){if(e.key==='ArrowLeft'||e.key.toLowerCase()==='f')choice='F';if(e.key==='ArrowRight'||e.key.toLowerCase()==='a')choice='A+'}if(choice!==undefined){e.preventDefault();mark(choice)}});
document.addEventListener('visibilitychange',()=>{hidden=document.hidden;last=performance.now();save()});window.addEventListener('pagehide',save);window.addEventListener('blur',()=>{paused=true;save()});window.addEventListener('focus',()=>{paused=false;last=performance.now()});window.addEventListener('error',e=>{if(!e.message)return;$('fatalMessage').textContent='Reload Grade School to return to your saved class.';$('fatal').hidden=false});
// Original vector classroom. Drawn directly in Canvas so it works without WebGL or external art.
let width=1,height=1,ratio=1,layout={};
function resize(){width=window.innerWidth;height=window.innerHeight;ratio=Math.min(1.6,window.devicePixelRatio||1);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);g.setTransform(ratio,0,0,ratio,0,0);measure();}
function measure(){const box=$('playArea').getBoundingClientRect(),side=document.querySelector('.class-side').getBoundingClientRect(),info=$('studentName').closest('.student-info').getBoundingClientRect();layout={box,side,info};}
window.addEventListener('resize',resize);window.addEventListener('orientationchange',resize);$('playArea').addEventListener('scroll',measure,{passive:true});
function rounded(x,y,w,h,r,fill,stroke,lw=2){g.beginPath();g.roundRect(x,y,w,h,r);if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.lineWidth=lw;g.stroke()}}
function line(points,colour,width=2){g.beginPath();points.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.strokeStyle=colour;g.lineWidth=width;g.stroke()}
function ellipse(x,y,rx,ry,fill,stroke,lw=2){g.beginPath();g.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);g.fillStyle=fill;g.fill();if(stroke){g.strokeStyle=stroke;g.lineWidth=lw;g.stroke()}}
function poly(points,fill,stroke,lw=2){g.beginPath();points.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.closePath();g.fillStyle=fill;g.fill();if(stroke){g.strokeStyle=stroke;g.lineWidth=lw;g.stroke()}}
function gradient(a,b,x,y,w,h){const v=g.createLinearGradient(x,y,x+w,y+h);v.addColorStop(0,a);v.addColorStop(1,b);return v}
function student(s,x,y,scale,expression=0,t=0,front=false){
 g.save();g.translate(x,y);g.scale(scale,scale);const wiggle=school.save.prefs.motion?Math.sin(t*1.5+s.id)*2:0;g.translate(0,wiggle);const outline='#3e504a',skin=s.skin,skinShade=shade(skin,-18),hair=s.hair;
 ellipse(0,240,91,17,'#36574626');
 // Rounded shoulders and a shirt with subtle dimensional shading.
 rounded(-63,140,126,107,29,gradient(s.shirt,shade(s.shirt,-22),-50,155,110,80),outline,3);
 rounded(-16,121,32,45,12,skin,outline,2);ellipse(0,153,24,9,skinShade);poly([[-27,149],[-9,161],[-22,182],[-43,151]],shade(s.shirt,23),outline,2);poly([[27,149],[9,161],[22,182],[43,151]],shade(s.shirt,23),outline,2);
 const arms=expression===1?Math.sin(t*4)*10:0;
 g.save();g.translate(-54,164);g.rotate(front&&expression===1?-.7:0);rounded(-17,0,32,72,14,skin,outline,2);ellipse(0,72+arms*.3,19,15,skin,outline,2);g.restore();g.save();g.translate(54,164);g.rotate(front&&expression===1?.7:0);rounded(-15,0,32,72,14,skin,outline,2);ellipse(0,72-arms*.3,19,15,skin,outline,2);g.restore();
 ellipse(-65,79,15,23,skinShade,outline,2);ellipse(65,79,15,23,skinShade,outline,2);rounded(-65,12,130,124,43,gradient(shade(skin,19),skinShade,-40,20,100,115),outline,3);
 // Different hair silhouettes, all drawn for this game.
 if(s.style===0){poly([[-65,62],[-65,32],[-46,6],[-5,-1],[42,6],[65,34],[65,53],[42,26],[25,35],[1,20],[-22,35],[-44,31]],hair,outline,2)}
 else if(s.style===1){ellipse(-65,31,20,29,hair,outline,2);ellipse(65,31,20,29,hair,outline,2);poly([[-65,71],[-70,32],[-43,-1],[23,-2],[63,21],[70,72],[48,34],[23,24],[-1,44],[-29,27],[-47,41]],hair,outline,2);rounded(-76,56,20,44,9,hair,outline,2);rounded(56,56,20,44,9,hair,outline,2);ellipse(-72,61,8,4,'#e8b268');ellipse(72,61,8,4,'#e8b268')}
 else if(s.style===2){for(let i=0;i<7;i++)ellipse(-53+i*18,18-Math.sin(i/6*Math.PI)*9,18,22,hair,outline,1);poly([[-65,28],[-52,43],[-37,24],[0,34],[29,23],[57,44],[66,31]],hair)}
 else{rounded(-69,2,138,74,39,hair,outline,3);poly([[-60,61],[-51,29],[-32,49],[-14,31],[8,44],[34,25],[52,66],[45,17],[-49,14]],hair);rounded(-72,46,17,77,8,hair,outline,2);rounded(56,46,17,77,8,hair,outline,2)}
 const blink=school.save.prefs.motion&&(t*1.2+s.id*.63)%5>.0&&(t*1.2+s.id*.63)%5<.13,eyeH=blink?1.8:expression===-1?9:15;
 ellipse(-27,75,16,eyeH,'#fffaf0',outline,1.5);ellipse(27,75,16,eyeH,'#fffaf0',outline,1.5);if(!blink){ellipse(-24,77,7,Math.min(eyeH-1,10),'#29463c');ellipse(30,77,7,Math.min(eyeH-1,10),'#29463c');ellipse(-21,73,2.5,3,'#fff');ellipse(33,73,2.5,3,'#fff')}
 line([[-44,52],[-20,expression===-1?57:49]],hair,4);line([[20,expression===-1?57:49],[44,52]],hair,4);ellipse(-43,99,12,6,'#c9736b45');ellipse(43,99,12,6,'#c9736b45');ellipse(3,94,10,6,skinShade);line([[0,85],[-3,93],[3,95]],skinShade,2);
 g.beginPath();g.moveTo(-17,111);g.quadraticCurveTo(0,expression===1?137:expression===-1?106:123,17,111);g.strokeStyle='#694c3c';g.lineWidth=3;g.stroke();if(expression===1){poly([[-14,114],[0,121],[14,114]],'#fff5e3')}
 if(s.id===5||s.id===10){rounded(-48,59,42,32,10,null,'#354e47',3);rounded(6,59,42,32,10,null,'#354e47',3);line([[-6,71],[6,71]],'#354e47',3)}
 if(front){const desk=C.SHOP.find(x=>x.id===school.save.equipped.desk).colour;poly([[-112,227],[89,221],[115,257],[-127,266]],shade(desk,17),'#7c674d',3);poly([[-127,266],[115,257],[115,281],[-127,289]],desk,'#7c674d',3);poly([[-98,289],[-86,289],[-87,350],[-99,350]],shade(desk,-16));poly([[83,282],[94,281],[99,343],[88,344]],shade(desk,-16));poly([[-36,239],[34,235],[43,256],[-31,260]],'#fff7dd','#acb7a1',1);line([[-18,245],[25,242]],'#849bad',2);line([[-15,253],[18,250]],'#849bad',2);rounded(60,245,35,5,2,'#e6b856','#9f8158',1)}
 g.restore();
}
function shade(hex,amount){const n=parseInt(hex.slice(1),16);return'#'+[n>>16,(n>>8)&255,n&255].map(v=>Math.max(0,Math.min(255,v+amount)).toString(16).padStart(2,'0')).join('')}
function drawRoom(t){
 if(!g)return;const room=C.SHOP.find(x=>x.id===school.save.equipped.room).colour,wall=height*.48;
 g.fillStyle=gradient(shade(room,17),room,0,0,width,wall);g.fillRect(0,0,width,height);poly([[0,wall],[width,wall-8],[width,height],[0,height]],gradient('#e2cf9f','#c3a87b',0,wall,0,height-wall));line([[0,wall],[width,wall-8]],'#8da491',7);
 const vanish={x:width*.52,y:wall-100};for(let i=-3;i<12;i++)line([[vanish.x+(i-5)*60,wall],[width/10*i,height]],'#a5875b22',2);for(let i=0;i<8;i++){const p=i/7,y=wall+(height-wall)*p*p;line([[0,y],[width,y-8*(1-p)]],'#a5875b25',2)}
 // Big windows and softly lit side walls.
 const wx=width*.035,wy=Math.max(97,height*.14),ww=Math.min(width*.2,215),wh=Math.min(height*.27,210);rounded(wx+6,wy+7,ww,wh,9,'#647f7040');rounded(wx,wy,ww,wh,8,'#f3e4c6','#a69372',5);rounded(wx+10,wy+10,ww-20,wh-20,2,gradient('#98c5d3','#d9ecdf',wx,wy,0,wh));g.save();g.beginPath();g.rect(wx+10,wy+10,ww-20,wh-20);g.clip();ellipse(wx+ww*.78,wy+wh*.22,22,22,'#f9e6a2');poly([[wx,wy+wh],[wx,wy+wh*.65],[wx+ww*.4,wy+wh*.4],[wx+ww*.75,wy+wh*.8],[wx+ww,wy+wh*.62],[wx+ww,wy+wh]],'#91b39e');ellipse(wx+ww*.22,wy+wh*.3,30,8,'#eff3df');g.restore();line([[wx+ww*.5,wy+8],[wx+ww*.5,wy+wh-6]],'#efe7ce',7);line([[wx+8,wy+wh*.5],[wx+ww-6,wy+wh*.5]],'#efe7ce',7);poly([[wx+ww,wy+wh],[wx+ww*1.6,height],[wx+ww*.4,height],[wx,wy+wh]],'#ffecb91a');
 // Classroom chalkboard, alphabet and pinboard.
 const bx=width*.29,bw=width*.43,by=Math.max(95,height*.115),bh=Math.max(110,Math.min(170,height*.24));rounded(bx+5,by+7,bw,bh,5,'#42655235');rounded(bx,by,bw,bh,4,'#b38c61','#8a6a4f',3);rounded(bx+10,by+10,bw-20,bh-20,1,'#2d5b4e');g.fillStyle='#dbecd5';g.font='600 '+Math.min(26,bw/17)+'px "Trebuchet MS",sans-serif';g.textAlign='center';g.fillText('A B C D E F G H I J K L M',bx+bw/2,by+40);g.fillStyle='#b6c9b6';g.font='italic '+Math.min(21,bw/20)+'px serif';g.fillText('Be curious. Be kind.',bx+bw/2,by+bh*.66);line([[bx+23,by+bh-25],[bx+bw-25,by+bh-25]],'#9bbfaf50',1);rounded(bx+22,by+bh-10,41,8,2,'#d8e4ce');rounded(bx+bw-62,by+bh-12,37,12,2,'#7e9b7d');
 const px=width*.79,py=by+10,pw=Math.min(width*.18,190),ph=Math.min(bh,150);rounded(px,py,pw,ph,7,'#b38a62','#8d7155',3);for(let i=0;i<4;i++){const x=px+16+(i%2)*pw*.47,y=py+15+Math.floor(i/2)*ph*.47;g.save();g.translate(x,y);g.rotate((i-1.5)*.06);rounded(0,0,pw*.36,ph*.34,2,['#ece6c2','#d7e3ce','#eac9c4','#d8d0e7'][i]);line([[10,14],[pw*.29,14]],'#7b977950',3);line([[10,24],[pw*.26,24]],'#7b977950',2);ellipse(pw*.17,3,3,3,'#cc7968');g.restore()}
 // Quiet classmates receding into the background.
 if(width>680){for(let row=0;row<2;row++){const y=wall+row*(height-wall)*.12,sc=.20+row*.07;for(let col=0;col<5;col++){const x=width*.27+col*width*.15;student(C.STUDENTS[(row*5+col+3)%12],x,y-155*sc,sc,0,t,false);const desk='#ba9568';poly([[x-40*sc,y+35*sc],[x+38*sc,y+30*sc],[x+53*sc,y+70*sc],[x-50*sc,y+72*sc]],desk);line([[x-40*sc,y+72*sc],[x-40*sc,y+130*sc]],'#856d53',4*sc);line([[x+42*sc,y+70*sc],[x+42*sc,y+120*sc]],'#856d53',4*sc)}}}
 if(school.save.owned.includes('bunting')){for(let i=0;i<12;i++){const x=width*.3+i*width*.038,y=83+Math.sin(i/11*Math.PI)*30;poly([[x,y],[x+18,y+3],[x+8,y+24]],['#d98177','#e3bb60','#86b39b','#aa98c2'][i%4])}line([[width*.3,83],[width*.52,113],[width*.74,83]],'#85976d',2)}
 if(school.save.owned.includes('clock')){const x=width*.745,y=by+28;ellipse(x,y,28,28,'#fbefcf','#758d71',4);for(let i=0;i<12;i++){const a=i*Math.PI/6;line([[x+Math.sin(a)*21,y-Math.cos(a)*21],[x+Math.sin(a)*24,y-Math.cos(a)*24]],'#8d9c7a',2)}line([[x,y],[x+6,y-14]],'#476b57',3);line([[x,y],[x-12,y]],'#476b57',3);ellipse(x,y,3,3,'#cb8170')}
 if(school.save.owned.includes('books')){const x=width*.91,y=wall-45;rounded(x-50,y-90,100,160,4,'#a48663','#7e7153',3);for(let row=0;row<3;row++){line([[x-47,y-39+row*46],[x+47,y-39+row*46]],'#75654b',5);for(let i=0;i<6;i++)rounded(x-40+i*13,y-80+row*46,10,35-i%3*4,1,['#af8ab1','#6d9c9c','#dca169','#87a56b'][i%4])}}
 if(school.save.owned.includes('plant')){const x=wx+ww*.75,y=wy+wh+10;poly([[x-16,y-27],[x+16,y-27],[x+11,y],[x-11,y]],'#c88869','#916b52',2);for(let i=0;i<7;i++){const a=(i-3)*.28;line([[x,y-27],[x+Math.sin(a)*25,y-57-Math.cos(a)*24]],'#5e8a66',3);ellipse(x+Math.sin(a)*25,y-57-Math.cos(a)*24,7,13,['#8bae71','#6a986b'][i%2])}}
 if(school.save.owned.includes('globe')){const x=width*.82,y=wall+75;rounded(x-31,y+28,62,9,5,'#a28957');line([[x,y+25],[x,y+5]],'#7f8061',6);ellipse(x,y-15,29,29,'#81b5c5','#58796f',3);poly([[x-15,y-35],[x+6,y-38],[x+19,y-22],[x+3,y-8],[x-3,y+7],[x-15,y-3]],'#91b486');g.beginPath();g.ellipse(x,y-15,36,31,-.25,-Math.PI*.58,Math.PI*.59);g.strokeStyle='#bf9e5e';g.lineWidth=4;g.stroke()}
 if(school.save.owned.includes('hamster')){const x=width*.9,y=wall+90;rounded(x-41,y-31,83,65,10,'#c0cdbf88','#7a978b',3);rounded(x-45,y+29,91,13,3,'#bd8b69','#846f59',2);const move=school.save.prefs.motion?Math.sin(t)*10:0;ellipse(x+move,y+18,19,14,'#d8aa70','#8d7459',1);ellipse(x+move+13,y+10,12,11,'#e9c491');ellipse(x+move+10,y,5,6,'#c69077');ellipse(x+move+21,y+8,2,2,'#38534b');for(let i=0;i<6;i++)line([[x-33+i*13,y-28],[x-33+i*13,y+28]],'#97b3a177',1)}
 // The student at the marking desk uses the available left-hand play space.
 const side=layout.side,info=layout.info;
 if(side){if(width<=680){const sc=.35,x=side.x+side.width*.21,y=side.y+14;student(activeStudent,x,y,sc,emotionUntil>t?emotion:0,t,true)}else{const usable=Math.max(145,(info?.y||height-120)-side.y-48),sc=Math.max(.48,Math.min(side.width/250,usable/345)),x=side.x+side.width*.49,y=side.y+45+Math.max(0,(usable-sc*345)/2);student(activeStudent,x,y,sc,emotionUntil>t?emotion:0,t,true)}}
 // Foreground teacher's desk edge ties the UI to the classroom.
 const desk=C.SHOP.find(x=>x.id===school.save.equipped.desk).colour;poly([[width*.3,height-13],[width,height-47],[width,height],[width*.25,height]],shade(desk,-7));line([[width*.3,height-13],[width,height-47]],shade(desk,20),3);
}
function frame(now){
 const dt=Math.min(1,Math.max(0,(now-(last||now))/1000));last=now;if(!hidden&&!paused){frameTime+=dt;if(!modalName&&school.session&&!school.session.settled){
  // Rush clock includes the feedback interval; menus and hidden/focused-away tabs pause it.
  if(result){if(school.session.mode==='rush')school.session.timeLeft=Math.max(0,school.session.timeLeft-dt)}else{const timeout=school.tick(dt);if(timeout){result=null;showTimedOut(timeout)}}
  if(school.session.mode==='rush'){const remaining=Math.ceil(school.session.timeLeft);$('countMeta').textContent=remaining+' SECONDS';$('sideValue').textContent=remaining;$('progressFill').style.width=(60-school.session.timeLeft)/60*100+'%';if(school.session.timeLeft<=0)showSummary()}
  if(school.round?.inspection)$('inspectionTime').textContent=Math.ceil(school.session.paperTime);
  if(now-lastSave>1500)save();
 }}
 if(now-lastDraw>40){measure();drawRoom(frameTime);lastDraw=now}requestAnimationFrame(frame);
}
function showTimedOut(answer){result=answer;feedbackUntil=frameTime+.3;emotion=-1;emotionUntil=frameTime+3;$('speech').textContent='The bell got there first.';$('feedback').classList.add('wrong');$('feedback').innerHTML='<div class="seal">TIME’S UP</div><h2>A quick look at the key.</h2><div class="correct-answer"><p style="margin:0">'+explanation(answer.round)+'</p></div><p style="text-align:center;margin-top:15px">The paper deserved <b>'+answer.answer+'</b>.</p><button class="primary" id="nextPaper">'+(school.finished?'Ring the bell →':'Next student →')+'</button>';$('feedback').hidden=false;$('nextPaper').addEventListener('click',next);stats();save();sound('bad')}
prefs();resize();stats();if(school.session&&school.finished&&!school.session.settled)showSummary();else welcome();requestAnimationFrame(frame);ready();
})();
